/* eslint-disable max-len */
export default {
  home: "Home",
  profile: "Profile",
  detail: "Detail",
  setting: "Setting",
  language: "Language",
  darkMode: "Dark mode",
  switchLanguage: "Switch language",
  approve: "Approve",
  cancel: "Cancel",
  placeholderEmaiPhone: "Email/Phone number",
  placeholderEmail: "Email",
  placeholderVerifyCode: "Verify code",
  placeholderPasword: "Password",
  forgotPassword: "forgot password",
  verifyCodeTitle: (text: string) => `Input verify code from email ${text}`,
  signIn: "Sign in",
  signUp: "Sign up",
  signInWith: "Sign in with",
  continue: "Continue",
  continueWith: (text: string) => `Continue with ${text}`,
  enterNewPassword: "Enter new password",
  confirmPassword: "Confirm password",
  enterOTP: "Enter otp",
  updatePassword: "Update password",
  save: "Save",
  required: "required",
  invalid: "Invalid",
  or: "Or",
  welcomeBack: "Welcome back!",
  minLength: (number: number) => `at least ${number} charectors`,
  needAnAccount: "Need an account? ",
  registerNow: "Register now!",
  createNewAccount: "Create new account!",
  fullname: "Fullname",
  haveAnAccount: "Have an account? ",
  loginNow: "Login now!",
  welcomeHeader: "Welcome to the World of Languages",
  welcomeDescription:
    "Learning has never been to easy! With IELTS you will learn ...",
  startNow: "Start Now",
  sendingError: "An error occurred!",
  createPassSuccess: "Create new password success!",
  loginSuccess: "Login success!",
  error: {
    unknown: "Unknow error!",
    invalidPhoneEmail: "Phone/Email invalid",
    passDoesNotMatch: "Confirmation password does not match",
    minLengthPass: "Password must be at least 6 characters",
    errorPatternPass:
      "Password includes at least 8 characters including letters, numbers and special characters, lowercase and uppercase",
  },
};
/* eslint-disable max-len */
