/* eslint-disable max-len */
export default {
  detail: "Detail",
  setting: "Setting",
  openSetting: "Open setting",
  language: "Language",
  darkMode: "Dark mode",
  switchLanguage: "Switch language",
  approve: "Approve",
  cancel: "Cancel",
  placeholderEmaiPhone: "Email/Phone number",
  placeholderEmail: "Email",
  placeholderVerifyCode: "Verify code",
  placeholderPasword: "Password",
  forgotPassword: "forgot password",
  verifyCodeTitle: (text: string) => `Input verify code from email ${text}`,
  signIn: "Sign in",
  signUp: "Sign up",
  signInWith: "Sign in with",
  continue: "Continue",
  continueWith: (text: string) => `Continue with ${text}`,
  enterNewPassword: "Enter new password",
  confirmPassword: "Confirm password",
  enterOTP: "Enter OTP",
  updatePassword: "Update password",
  save: "Save",
  required: "required",
  invalid: "Invalid",
  or: "Or",
  welcomeBack: "Welcome back!",
  minLength: (number: number) => `at least ${number} charectors`,
  needAnAccount: "Need an account? ",
  registerNow: "Register now!",
  createNewAccount: "Create new account!",
  fullname: "Fullname",
  haveAnAccount: "Have an account? ",
  loginNow: "Login now!",
  welcomeHeader: "Welcome to the World of Languages",
  welcomeDescription:
    "Learning has never been to easy! With IELTS you will learn ...",
  startNow: "Start Now",
  sendingError: "An error occurred!",
  createPassSuccess: "Create new password success!",
  loginSuccess: "Login success!",
  goBackHome: "Go back home",
  next: "Next",
  other: "Other",
  recordAudio: "Record audio",
  playAudio: "Play audio",
  stopAudio: "Stop audio",
  keepGoing: "Keep going",
  changeLanguage: "Choose the language",
  error: {
    unknown: "Unknow error!",
    invalidPhoneEmail: "Phone/Email invalid",
    invalidEmail: "Email invalid",
    invalidPhone: "Phone invalid",
    invalidLink: "Link invalid",
    invalidYoutube: "Link youtube invalid",
    invalidFacebook: "Link facebook invalid",
    passDoesNotMatch: "Confirmation password does not match",
    minLengthPass: "Password must be at least 6 characters",
    errorPatternPass:
      "Password includes at least 8 characters including letters, numbers and special characters, lowercase and uppercase",
    isOffline: "Connect to internet and retry!",
  },
  channelLocked: "The channel is temporarily locked",
  channelLockedDes: "Go to website to active channel",
  create_Channel: "Create Channel",
  postCategory: "Select category",
  createPost: "Create post",
  placeholderContent: "What’s on your mind?",
  createChannel: "Create Channel",
  unblock: "Unblock",
  confirm: "Confirm",
  somethingWentWrong: "Something went wrong. Please try again.",
  notFound: "Empty List",
  offlineNetwork: "You are currently offline",
  onlineNetwork: "You internet connection was restored",
  all: "All",
  seconds: "seconds",
  minutes: "minutes",
  hours: "hours",
  days: "days",
  weeks: "weeks",
  months: "months",
  years: "years",
  ago: "ago on",
  copied: "Copied",
  thankyouForReport:
    "Thank you for reporting, we will carefully review this content!",
  copy: "Copy",
  report: "Report",
  block: "Block",
  unBlockUser: "Unblock",
  blockedDes: "You will not be able to see or contact each other",
  blockedUser: "You have blocked the profile of :username",
  commentAs: "Comment as",
  replying: "Replying",
  reply: "reply",
  like: "like",
  comment: "comment",
  delete: "Delete",
  edit: "Edit",
  duplicate: "Duplicate",
  copyLink: "Copy link",
  pinToTop: "Pin to top",
  turnOfComments: "Turn off comments",
  turnOnComments: "Turn on comments",
  deleteSuccess: "Successfully deleted",
  updateSuccess: "Successfully updated",
  pinned: "Pinned",
  hide: "Hide",
  online: "Online now",
  offline: "Offline",
  status: "Status",
  joined: "Joined",
  bio: "Bio",
  contributions: "Contributions",
  follower: "Follower",
  following: "Following",
  follow: "Follow",
  unfollow: "Unfollow",
  followed: "Followed",
  message: "Message",
  filter: "Filter",
  sort: "Sort",
  search: "Search...",
  notInGroup: "You are not in any organization",
  createChannel: "You can create an organization using the following ",
  notInGroup: "You are not in any organization",
  createChannelDes: "You can create an organization using the following ",
  joinViaInvite:
    "You can send your email to the owner of an organization so they can invite you to join.",
  deleteConfirm: "Are you sure to want delete this?",
  update: "Update",
  viewAll: "View All",
  aboutMe: "About me",
  noReferrals: "There are no referrals yet!",
  noCertificates: "Teachers have not updated their certificates!",
  today: "Today",
  yesterday: "Yesterday",
  tomorrow: "Tomorrow",
  from: "From",
  to: "To",
  continue: "Continue",
  justNow: "Just now",
  openFile: "Open File",
  openFileDes: "Do you want to open file in the browser?",
  active: "Active",
  updateAvailable: "Update available",
  updateAvailableDes:
    "There is a new version of the app available on the App Store, download it?",
  seemore: "...See more",
  selectImage: "Select Image",
  draft: "Draft",
  public: "Public",
  cancelEdit: "Cancel confirm",
  cancelEditDes: "Edits will not be saved. Do you want to continue?",
  clear: "Clear all",
  searchForKey: "Results for keywords: ",
  post: {
    post: "Post",
    posts: "Post",
    detailPost: (name: string) => `${name}'s post`,
    createPost: "Create Post",
    category: "Category",
    title: "Title",
    content: "Content",
    poll: "Poll",
    removePoll: "Remove Poll",
    addOption: "Add Option",
    addVideo: "Add video",
    addVideoDes: "Add a Youtube, Vimeo or Wistia link.",
    link: "Link",
    pleaseInputTitleOrContent: "Please input title or content",
    pleaseSelectCategory: "Please select category",
    pollMinLength: "Poll need at least 2 answers",
    createPostSuccess: "create post successfully",
    like: "Like",
    liked: "Liked",
    share: "Share",
    comment: "Comment",
    comments: "comments",
    likeThisPost: "like this post",
    personLiked: "The person who liked",
    emptyComment: "No comments yet",
    emptyCommentDes: "Start the conversation",
    emptyPost: "There are no posts yet",
    emptyPostTitle: "There is no article",
    emptyPostDes:
      "When a friend or a teacher posts an article, it will appear here, and you can then like, share, and comment on the post.",
    postInvalid: "Invalid post",
    report: "Report this post",
    save: "Save post",
    likeError: "Send like error, please try again!",
    savePostSuccess: "Save post success",
    listPostSave: "Post save",
    deleteFromSave: "Delete from save",
    emptyListSave: "Saved posts list is empty",
  },
  navigation: {
    dashboard: "Dashboard",
    courses: "Courses",
    leaderboards: "Leaderboards",
    notifications: "Notifications",
    menu: "Menu",
    messages: "Messages",
  },
  switchGroups: "Switch Groups",
  createGroup: "Create a group",
  login: {
    continueFacebook: "Continue with Facebook",
    continueGoogle: "Continue with Google",
    continueApple: "Continue with Apple",
    email: "Email",
    emailPhone: "Email / Phone number",
    fullname: "Fullname",
    description: "Description",
    password: "Password",
    signin: "Sign in",
    signup: "Sign up",
    signinWithPassword: "Sign in with password",
    dontHaveAccount: "Don't have an account?",
    or: "Or",
    orContinueWith: "or continue with",
    descriptionSignin: "By signing in, you're agree to our ",
    descriptionSignup: "By signing up, you're agree to our ",
    termConditions: "Terms & Conditions",
    privacyPolicy: "Privacy Policy",
    and: " and ",
    our: "",
    alreadyHaveAccount: "Already have an account?",
    letYouIn: "Let's you in",
    createYourAccount: "Create your account",
    loginError: "Have an Error while Login, please try again!",
    registerSuccess: "Successfully registered",
    forgotPassword: "Forgot Password",
    send: "Send",
    forgotPasswordSuccess:
      "Successfully sent an email, please check your email!",
    requireLogin: "You need login for using this feature",
    bylogin: "By login or signing up, you're agree to our",
    term: "Terms & Conditions",
    police: "Privacy Policy",
  },
  validate: {
    emailInvalid: "Email is invalid",
    emailPhoneInvalid: "Email / Phone is invalid",
    numberInvalid: "Number is invalid",
    requiredEmail: "Email is required",
    requiredPassword: "Password is required",
    requiredFullName: "Fullname is required",
    errorOldPassword: "Old password is required",
    errorNewPassword: "New password is required",
    errorConfirmPasswordNotMatch: "Password doesn't match",
    errorConfirmPassword: "Confirm password is required",
    requiredDate: "Date is required",
    requiredName: "Name is required",
    requiredTime: "Time is required",
    requiredDuration: "Duration is required",
    requiredLocation: "Location is required",
    requiredAttend: "Attend is required",
    requiredLink: "Link is required",
    requiredDayOfWeeks: "Day of week is required",
    requiredOccurrences: "Occurrences is required",
    numberOccurrences: "Occurrences must be a number",
    invalidInput: "Input is invalid",
    requiredDescription: "Description is required",
    requiredLevel: "Level is required",
    requiredCourse: "Course is required",
    pointBetween: "Point must be between :min and :max",
    requiredPhoneNumber: "Phone number is required",
    phoneNumberInvalid: "Phone number is invalid",
  },
  home: {
    whatonYourMind: "What's on your mind",
    dontHasPermissionToCreate: "You can't create a new post",
    commentSuccess: "Commented successfully",
    typeComment: "Type your comment...",
    recentActivity: "Recent activity",
    mostPopular: "Most Popular",
    mostLike: "Most Likes",
    trending: "Trending",
    beFirstComment: "Be the first to comment",
    image: "Image",
    file: "File",
    poll: "Vote",
    select: "Select",
    maximunImage: "Maximum :count image",
    emptyList: "Empty list",
    deletePostSuccess: "Delete post success",
    deletePost: "Delete post?",
    deleteComment: "Delete comment",
  },
  chat: {
    search: "Search",
    cancel: "cancel",
    weHaveRemovedErrorPhoto:
      "We have removed error photo files or videos longer than 1 minutes",
    sendYourAudioMessage: "Send your audio message",
    releaseToSend: "Release to send, move to the right to use hand-free mode",
    holdToRecord: "Hold to record",
    permissionToRecord:
      "Permission to record, write data and access library are required to use this function",
    grandPermission: "Grant permission",
    noPeopleFound: "Currently this channel has no one to chat with",
    emptyListChat:
      "You have never talked to anyone. Try starting a conversation with",
    typeMessage: "Type a message...",
    lastSeen: "Last seen: ",
    desRecord: "Tap the microphone icon to start recording",
  },
  keyboard: {
    writeSomething: "Write something",
    sending: "Sending...",
  },
  common: {
    yrs: "yrs",
    hrs: "hrs",
    mins: "mins",
    secs: "secs",
    seconds: "seconds",
    minutes: "minutes",
    hours: "hours",
    days: "days",
    months: "months",
    years: "years",
    at: "at",
  },
  course: {
    course: "Course",
    newCourse: "New Course",
    createCourse: "Create Course",
    updateCourse: "Update Course",
    uploadCoverImageOrVideo: "Upload an introductory photo or video",
    add: "Add",
    warningDelete: "Are you sure you are deleting this course?",
    warningFull: "Select complete information",
    duration: "Duration",
    timeStart: "Time start",
    day: "Day",
    schedule: "Schedule",
    selectedTime: "Please choose at least one session",
    warningUploadCoverImageOrVideo:
      "Please select a video/photo introducing the course",
    uploadCoverImage: "Upload cover image",
    addCourse: "Add Course",
    courseName: "Course Name",
    courseDescription: "Course description",
    courseLongDescription: "Detail course",
    whoCanAccessThisCourse: "Who can access this course",
    publish: "Publish",
    videoTooLong: "Please choose a video that is less than 5 minutes long",
    pleaseFillInformation: "Please fill information",
    createCourseSuccess: "Successfully created source",
    open: "OPEN",
    join: "Join now",
    description: "Description",
    mentor: "Mentor",
    viewProfile: "View Profile",
    educationProgram: "Education Program",
    viewMore: "View More",
    hideLess: "Hide less",
    rate: "Rate",
    rankTeacher: "Instructor ratings",
    student: "Student",
    courseContent: "Course content",
    requestSkills: "Request skills",
    information: "Information",
    instructor: "Instructor",
    titleModule: "Title Module",
    updateModule: "Update Module",
    updateModuleSuccess: "Successfully updated",
    createModuleSuccess: "Successfully created",
    addModule: "Add Module",
    enterModuleName: "Enter Module Name",
    media: "Media",
    chooseFile: "Choose File",
    downloadDocument: "Download Document",
    openWebsite: "Open document",
    editModule: "Edit Module",
    consistsOf: "Consists of",
    parts: "parts",
    lectures: "lectures",
    requireLevel: "Require level",
    selectVideoModule: "Choose a lesson to get started",
    addVideo: "Add video",
    addFile: "Add file",
    requireLevelDes: "SORRY YOU ARE NOT LEVEL ENOUGH TO OPEN THIS COURSE",
    emptyCourse: "There are no courses available",
    typeLearning: "Type of Learning",
    formLearning: "Form of Learning",
    filterSpeaker: "Native teachers",
    viewResult: (text: string) =>
      text != "0" ? "View " + text + " courses" : "No result find",
    moreCouresBy: (name: string) => `More course buy ${name}`,
    viewResultTutor: (text: string) =>
      text != 0 ? "View " + text + " tutors" : "No result find",
    priceCourse: "Course Price",
    filterLevel: "Course Level",
    select: "Select",
    price_low: "Price: lowest first",
    price_high: "Price: highest first",
    rating: "Highest rating",
    newest: "Sort by newest",
    teacher: "Tutor",
    lastUpdate: "Last update",
    buyNow: "Buy now",
    addToCart: "Add to cart",
    filter: "Filter",
    formOfLearn: "From of learning",
    allForms: "All forms",
    callOneVsOne: "Call 1-1",
    salfLearning: "Salf learning",
    callGroup: "Call group",
    skills: "Skills",
    allSkills: "All skills",
    listening: "Listening",
    reading: "Reading",
    writing: "Writing",
    Speaking: "Speaking",
    pricePerCourse: "Price per course",
    minimum: "Minimum",
    maximum: "Maximum",
    levelsOfStudy: "Level of study",
    timeAvailable: "Time available",
    dayTime: "Day time",
    eveningAndNight: "Evening and night",
    onlyEnglish: "Only English native speakers",
    levelsOfTutor: "Levels of Tutor",
    bestSeller: "Best-seller",
    growYourListening: "Grow your listening skill",
    growYourReading: "Grow your reading skill",
    growYourWriting: "Grow your writing skill",
    growYourSpeaking: "Grow your speaking skill",
    sortBy: "Sort by",
    calendar: "Calendar",
    reviews: "Review",
    apply: "Apply",
    placeholderReiview: "Input review",
    sendReview: "Send review",
    updateReview: "Update review",
    certifications: "Certifications",
    more: "More",
    previewThisCourse: "Preview this course",
    watchIntro: "Watch the introductory video",
    title: "Title",
    longDescription: "Long description",
    startTime: "Start time",
    endTime: "End time",
    limitMember: "Limit member",
    createClass: "Create class",
    listClass: "List class",
    createClassSuccess: "Create class success",
    addLesson: "Add lesson",
    titleLesson: "Title lesson",
    updateLesson: "Update lesson",
    addLessonSuccess: "Add lesson success",
    addPart: "Add part",
    addPartSuccess: "Add part success",
    aboutThisCourse: "About this course",
    shareThisCourse: "Share this course",
    resources: "Resources",
    addCourseToFavourites: "Add course to favourites",
    reportAPlaybackProblem: "Report a playback problem",
    wriveAReview: "Write a review",
    enrollNow: "Enroll now",
    viewHomework: "View homework",
    Lectures: "Lectures",
    warningSelectTime: "Please select full time",
    warningSelectImage: "Please select image",
    warningSelectTimeGreater:
      "The start time cannot be greater than the course end time",
    deleteClass: "Delete class",
    deleteClassSuccess: "Delete class successfully",
    deleteClassError: "Class deletion failed",
    uploadVideoFailed: "Upload image/video failed",
    deleteClassDes: "Are you sure you want to delete this class?",
    deleteModule: "Delete module",
    deleteModuleSuccess: "Delete module successfully",
    deleteModuleError: "Module deletion failed",
    deleteModuleDes: "Are you sure you want to delete this module?",
    typeCourse: "Type of course",
    videoReviewCourse: "Video review course",
    requiredTitle: "Title is required",
    publicCourse: "Public course",
    discountEntry: "start at",
    endAt: "end at",
    noreview: "Zero review",
    selectModal: "Select",
    myCourse: "My course",
    noClass: "Empty class",
    manageClass: "Manage classes",
    recommendCourse: "Recommend course",
    teachingTime: "Teaching time",
    sortByTutor: "Sort tutor by",
    warningLengthRequired: "Reviews must be longer than 10 characters",
    updateRateSuccess: "Successful review update",
    sendRateSuccess: "Review submitted successfully",
    level_low: "Level: lowest first",
    level_high: "Level: highest first",
    delete: "Delete course",
    report: "Report course",
    deleteCourseSuccess: "Course deleted successfully",
    updateSuccess: "Update successfully",
    timeStartAt: "Start at",
    allCourse: "All course",
    allTutor: "All tutor",
  },
  seeAll: "See all",
  settings: {
    shortcut: "Shortcut",
    calendar: "Calendar",
    events: "Events",
    members: "Members",
    leaderboards: "Leaderboards",
    about: "About",
    settings: "Settings",
    profile: "Profile",
    logout: "Logout",
    invite: "Invite",
    general: "General",
    categories: "Categories",
    plugins: "Plugins",
    metrics: "Metrics",
    gamification: "Gamifications",
    links: "Links",
    billing: "Billing & referrals",
    pending: "Pending",
    block: "Block",
    remove: "Remove",
    notificationLevel:
      "Please earn {need point} points to reach the next level",
    maxLevel: "You are maximum level",
    shortcuts: "All Shortcuts",
    becomeAMentor: "Become a  Mentor",
    navigationBar: "Navigation Bar",
    becomeMentorDes: "Become a Mentor, you will:",
    becomeMentorDes1: "Shared Unlimited Sales",
    becomeMentorDes2: "Create New Courses",
    becomeMentorDes3: "And hundreds of exclusive VIP privileges",
    addLevel: "Add Level",
    deleteDes: "Are you sure you want to delete {level}?",
    point: "points",
    settingPoint: "Point Settings",
    inviteUser:
      "People invited with this link will go though the membership approval process. Want your invites to skip the approval process? Invite via email",
    sendEmailSuccess: "An invitation has been sent to the email",
    newAudio: "New Audio",
    soundSetting: "Add signature sound",
    deleteAccount: "Delete Account",
    deleteAccountConfirm: "(!!) Are you sure you want to delete this account?",
    deleteAccountSuccess: "Account deleted successfully",
    deleteAccountFaild: "Account deletion failed",
    deleteAccountDes:
      "We hate to see you go... Help us improve our service by letting us know why you're decided to leave.",
    enterReason: "Enter your reason",
    category: "Category",
    channel: "Channel",
    comment: "Comment",
    course: "Course",
    level: "Level",
    module: "Module",
    request: "Request",
    create: "Create",
    update: "Update",
    delete: "Delete",
    banUser: "Ban User",
    removeUser: "Remove User",
    descriptionPoint:
      "This is the number of points the student will receive for each corresponding action",
    inviteDes:
      "You will get 4000 points for each friend who activates oyur code and earns 10000 points. Your friend will also get 1000 points as a reward.",
    changeLanguage: "Change Language",
  },
  codeActivations: {
    sortBy: "Sort by",
    timeLatest: "Time: Latest first",
    priceHighest: "Price: highest first",
    header: "Code activations",
    referrer: "Referrer",
    copyCodeSuccsess: "Copied",
    activate: "Activate",
    goTo: "Go to",
  },
  profile: {
    editProfile: "Edit Profile",
    saveProfile: "Save profile",
    profile: "Profile",
    account: "Account",
    notifications: "Notifications",
    chat: "Chat",
    bio: "Bio",
    addBio: "Add bio",
    address: "Address",
    phoneNumber: "Phone Number",
    socialLink: "Social Links",
    updateProfileSuccess: "Successfully updated profile",
    oldPassword: "Old password",
    newPassword: "New password",
    confirmPassword: "Confirm password",
    changePassword: "Change password",
    notifyMeByEmail: "Notify me by email",
    dontNotifyMeByEmail: "Don't Notify me by email",
    userNotifications: "User Notifications",
    whenSomebodyFollowsMe: "When somebody follows me",
    whenIEarnMoneyFromReferrals: "When I earn money from referrals",
    groupNotifications: "Group Notifications",
    digestEmailFrequency: "Digest Email Frequency",
    digestEmailFrequencyDes:
      "A summary of popular posts and member activity when you don't visit the group",
    notificationsEmailFrequency: "Notifications Email Frequency",
    notificationsEmailFrequencyDes:
      "A bundled summary of unread likes, comments, mentions and activity for posts/members I follow",
    postLikesNotifications: "Post likes notifications",
    postLikesNotificationsDes: "Notify me when somebody likes my post",
    adminAnnouncements: "Admin announcements",
    adminAnnouncementsDes:
      "Notify me when group admins make announcement posts",
    eventReminders: "Event reminders",
    eventRemindersDes:
      "Notify me of calendar events the day before they happen",
    daily: "Daily",
    weekly: "Weekly",
    every14Days: "Every 14-Days",
    monthly: "Monthly",
    never: "Never",
    mins: "min",
    hourly: "Hourly",
    hours: "hours",
    notifyMe: "Notify me",
    dontNotifyMe: "Don't notify me",
    yes: "Yes",
    no: "No",
    notifyChat:
      "Notify me with sound and blinking tab header when somebody messages me.",
    emailNotifications: "Email notifications",
    emailNotificationsDes:
      "If you're offline and somebody messages you, we'll let you know via email. We won't email you if you're online.",
    whoCanMessageMe: "Who can message me?",
    whoCanMessageMeDes:
      "Only members in the group you're in can message you. You choose what group users can message you from by turning your chat on/off below.",
    on: "On",
    off: "Off",
    pointToLevelUp: "points to level up",
    permisisonDenied: "Permission denied",
    permissionDeniedDes: (text) =>
      `There is currently no access to ${text}. Do you want to go to Settings so you can continue?`,
    shareProfile: "Share profile",
  },
  member: {
    chat: "chat",
    membership: "membership",
    memberOfGroup: "Members of the group",
    followSuccess: "Successfully followed {name}.",
    unfollowSuccess: "Unfollowed {name}.",
    blockSuccess: "{name} has been successfully locked.",
    deleteSuccess: "Delete success",
  },
  coupon: {
    coupon: "Coupon",
    couponMyCourse: "Discount code for my course",
    createCoupon: "Add new discount code",
    updateCoupon: "Update discount code",
    saveCoupon: "Save coupon",
    add: "Add",
    applyCoupon: "Apply coupon",
    update: "Update",
    save: "Save",
    title: "Discount code name",
    description: "Description",
    promotion: "Percentage discount",
    addCouponSuccess: "Added new discount code successfully",
    addCouponFailed: "Adding a new discount code failed",
    updateCouponSuccess: "Update discount code successfully",
    updateCouponFailed: "Update discount code failed",
    listCouponForMyCourse: "List coupon for my course",
    percentage: "Percentage (%)",
    value: "Value",
    warningCoupon: "Invalid reduced value",
    period: "Period",
    type: "Type discount",
    deleteCouponSuccess: "Delete coupon success!",
    deleteCouponFaild: "Delete coupon faild! Retry again.",
    warningDeleteCoupon: "Do you really want to delete this discount code?",
    selectCourse: "Select course",
    choose: "Choose",
    chooseProduct: "Choose product",
    applyForProduct: "Apply for product",
    reduce: "Reduce",
    reductionLevel: "Reduction level",
    notDisplay: "Not displayed to buyer",
  },
  event: {
    addEvent: "Add Event",
    updateEvent: "Update Event",
    title: "Title",
    date: "Date",
    time: "Time",
    duration: "Duration",
    timezone: "Timezone",
    recurringEvent: "Recurring Event",
    location: "Location",
    link: "Link",
    description: "Description",
    whoCanAttendThisEvent: "Who can attend this event",
    remindMembersByEmail: "Remind members by email 1 day before",
    create: "Create",
    library: "Library",
    repeatOn: "Repeat On",
    end: "End",
    repeatEvery: "Repeat Every",
    pleaseSelectDay: "Please select which day(s) your event will repeat on",
    after: "After",
    occurrences: "occurrences",
    uploadCoverImage: "Upload cover image",
    allMembers: "All members",
    membersAtLevel: "Members at a level",
    membersInCourse: "Members in a course",
    endDate: "End date",
    never: "Never",
    createEventSuccess: "Successfully created event",
    pleaseSelectImage: "Please select a cover image",
    peopleInterested: "people interested",
    interest: "Interest",
    interested: "Interested",
    eventOfSpeaker: "Events of speaker",
    detailEvent: "Detail event",
    suggestEvent: "Suggest event",
    yourEvent: "Your event",
    allEvent: "All events",
    join: "Join",
    eventNotFoundToday: "There are no events today",
    eventNotFound: "There are no events",
    eventConfirm: "Do you want to stop video calling",
    eventEndLive: "Do you want to stop the livestream session?",
  },
  notifications: {
    notifications: "Notifications",
    markAll: "Mark all as read",
    turnonChat: "Turn on notifications when a message arrives",
    turnonCourse:
      "Enable notifications when there are new updates for the course keywords",
    emptyNotification: "There are currently no announcements",
  },
  invite: {
    invitePeople: "Invite people",
    toJoin: "to join {channel}",
    sendInvite: "Send invite",
    getLink: "Get an invite link to share",
    titleInvite: "Do you have any invitation code?",
    desInvite: "Confirm your invitation code and you will receive 1000 Points",
    enterCode: "Enter code",
    enterCodeSuccess: "Enter referral code successfully",
    enterCodeFaild: "The referral code is incorrect, please try again.",
    send: "Send",
    codeActivations: "Code activations",
    emptyListInvite: "List invite is empty",
  },
  categories: {
    addCategory: "Add Category",
    edit: "Edit",
    delete: "Delete",
    add: "Add",
  },
  gamifications: {
    description:
      "Make your group fun! Personalize your group by naming your level. Incentivize engagement by unlocking courses when members reach a higher level.",
    level: "level",
    point: "Points",
    pointHigher: "The point must be higher than Level {level}",
    pointLower: "The point must be lower than Level {level}",
  },
  liveStream: {
    endLive: "Ending live broadcast",
    startLive: "Starting live broadcast...",
    tapToAddDescription: "Tap to add a description",
    goLive: "Go Live",
    finish: "Finish",
    addCover: "Add cover",
    change: "Change",
    warning: "Select photos before going live",
  },
  noResult: "No result found!",
  results: "results",
  sort_by_relevance: "Sort by",
  startChat: "Start a conversation!",
  startChatDesc:
    "Send a friendly message asking about their learning journey or discussing a common interest to start an interesting conversation.",
  noNewMessageTittle: "No new messages",
  noNewMessageDesc:
    "When you contact others or purchase a course, you will receive messages here.",
  actionView: {
    sendYourAudioMessage: "Send your audio message",
    releaseToSend: "Release to send, move to the right to use hand-free mode",
    holdToRecord: "Hold to record",
  },
  mediaKeyboard: {
    chooseFromGallery: "Choose from gallery",
    permissionToRecord:
      "Permission to record, write data and access library are required to use this function",
    grandPermission: "Grant permission",
    weHaveRemovedErrorPhoto:
      "We have removed error photo files or videos longer than 1 minutes",
    attention: "Attention!",
    imageIsError: "Image is error!",
    shootAVideo: "Shoot a video",
    takeAPhoto: "Take a photo",
  },
  audio: {
    pause: "Pause",
    resume: "Resume",
    stop: "Stop",
    send: "Send",
  },
  livestream: {
    hello: "Hello!",
    inputTitle: "Input title for livestream",
  },
  purchase: {
    headerBookLesson: "Book lesson",
    headerChooseClass: "Choose a class",

    timeDuration: "Time per course",
    chooseDay: "Choose the day of week",
    chooseDayDes: "You can only choose up to 4 option for class",
    timeNote: "In your time zone, Asia/Ho Chi Minh (GMT +7:00)",
    morning: "Morning",
    Afternoon: "Afternoon",
    Night: "Night",
    hoursNote: "You can only choose up to 2 options fo class hours",
    orderNow: "Order Now!",
    participants: "Participants",
    startDate: "Start date",
    endDate: "End date",
  },
  payment: {
    paymentmethod: "Payment method",
    paymentdetail: "Payment Detail",
    totalpayment: "Total Payment",
    vnpay: "VNPay",
    smartbanking: "Smart Banking",
    formforLearning: "Form for learning",
    class: "Class",
    days: "Days",
    learningtime: "Learning Time",
    promo: "Promo",
    errorpaymentmethod: "You haven’t chosen the payment method",
    couresfree: "Course free",
    coursePrice: "Course price",
    completecheckout: "Complete Checkout",
    promotion: "Promotion",
    notePurchase:
      "The transaction will take a few minutes to complete, when successful we will notify you",
    paymentsuccess: "Payment Success",
    completepayment:
      "When you have completed your payment. You just need to click the button below to enjoy the course.",
    gomylearning: "Go to my learning",
    uploadfile: "Upload file",
    send: "Send",
    sendPro: "Send provemment",
    saveQRCode: "Save QR code",
    tocomplete:
      "To complete the payment process, please make a transfer to the account number below:",
    content: "Content tranfer",
    courseNotAvailable: "Course not available",
  },
  settingUser: {
    language: "Language",
    hightandweigh: "Height/Weight",
    space: "Space",
    deletecache: "Delete memory",
    noti: "Notification",
    hidden: "Hidden me from WhiteG",
    block: "Block message from strangers",
    blackList: "List Black",
    setting: "Setting",
    private: "Security & privacy",
    support: "Customer support",
    aboutus: "About us",
    mycouse: "My Course",
    purchaseCouse: "Purchased course",
    discount: "Discount",
    codeActivations: "Code activations",
    becomeATutor: "Become a tutor",
  },
  aboutUs: {
    aboutUs: "About us",
    termofus: "Term of us",
    privacy: "Privacy Policy",
    cookie: "Cookie policy",
    return: "Return policy",
    deleteacount: "Detete Account",
  },
  call: {
    inComingCall: "Incoming Call...",
    titleCamera: "Need permission to access camera",
    messageCamera: "To call others, we need permission to access your camera.",
    titleMic: "Need permission to access microphone",
    messageMic: "To call others, we need permission to access your microphone.",
  },
  listCategory: {
    course: "Course",
    tutor: "Tutor",
    shop: "Shop",
    affiliate: "Affiliate",
    descriptionTitle: "What should we today?",
  },
  recommendCourse: "Recommend course",
  ieltsHunterLive: "IELTS Hunter Live",
  nameTutor: (name: string) => `${name}'s course`,
  titleLive: "Nguyen Trung Kien's IELTS Writing class",
  titleName: "IELTS Listening [MASTERCLASS]: Get Band 7+ in 2024",
  best: "Best-seller",
  ratings: "2.3K ratings",
  buy: "Buy",
  pin: "Pin",
  unPin: "Unpin",
  priceNew: "1,500,000đ",
  priceOld: "5,000,000đ",
  selectCategory: "Select category",
  selectImage1: "Photo",
  selectVideo: "Video",
  selectLive: "Live video",
  selectFile: "Upload file",
  en: "English",
  vi: "Vietnamese",
  leaderBoard: "Leader Board",
  inprogress: "Inprogress",
  complete: "Complete",
  signOut: "Sign Out",
  gotIt: "Got it",
  task: {
    inviteFriend: "Invite a friend",
    yourscore: "Your IELTS Score",
    powered: "POWERED BY",
    mycode: "My Code",
    level: "Level",
    task: "Tasks",
    score: "Score",
    listening: "Listening",
    speaking: "Speaking",
    reading: "Reading",
    writing: "Writing",
    missions: "Missions",
    get: "Get",
  },
  homework: {
    header: "Task list",
    assignment: "Assignment",
    assign: "Assign",
    addClassCmt: "Add class comment",
    detailTask: "Detail task",
    classCmt: "Class Comment",
    yourWork: "Your work",
    addWork: "Add work",
    handedIn: "Handed in",
    unsubmit: "Unsubmit",
    unsubmitDes:
      "Unsubmit to add or change attachments. Don’t forget to resubmit once you’ve finished.",
    removeAtt: "Remove attachment?",
    removeAttDes: "Are you sure to remove your attachment?",
    handInYourWork: "Hand in your work?",
    handInYourWorkDes: (text) => text + "attachment will be submitted?",
    privateCmt: "Private Comment",
    privateCmtDes: "Add private comment to",
    intructions: "Intructions",
    studentWork: "Student work",
    assigned: "Assigned",
    mark: "Input mark",
    marked: "Marked",
    acceptSub: "Accepting submissions",
    assignTitle: "Assign title",
    description: "Description",
    attachment: "Attachment",
    score: "Score",
    points: "points",
    dueDate: "Due date",
    topic: "Topic",
    createWork: "Create work",
    selectClass: "Select class",
    selectDouDate: "Select due date",
    createTaskSuccess: "Create homework success",
    deleteTaskSuccess: "Delete homework success",
    updateTaskSuccess: "Update homework success",
    handedInSuccess: "Handed in success",
    markError: "Scores must be numeric and less than 100",
    forYou: "For you",
    following: "Following",
  },
  introwelcome: {
    text11: "Welcome to the world of language",
    text12:
      "Ready to embark on this enriching adventure? Let's start your learning odyssey now!",
    text21: "Join our vibrant IELTS community",
    text22:
      "A space to connect with fellow learners, share insights, and boost your preparation journey together!",
    text31: "Diverse Learning Forms",
    text32:
      "Choose your learning adventure: dive into self-paced video modules, receive personalized guidance in 1v1 sessions, and foster group collaboration.",
  },
  discover: {
    study: "Study",
    dictionary: "Dictionary",
    shop: "Shop",
    finduser: "Find user",
    findTutor: "Find tutor",
    coins: "Coins",
    level: "Level",
    leaderboard: "Leader Board",
    poits: "Points",
    feature: "Features",
    ieltsPractice: "Ielts practice test",
  },
  gamificaiton: {
    youEarn: "You earned ",
    collectPoint: "Collect point",
    levelUp: "Level up!",
    levelUpDes:
      "Earn more point and grow your level by doing tasks and improving your skill.",
  },
  affiliate: {
    yourIncome: "Your Income",
    withdraw: "Withdraw",
    today: "To day",
    thisMonth: "This month",
    lastMonth: "Last month",
    date: "Date",
    product: "Product",
    user: "User",
    customer: "Customer",
    emptyTransaction: "Empty transaction",
    fromDate: "From date",
    toDate: "To date",
    commission: "Commission",
    noTransaction: "No transaction has occurred",
  },
  withDraw: {
    header: "Withdraw",
    your_money: "Your money",
    withdraw_amount: "Withdraw amount",
    min_withdraw_des: "Minimum amount for withdrawal is 100.000đ",
    bank_des: "Unlimited time for free cashout",
    add_bank: "Add bank",
    bank_title: "Bank Account",
    card_number: "Card/Account number",
    card_number_placeholder: "Enter Card/Account number",
    card_name: "Card/Account holder name",
    card_number_error: "Please input your bank account number (4 to 14 digits)",
    search_bank: "Search bank",
    choose_bank: "Choose bank",
    bank_acc: "Bank account",
    addBankSuccess: "Add card success",
    addBankFaild: "Adding a new bank card failed",
    withDrawSuccess: "Placed withdrawal order to account successfully",
    withDrawFaild: "Withdrawal order failed",
  },
  referrals: {
    yourReferral: "Your referral",
    viewProfile: "View profile",
  },
  ieltsPractice: {
    praticeTest: "Practice test",
    writing: "Writing",
    listening: "Listening",
    reading: "Reading",
    speaking: "Speaking",
    answers: "Answers",
    questions: "Questions",
    submitSucces: "Submit success",
    timeout: "Timeout",
    submit: "Submit",
    hidePassage: "Hide passage",
    showPassage: "Show passage",
    waittingResult: "Waitting result",
  },
};
/* eslint-disable max-len */
