/* eslint-disable max-len */
export default {
  // --- Common & Auth ---
  detail: "Detail",
  setting: "Setting",
  openSetting: "Open setting",
  language: "Language",
  darkMode: "Dark mode",
  switchLanguage: "Switch language",
  approve: "Approve",
  cancel: "Cancel",
  placeholderEmaiPhone: "Email/Phone number",
  placeholderEmail: "Email",
  placeholderVerifyCode: "Verify code",
  placeholderPasword: "Password",
  placeholderRePasword: "Repeat password",
  forgotPassword: "Forgot password",
  verifyCodeTitle: (text) => `Input verify code from email ${text}`,
  signIn: "Sign in",
  signUp: "Sign up",
  signInWith: "Sign in with",
  continue: "Continue",
  continueWith: (text) => `Continue with ${text}`,
  enterNewPassword: "Enter new password",
  confirmPassword: "Confirm password",
  enterOTP: "Enter OTP",
  updatePassword: "Update password",
  save: "Save",
  required: "required",
  invalid: "Invalid",
  or: "Or",
  hi: "Hi",
  welcomeBack: "Kickstart your healthy journey today!",
  minLength: (number) => `at least ${number} characters`,
  needAnAccount: "Need an account? ",
  registerNow: "Register now!",
  createNewAccount: "Create new account!",
  fullname: "Fullname",
  haveAnAccount: "Have an account? ",
  loginNow: "Login now!",
  welcomeHeader: "Welcome to CaloSnap",
  welcomeDescription: "Tracking calories has never been easier! With CaloSnap you will...",
  startNow: "Start Now",
  sendingError: "An error occurred!",
  createPassSuccess: "Create new password success!",
  loginSuccess: "Login success!",
  goBackHome: "Go back home",
  next: "Next",
  other: "Other",
  keepGoing: "Keep going",
  changeLanguage: "Choose the language",
  
  // --- Tabs ---
  homes: "Home",
  chats: "Chat",
  discovers: "Discover",
  profile: "Profile",
  statistics: {
    title: "Statistics",
    overview: "Overview",
    comingSoon: "Feature coming soon",
  },
  health: {
    title: "Health",
    overview: "Overview",
    comingSoon: "Feature coming soon",
  },

  // --- Errors ---
  error: {
    unknown: "Unknown error!",
    invalidPhoneEmail: "Phone/Email invalid",
    invalidEmail: "Email invalid",
    invalidPhone: "Phone invalid",
    invalidLink: "Link invalid",
    passDoesNotMatch: "Confirmation password does not match",
    minLengthPass: "Password must be at least 6 characters",
    isOffline: "Connect to internet and retry!",
  },

  // --- Actions ---
  reset: "Reset",
  apply: "Apply",
  blackList: {
    unblock: "Unblock",
    unBlockSuccess: "Unblock success!",
    warningUnblock: (name) => `You want to unblock ${name}?`,
  },
  you: "You",
  permissions: {
    titleCamera: "Need permission to access camera",
    messageCamera: "We need permission to access your camera to snap food photos",
    denied: "Permission denied. Please enable in settings.",
    negative: "Cancel",
    positive: "Ok",
  },

  // --- Social & Chat ---
  postCategory: "Select category",
  createPost: "Create post",
  placeholderContent: "What’s on your mind?",
  confirm: "Confirm",
  somethingWentWrong: "Something went wrong. Please try again.",
  notFound: "Empty List",
  offlineNetwork: "You are currently offline",
  onlineNetwork: "Your internet connection was restored",
  all: "All",
  seconds: "seconds",
  minutes: "minutes",
  hours: "hours",
  days: "days",
  weeks: "weeks",
  months: "months",
  schedule: "Schedule",
  years: "years",
  ago: "ago on",
  copied: "Copied",
  copy: "Copy",
  report: "Report",
  block: "Block",
  unBlockUser: "Unblock",
  commentAs: "Comment as",
  replying: "Replying",
  reply: "reply",
  like: "like",
  comment: "comment",
  delete: "Delete",
  edit: "Edit",
  copyLink: "Copy link",
  deleteSuccess: "Successfully deleted",
  updateSuccess: "Successfully updated",
  online: "Online now",
  offline: "Offline",
  status: "Status",
  joined: "Joined",
  bio: "Bio",
  follower: "Follower",
  following: "Following",
  follow: "Follow",
  unfollow: "Unfollow",
  followed: "Followed",
  message: "Message",
  filter: "Filter",
  sort: "Sort",
  search: "Search...",
  update: "Update",
  viewAll: "View All",
  aboutMe: "About me",
  today: "Today",
  yesterday: "Yesterday",
  tomorrow: "Tomorrow",
  from: "From",
  to: "To",
  selectImage: "Select Image",
  public: "Public",
  post: {
    likes: (count) => `${count} like${count > 1 ? "s" : ""}`,
    post: "Post",
    posts: "Post",
    createPost: "Create Post",
    category: "Category",
    title: "Title",
    content: "Content",
    createPostSuccess: "Create post successfully",
    like: "Like",
    liked: "Liked",
    share: "Share",
    comment: "Comment",
    comments: "comments",
    emptyComment: "No comments yet",
    emptyPost: "There are no posts yet",
    emptyPostDes: "Share your healthy journey with friends!",
    report: "Report this post",
    save: "Save post",
    savePostSuccess: "Save post success",
    uploadImageFaild: "Image upload failed. Please try again!",
  },
  
  // --- Chat ---
  chat: {
    search: "Search",
    sendMessage: "Send message",
    cancel: "cancel",
    typeMessage: "Type a message...",
    lastSeen: "Last seen: ",
    addMember: "Add member",
    createGroupSuccess: "Create group chat successfully",
    selectGroup: "Select group",
    selectMember: "Select member",
    mediaFile: "Media, files",
    createGroup: (txt) => `Create group with ${txt}`,
    sendFiles: "Send Photo, files, links",
    blockUser: "Block user",
    report: "Report",
    leave: "Leave group",
    renameGroup: "Rename group",
    enterGroupName: "Enter group name",
  },

  // --- Home / Dashboard (Calorie App Core) ---
  home: {
    whatonYourMind: "What's on your mind",
    recentActivity: "Recent activity",
    macros: {
      CARBS: "Carbohydrates",
      PROTEIN: "Protein",
      FAT: "Fat",
    },
    week: {
      dayShort: "T__INDEX__",
      sunShort: "Sun",
    },
    daily: {
      intake: "Intake",
      burn: "Burn",
      valuePrefix: "",
    },
    emptyMealsTitle: "No meals yet!",
    emptyMealsSub: "Tap + to add your first meal of the day.",
    greeting: "Today",
    dashboard: {
      caloriesLabel: "Calories Goal",
      stepsLabel: "Steps Goal",
      waterLabel: "Water Goal",
      consumedLabel: "Consumed",
      burnedLabel: "Burned",
      unitCalories: "kcal",
      unitSteps: "steps",
      unitWater: "ml",
    },
    banner: {
      title: "AI Calorie Counter",
      download: "Download",
      premiumPrefix: "Ad-free.",
      premiumCta: "Upgrade to Premium",
    },
  },

  // --- Calorie Scanner / Result ---
  scanner: {
    title: "CaloSnap",
    analysisSuccess: "Analysis successful!",
    saveSuccess: "Meal saved!",
    saveError: "Failed to save data.",
    deleteIngredientTitle: "Remove ingredient",
    deleteIngredientMessage: "Are you sure you want to remove it?",
    cancel: "Cancel",
    delete: "Delete",
    cameraPermissionTitle: "Camera permission required",
    cameraPermissionMessage: "Please grant camera permission...",
    openSettings: "Settings",
    health: "Health",
    nutritionTitle: "Calories & Nutrition",
    quantity: "Quantity",
    calories: "Calories",
    carbs: "Carbs",
    protein: "Protein",
    fat: "Fat",
    ingredients: "Ingredients",
    addIngredient: "Add new ingredient",
    tweakHint: 'Want to refine your result? Tap "Edit result" and tell us!',
    editResult: "Edit result",
    save: "Save",
    mealDetail: "Meal details",
    result: "Result",
  },

  // --- Login / Auth ---
  login: {
    requireLogin: "Please log in to continue",
    continueFacebook: "Continue with Facebook",
    continueGoogle: "Continue with Google",
    continueApple: "Continue with Apple",
    email: "Email",
    emailPhone: "Email / Phone number",
    password: "Password",
    signin: "Sign in",
    signup: "Sign up",
    dontHaveAccount: "Don't have an account?",
    or: "Or",
    termConditions: "Terms & Conditions",
    privacyPolicy: "Privacy Policy",
    alreadyHaveAccount: "Already have an account?",
    createYourAccount: "Create your account",
    loginError: "Have an Error while Login, please try again!",
    registerSuccess: "Successfully registered",
    forgotPassword: "Forgot Password",
    send: "Send",
    forgotPasswordSuccess: "Successfully sent an email, please check your email!",
  },

  // --- Validations ---
  validate: {
    emailInvalid: "Email is invalid",
    requiredEmail: "Email is required",
    requiredPassword: "Password is required",
    requiredFullName: "Fullname is required",
    errorConfirmPasswordNotMatch: "Password doesn't match",
    requiredDate: "Date is required",
    requiredTime: "Time is required",
  },

  // --- Setting User & Profile ---
  settingUser: {
    language: "Language",
    hightandweigh: "Height/Weight",
    space: "Space",
    deletecache: "Delete memory",
    noti: "Notification",
    blackList: "Blocked List",
    setting: "Setting",
    private: "Security & privacy",
    support: "Customer support",
    aboutus: "About us",
  },
  
  aboutUs: {
    aboutUs: "About us",
    termofus: "Term and conditions",
    privacy: "Privacy Policy",
    deleteacount: "Delete Account",
  },

  // --- Profile Screen specific (CaloSnap style) ---
  profile: {
    title: "Profile",
    editProfile: "Edit Profile",
    saveProfile: "Save profile",
    account: "Account",
    notifications: "Notifications",
    bio: "Bio",
    addBio: "Add bio",
    
    // Groups in Setting Profile
    goals: "Goals",
    customization: "Customization",
    other: "Other",
    followUs: "Follow CaloSnap",
    
    // Goal Items
    weight: "Weight",
    calories: "Calories",
    nutrition: "Nutrition",
    diet: "Diet",
    steps: "Steps",
    water: "Water",
    
    // Customization Items
    restart: "Restart",
    reminders: "Reminders",
    darkMode: "Dark Mode",
    language: "Language",
    addBurnedCalories: "Add burned calories",
    metricSystem: "Metric system",
    
    // Other Items
    rateApp: "Rate CaloSnap",
    freeQuota: "Free quota",
    support: "Support",
    privacyPolicy: "Privacy Policy",
    termsOfUse: "Terms of Use",
    medicalSources: "Medical sources",
    deleteAccount: "Delete account",
    
    // Social & Account
    login: "Login",
    id: "ID",
    tiktok: "TikTok",
    facebook: "Facebook",
    
    // Descriptions
    addBurnedCaloriesDesc: "Increase daily calorie limit based on activity",
    metricSystemDesc: "Turn off to use Imperial measurement system",
    deleteAccountDesc: "Delete all data and reset",
    
    // Pro Banner
    proBannerTitle: "CaloSnap",
    proBadge: "PRO",
    proDescription: "Experience uninterrupted smart AI - Quickly achieve your goals.",
    proButton: "Try free",
    
    // Footer
    footerVersion: "CaloSnap 1.6.18+63",
    footerCopyright: "© 2025 CaloSnap. All rights reserved.",
    
    // Goal Details
    weightGoalTitle: "Weight Goal",
    caloriesGoalTitle: "Calories Goal",
    dietGoalTitle: "Diet",
    stepsGoalTitle: "Steps Goal",
    waterGoalTitle: "Water Goal",
    stepsUnit: "steps / day",
    waterUnit: "ml",
    chooseLanguageSubtitle: "Select the language you want to use",
  },

  // --- Diet Types ---
  dietTypes: {
    BALANCED: "Balanced",
    LOW_CARB: "Low Carb",
    LOW_FAT: "Low Fat",
    HIGH_PROTEIN: "High Protein",
    KETO: "Keto",
    VEGETARIAN: "Vegetarian",
  },

  // --- Premium / Payment ---
  premiumAccount: {
    freeTrial: "Free 3 days trial",
    day: "Day",
    month: "Month",
    year: "Year",
    save: "Save",
    getIt: "Go to Premium",
    noThanks: "No, thank you",
    whiteGPro: "Premium",
    proDes: "Upgrade to Premium for advanced AI analysis and unlimited tracking!",
    getPro: "Get Premium",
    upgrade: "Upgrade",
    restore: "Restore purchase",
  },
  
  payment: {
    paymentmethod: "Payment method",
    totalpayment: "Total Payment",
    paymentsuccess: "Payment Success",
  },

  // --- Affiliate (Nếu giữ lại tính năng bán TPCN/Gói tập) ---
  affiliate: {
    yourIncome: "Your Income",
    withdraw: "Withdraw",
    product: "Product",
    customer: "Customer",
    commission: "Commission",
    revenua: "Revenue",
  },

  // --- Notifications ---
  notifications: {
    notifications: "Notifications",
    markAll: "Mark all as read",
    emptyNotification: "There are currently no notifications",
  },
  
  // --- Common units/time ---
  common: {
    seconds: "seconds",
    minutes: "minutes",
    hours: "hours",
    days: "days",
  },

  // --- Empty States ---
  emptyList: "Empty list",
  noResult: "No result found!",
  
  // --- Buttons ---
  close: "Close",
  done: "Done",
  seeAll: "See all",
};
/* eslint-disable max-len */