/* eslint-disable max-len */
export default {
  // --- Common & Auth ---
  detail: "詳細",
  setting: "設定",
  openSetting: "設定を開く",
  language: "言語",
  darkMode: "ダークモード",
  switchLanguage: "言語を切替",
  approve: "承認",
  cancel: "キャンセル",
  placeholderEmaiPhone: "メールアドレス / 電話番号",
  placeholderEmail: "メールアドレス",
  placeholderVerifyCode: "認証コード",
  placeholderPasword: "パスワード",
  placeholderRePasword: "パスワード（確認用）",
  forgotPassword: "パスワードをお忘れですか？",
  verifyCodeTitle: (text) => `メールアドレス ${text} に送信された認証コードを入力してください`,
  signIn: "ログイン",
  signUp: "新規登録",
  signInWith: "でログイン",
  continue: "次へ",
  continueWith: (text) => `${text} で続ける`,
  enterNewPassword: "新しいパスワードを入力",
  confirmPassword: "パスワードを確認",
  enterOTP: "OTPを入力",
  updatePassword: "パスワードを更新",
  save: "保存",
  required: "必須",
  invalid: "無効です",
  or: "または",
  hi: "こんにちは",
  welcomeBack: "今日も健康的な一日を始めましょう！",
  minLength: (number) => `少なくとも ${number} 文字以上`,
  needAnAccount: "アカウントをお持ちではありませんか？ ",
  registerNow: "今すぐ登録！",
  createNewAccount: "新しいアカウントを作成",
  fullname: "氏名",
  haveAnAccount: "すでにアカウントをお持ちですか？ ",
  loginNow: "ログイン",
  welcomeHeader: "CaloSnapへようこそ",
  welcomeDescription: "カロリー管理がこれまでになく簡単になりました！CaloSnapを使えば...",
  startNow: "今すぐ始める",
  sendingError: "エラーが発生しました！",
  createPassSuccess: "新しいパスワードを作成しました！",
  loginSuccess: "ログイン成功！",
  goBackHome: "ホームに戻る",
  next: "次へ",
  other: "その他",
  keepGoing: "その調子！",
  changeLanguage: "言語を選択",

  // --- Tabs ---
  homes: "ホーム",
  chats: "チャット",
  discovers: "発見",
  profile: "プロフィール",
  statistics: {
    title: "統計",
    overview: "概要",
    comingSoon: "近日公開予定",
  },
  health: {
    title: "ヘルスケア",
    overview: "概要",
    comingSoon: "近日公開予定",
  },

  // --- BMI (by type) ---
  bmi: {
    UNDERWEIGHT: "低体重",
    NORMAL: "普通",
    OVERWEIGHT: "肥満気味",
    OBESE: "肥満",
    estimateLabel: "推定BMI",
    waitingHeight: "身長データを待っています...",
  },

  // --- Onboarding ---
  onboarding: {
    heightTitle: "身長は何cmですか？",
    currentWeightTitle: "現在の体重は何kgですか？",
    targetWeightTitle: "目標体重は何kgですか？",
    ageTitle: "おいくつですか？",
    changeAnytimeHint: "ご安心ください。いつでも変更できます",
    genderTitle: "性別",
    genderSubtitle: "性別を選択してください",
    genderMale: "男性",
    genderFemale: "女性",
    continue: "続ける",
    paceTitle: "変化のペース",
    paceSubtitle: "どのペースで目標に近づきたいですか？",
    paceSlowLabel: "ゆっくり",
    paceSlowDesc: "0.25 kg/週 - 安全で持続可能",
    paceNormalLabel: "普通",
    paceNormalDesc: "0.5 kg/週 - バランス型",
    paceFastLabel: "速い",
    paceFastDesc: "1 kg/週 - 継続が大切",
    viewResult: "結果を見る",
  },

  // --- Plan Result (onboarding summary) ---
  planResult: {
    title: "あなたのヘルスプランができました！",
    subtitle: "ご入力いただいた情報をもとに、栄養プランをご提案します",
    yourInfo: "あなたの情報",
    gender: "性別:",
    age: "年齢:",
    ageUnit: "歳",
    height: "身長:",
    activityLevel: "活動レベル:",
    paceChange: "変化のペース:",
    nowLabel: "現在",
    goal: "目標",
    maintainWeight: "維持",
    targetCalTitle: "目標カロリー摂取量",
    caloGainingDesc: "🔥🔥🔥 増量のためカロリーを推定...",
    caloLosingDesc: "🔥🔥🔥 減量のためカロリーを推定...",
    caloPerDay: "cal/日",
    caloPerWeek: "cal/週",
    includesLabel: "内訳:",
    tdeeLabel: "1日に必要なTDEE",
    caloUnit: "cal",
    caloSurplus: "カロリー黒字",
    caloDeficit: "カロリー赤字",
    fromDietAndExercise: "食事と運動から",
    expectedTargetDesc: "上記に基づき、目標達成予定",
    kgOn: "Kg（",
    macroTitle: "推奨栄養バランス",
    balancedDietPrefix: "バランスの取れた",
    balancedDiet: "食事をおすすめします",
    genderLabels: {
      MALE: "男性",
      FEMALE: "女性",
    },
    activityLabels: {
      SEDENTARY: "ほとんど運動しない",
      LIGHTLY_ACTIVE: "軽い運動",
      MODERATELY_ACTIVE: "適度な運動",
      VERY_ACTIVE: "活発に運動",
    },
    paceLabels: {
      SLOW: "ゆっくり（0.25 kg/週）",
      NORMAL: "普通（0.5 kg/週）",
      FAST: "速い（1 kg/週）",
    },
    currentWeight: "現在の体重",
    targetWeight: "目標体重",
    gaining: "増量",
    losing: "減量",
    expectedBy: "達成予定",
    dailyCalories: "1日のカロリー",
    kcalPerDay: "kcal/日",
    macroSplit: "マクロ配分",
    carb: "炭水化物",
    protein: "タンパク質",
    fat: "脂質",
    note: "💡 注意: Mifflin-St Jeor式に基づく参考プランです。体質や運動量により結果は異なります。",
    start: "始める",
    restart: "最初からやり直す",
  },

  // --- Errors ---
  error: {
    unknown: "不明なエラーです！",
    invalidPhoneEmail: "電話番号またはメールアドレスが無効です",
    invalidEmail: "メールアドレスが無効です",
    invalidPhone: "電話番号が無効です",
    invalidLink: "リンクが無効です",
    passDoesNotMatch: "確認用パスワードが一致しません",
    minLengthPass: "パスワードは6文字以上である必要があります",
    isOffline: "インターネットに接続して再試行してください！",
  },

  // --- Actions ---
  reset: "リセット",
  apply: "適用",
  blackList: {
    unblock: "ブロック解除",
    unBlockSuccess: "ブロックを解除しました！",
    warningUnblock: (name) => `${name} のブロックを解除しますか？`,
  },
  you: "あなた",
  permissions: {
    titleCamera: "カメラへのアクセス権限が必要です",
    messageCamera: "食事の写真を撮るためにカメラへのアクセスが必要です",
    denied: "権限が拒否されました。設定から有効にしてください。",
    negative: "キャンセル",
    positive: "OK",
  },

  // --- Social & Chat ---
  postCategory: "カテゴリを選択",
  createPost: "投稿を作成",
  placeholderContent: "今なにしてる？",
  confirm: "確認",
  somethingWentWrong: "問題が発生しました。もう一度お試しください。",
  notFound: "リストは空です",
  offlineNetwork: "現在オフラインです",
  onlineNetwork: "インターネット接続が復旧しました",
  all: "すべて",
  seconds: "秒",
  minutes: "分",
  hours: "時間",
  days: "日",
  weeks: "週間",
  months: "ヶ月",
  schedule: "スケジュール",
  years: "年",
  ago: "前",
  copied: "コピーしました",
  copy: "コピー",
  report: "通報",
  block: "ブロック",
  unBlockUser: "ブロック解除",
  commentAs: "コメントする：",
  replying: "返信中",
  reply: "返信",
  like: "いいね",
  comment: "コメント",
  delete: "削除",
  edit: "編集",
  copyLink: "リンクをコピー",
  deleteSuccess: "削除しました",
  updateSuccess: "更新しました",
  online: "オンライン",
  offline: "オフライン",
  status: "ステータス",
  joined: "参加済み",
  bio: "自己紹介",
  follower: "フォロワー",
  following: "フォロー中",
  follow: "フォロー",
  unfollow: "フォロー解除",
  followed: "フォローされています",
  message: "メッセージ",
  filter: "フィルター",
  sort: "並び替え",
  search: "検索...",
  update: "更新",
  viewAll: "すべて見る",
  aboutMe: "自己紹介",
  today: "今日",
  yesterday: "昨日",
  tomorrow: "明日",
  from: "自",
  to: "至",
  selectImage: "画像を選択",
  public: "公開",
  post: {
    likes: (count) => `${count} いいね`,
    post: "投稿",
    posts: "投稿",
    createPost: "投稿を作成",
    category: "カテゴリ",
    title: "タイトル",
    content: "内容",
    createPostSuccess: "投稿を作成しました",
    like: "いいね",
    liked: "いいね済み",
    share: "シェア",
    comment: "コメント",
    comments: "コメント",
    emptyComment: "まだコメントはありません",
    emptyPost: "まだ投稿はありません",
    emptyPostDes: "健康への道のりを友達とシェアしましょう！",
    report: "この投稿を通報",
    save: "投稿を保存",
    savePostSuccess: "投稿を保存しました",
    uploadImageFaild: "画像のアップロードに失敗しました。再試行してください！",
  },
  
  // --- Chat ---
  chat: {
    search: "検索",
    sendMessage: "メッセージを送信",
    cancel: "キャンセル",
    typeMessage: "メッセージを入力...",
    lastSeen: "最終オンライン： ",
    addMember: "メンバーを追加",
    createGroupSuccess: "グループチャットを作成しました",
    selectGroup: "グループを選択",
    selectMember: "メンバーを選択",
    mediaFile: "メディア、ファイル",
    createGroup: (txt) => `${txt} とグループを作成`,
    sendFiles: "写真、ファイル、リンクを送信",
    blockUser: "ユーザーをブロック",
    report: "通報",
    leave: "グループから退出",
    renameGroup: "グループ名を変更",
    enterGroupName: "グループ名を入力",
  },

  // --- Home / Dashboard (Calorie App Core) ---
  home: {
    whatonYourMind: "何を考えていますか？",
    recentActivity: "最近のアクティビティ",
    macros: {
      CARBS: "炭水化物",
      PROTEIN: "タンパク質",
      FAT: "脂質",
    },
    week: {
      dayShort: "T__INDEX__", // Keep logic or change to 月, 火, 水... if handled in code
      sunShort: "日",
    },
    daily: {
      intake: "摂取",
      burn: "消費",
      valuePrefix: "",
    },
    emptyMealsTitle: "食事が記録されていません",
    emptyMealsSub: "＋ボタンをタップして、今日の最初の食事を追加しましょう。",
    greeting: "今日",
    dashboard: {
      caloriesLabel: "目標カロリー",
      stepsLabel: "目標歩数",
      waterLabel: "目標水分",
      consumedLabel: "摂取済み",
      burnedLabel: "消費済み",
      unitCalories: "kcal",
      unitSteps: "歩",
      unitWater: "ml",
    },
    banner: {
      title: "AIカロリーカウンター",
      download: "ダウンロード",
      premiumPrefix: "広告なし。",
      premiumCta: "プレミアムへアップグレード",
    },
  },

  // --- Calorie Scanner / Result ---
  scanner: {
    processingText: "結果を準備しています",
    successText: "もうすぐです！",
    bottomNote: "アプリを閉じたり、デバイスをロックしないでください",
    modeVoice: "音声",
    modeImage: "画像",
    modeManual: "手動",
    title: "CaloSnap",
    analysisSuccess: "解析に成功しました！",
    saveSuccess: "食事を保存しました！",
    saveError: "データの保存に失敗しました。",
    deleteIngredientTitle: "材料を削除",
    deleteIngredientMessage: "削除してもよろしいですか？",
    cancel: "キャンセル",
    delete: "削除",
    cameraPermissionTitle: "カメラ権限が必要です",
    cameraPermissionMessage: "カメラの権限を許可してください…",
    openSettings: "設定",
    health: "健康",
    nutritionTitle: "カロリー＆栄養",
    quantity: "量",
    calories: "カロリー",
    carbs: "炭水化物",
    protein: "タンパク質",
    fat: "脂質",
    ingredients: "材料",
    addIngredient: "材料を追加",
    tweakHint: '結果を調整しますか？「結果を編集」をタップして教えてください！',
    editResult: "結果を編集",
    save: "保存",
    mealDetail: "食事の詳細",
    result: "結果",
  },

  // --- Intro (first-time welcome) ---
  intro: {
    title: "カロリー管理を\nもっと簡単に",
    getStarted: "始める",
    alreadyHaveAccount: "すでにアカウントをお持ちですか？ ",
    signIn: "ログイン",
  },

  // --- Login / Auth ---
  login: {
    requireLogin: "続行するにはログインしてください",
    continueFacebook: "Facebookで続ける",
    continueGoogle: "Googleで続ける",
    continueApple: "Appleで続ける",
    email: "メールアドレス",
    emailPhone: "メールアドレス / 電話番号",
    password: "パスワード",
    signin: "ログイン",
    signup: "新規登録",
    dontHaveAccount: "アカウントをお持ちではありませんか？",
    or: "または",
    termConditions: "利用規約",
    privacyPolicy: "プライバシーポリシー",
    alreadyHaveAccount: "すでにアカウントをお持ちですか？",
    createYourAccount: "アカウントを作成",
    loginError: "ログイン中にエラーが発生しました。再試行してください！",
    registerSuccess: "登録が完了しました",
    forgotPassword: "パスワードをお忘れですか",
    send: "送信",
    forgotPasswordSuccess: "メールを送信しました。受信トレイを確認してください！",
  },

  // --- Validations ---
  validate: {
    emailInvalid: "メールアドレスが無効です",
    requiredEmail: "メールアドレスは必須です",
    requiredPassword: "パスワードは必須です",
    requiredFullName: "氏名は必須です",
    errorConfirmPasswordNotMatch: "パスワードが一致しません",
    requiredDate: "日付は必須です",
    requiredTime: "時間は必須です",
  },

  // --- Setting User & Profile ---
  settingUser: {
    language: "言語",
    hightandweigh: "身長 / 体重",
    space: "スペース",
    deletecache: "キャッシュを削除",
    noti: "通知",
    blackList: "ブロックリスト",
    setting: "設定",
    private: "セキュリティとプライバシー",
    support: "カスタマーサポート",
    aboutus: "私たちについて",
  },
  
  aboutUs: {
    aboutUs: "私たちについて",
    termofus: "利用規約",
    privacy: "プライバシーポリシー",
    deleteacount: "アカウント削除",
  },

  // --- Profile Screen specific (CaloSnap style) ---
  profile: {
    title: "プロフィール",
    editProfile: "プロフィール編集",
    saveProfile: "プロフィール保存",
    account: "アカウント",
    notifications: "通知",
    bio: "自己紹介",
    addBio: "自己紹介を追加",
    
    // Groups in Setting Profile
    goals: "目標",
    customization: "カスタマイズ",
    other: "その他",
    followUs: "CaloSnapをフォロー",
    
    // Goal Items
    weight: "体重",
    calories: "カロリー",
    nutrition: "栄養",
    diet: "食事プラン",
    steps: "歩数",
    water: "水分",
    
    // Customization Items
    restart: "最初からやり直す",
    reminders: "リマインダー",
    darkMode: "ダークモード",
    language: "言語",
    addBurnedCalories: "消費カロリーを目標に加算",
    metricSystem: "メートル法",
    
    // Other Items
    rateApp: "CaloSnapを評価",
    freeQuota: "無料枠",
    support: "サポート",
    privacyPolicy: "プライバシーポリシー",
    termsOfUse: "利用規約",
    medicalSources: "医療情報源",
    deleteAccount: "アカウント削除",
    
    // Social & Account
    login: "ログイン",
    id: "ID",
    tiktok: "TikTok",
    facebook: "Facebook",
    
    // Descriptions
    addBurnedCaloriesDesc: "活動量に基づいて1日のカロリー制限を増やします",
    metricSystemDesc: "オフにするとヤード・ポンド法を使用します",
    deleteAccountDesc: "すべてのデータを削除してリセットします",
    
    // Pro Banner
    proBannerTitle: "CaloSnap",
    proBadge: "PRO",
    proDescription: "スマートAIを中断なく体験 - 目標を素早く達成しましょう。",
    proButton: "無料で試す",
    
    // Footer
    footerVersion: "CaloSnap 1.6.18+63",
    footerCopyright: "© 2025 CaloSnap. All rights reserved.",
    
    // Goal Details
    weightGoalTitle: "目標体重",
    caloriesGoalTitle: "目標カロリー",
    dietGoalTitle: "食事プラン",
    stepsGoalTitle: "目標歩数",
    waterGoalTitle: "目標水分",
    stepsUnit: "歩 / 日",
    waterUnit: "ml",
    chooseLanguageSubtitle: "使用する言語を選択してください",
  },

  // --- Diet Types ---
  dietTypes: {
    BALANCED: "バランス",
    LOW_CARB: "低炭水化物",
    LOW_FAT: "低脂質",
    HIGH_PROTEIN: "高タンパク",
    KETO: "ケトジェニック",
    VEGETARIAN: "ベジタリアン",
  },

  // --- Premium / Payment ---
  premiumAccount: {
    freeTrial: "3日間無料体験",
    day: "日",
    month: "ヶ月",
    year: "年",
    save: "保存",
    getIt: "プレミアムへ",
    noThanks: "結構です",
    whiteGPro: "プレミアム",
    proDes: "高度なAI分析と無制限のトラッキングのためにプレミアムにアップグレード！",
    getPro: "プレミアムを入手",
    upgrade: "アップグレード",
    restore: "購入を復元",
  },
  
  payment: {
    paymentmethod: "支払い方法",
    totalpayment: "支払い総額",
    paymentsuccess: "支払い成功",
  },

  // --- Affiliate ---
  affiliate: {
    yourIncome: "あなたの収入",
    withdraw: "出金",
    product: "商品",
    customer: "顧客",
    commission: "報酬",
    revenua: "売上",
  },

  // --- Notifications ---
  notifications: {
    notifications: "通知",
    markAll: "すべて既読にする",
    emptyNotification: "現在、通知はありません",
  },
  
  // --- Common units/time ---
  common: {
    seconds: "秒",
    minutes: "分",
    hours: "時間",
    days: "日",
  },

  // --- Empty States ---
  emptyList: "リストは空です",
  noResult: "結果が見つかりません！",
  
  // --- Buttons ---
  close: "閉じる",
  done: "完了",
  seeAll: "すべて見る",
};
/* eslint-disable max-len */