/* eslint-disable max-len */

export default {
  detail: "詳細",
  setting: "設定",
  openSetting: "設定を開く",
  language: "言語",
  darkMode: "ダークモード",
  switchLanguage: "言語を切り替える",
  approve: "承認",
  cancel: "キャンセル",
  placeholderEmaiPhone: "メール/電話番号",
  placeholderEmail: "メール",
  placeholderVerifyCode: "認証コード",
  placeholderPasword: "パスワード",
  placeholderRePasword: "パスワードをもう一度入力してください",
  forgotPassword: "パスワードを忘れた",
  verifyCodeTitle: (text) =>
    `${text}から受け取った認証コードを入力してください`,
  signIn: "サインイン",
  signUp: "サインアップ",
  signInWith: "以下でサインイン",
  continue: "続ける",
  continueWith: (text) => `${text}で続ける`,
  enterNewPassword: "新しいパスワードを入力",
  confirmPassword: "パスワードを確認",
  enterOTP: "OTPを入力",
  updatePassword: "パスワードを更新",
  save: "保存",
  required: "必須",
  invalid: "無効",
  or: "または",
  hi: "こんにちは",
  welcomeBack: "今日からあなたの旅を始めましょう！",
  minLength: (number) => `最小${number}文字`,
  needAnAccount: "アカウントが必要ですか？ ",
  registerNow: "今すぐ登録！",
  createNewAccount: "新しいアカウントを作成",
  fullname: "フルネーム",
  haveAnAccount: "すでにアカウントをお持ちですか？ ",
  loginNow: "今すぐログイン！",
  welcomeHeader: "言語の世界へようこそ",
  welcomeDescription: "学びは決して簡単ではありませんが、IELTSであなたは...",
  startNow: "今すぐ開始",
  createPassSuccess: "新しいパスワードの作成に成功しました！",
  loginSuccess: "ログインに成功しました！",
  goBackHome: "ホームに戻る",
  next: "次へ",
  other: "その他",
  recordAudio: "音声を録音",
  playAudio: "音声を再生",
  stopAudio: "音声を停止",
  keepGoing: "続ける",
  changeLanguage: "言語を変更",
  homes: "ホーム",
  chats: "チャット",
  discovers: "発見",
  profile: "プロフィール",
  courses: "コース",
  error: {
    unknown: "未知のエラーが発生しました！",
    invalidPhoneEmail: "無効な電話番号/メールアドレス",
    invalidEmail: "無効なメールアドレス",
    invalidPhone: "無効な電話番号",
    invalidLink: "無効なリンク",
    invalidYoutube: "無効なYouTubeチャンネル",
    invalidFacebook: "無効なFacebookリンク",
    minLengthPass: "パスワードは少なくとも6文字必要です",
    passDoesNotMatch: "確認用パスワードが一致しません",
    errorPatternPass:
      "パスワードは少なくとも8文字で、文字、数字、特殊文字、大文字と小文字を含む必要があります",
    isOffline: "インターネットに接続して再試行してください",
  },
  reset: "リセット",
  apply: "適用",
  blackList: {
    unblock: "ブロック解除",
    unBlockSuccess: "ブロック解除に成功しました！",
    warningUnblock: (name) => `${name}をブロック解除しますか？`,
  },
  you: "あなた",
  permissions: {
    titleAudio: "マイクへのアクセスが必要です",
    messageAudio: "マイクへのアクセスが必要です",
    titleCamera: "カメラへのアクセスが必要です",
    messageCamera: "カメラへのアクセスが必要です",
    denied: "アクセスが拒否されました。以前に拒否した可能性があります！",
    negative: "キャンセル",
    positive: "承認",
  },
  channelLocked: "一時的にチャンネルがロックされています",
  channelLockedDes: "ウェブサイトにアクセスしてチャンネルをアクティブにします",
  create_Channel: "チャンネルを作成",
  unblock: "アンブロック",
  unblockDes: ":usernameのブロックを解除しますか？",
  cancel: "キャンセル",
  postCategory: "カテゴリー",
  createPost: "投稿を作成",
  placeholderContent: "何を考えていますか？",
  confirm: "確認",
  somethingWentWrong:
    "システムにエラーが発生しました。後で再試行してください。",
  notFound: "リストは空です",
  offlineNetwork: "ネットワーク接続がオフラインです",
  onlineNetwork: "データネットワークが再接続されました",
  all: "すべて",
  goToWeb: "詳細をウェブサイトで確認しますか？",
  orderDetail: "詳細情報",
  loadingLogin: "ログイン中...",
  seconds: "秒",
  minutes: "分",
  hours: "時間",
  days: "日",
  weeks: "週",
  months: "月",
  day: "日",
  week: "週",
  month: "月",
  schedule: "スケジュール",
  years: "年",
  ago: "前",
  copied: "コピーされました",
  thankyouForReport: "報告ありがとうございます。違反を確認して対応します！",
  copy: "コピー",
  report: "報告",
  block: "ブロック",
  unBlockUser: "ブロック解除",
  blockedDes: "お互いに見ることや連絡を取ることはできません",
  blockedUser: ":usernameのプロフィールをブロックしました",
  commentAs: "名前でコメント",
  replying: "返信",
  reply: "返信",
  like: "いいね",
  comment: "コメント",
  delete: "削除",
  edit: "編集",
  duplicate: "複製",
  copyLink: "リンクをコピー",
  pinToTop: "トップにピン留め",
  turnOfComments: "コメントをオフにする",
  turnOnComments: "コメントをオンにする",
  deleteSuccess: "削除に成功",
  updateSuccess: "更新に成功",
  pinned: "ピン留め済み",
  loadingMore: "さらに読み込み中",
  hide: "非表示",
  online: "オンライン",
  offline: "オフライン",
  status: "ステータス",
  joined: "参加済み",
  bio: "自己紹介",
  contributions: "貢献",
  follower: "フォロワー",
  following: "フォロー中",
  follow: "フォロー",
  unfollow: "フォロー解除",
  followed: "フォロー済み",
  removeThisFollow: "フォロー解除",
  message: "メッセージ",
  filter: "フィルター",
  sort: "ソート",
  search: "検索...",
  notInGroup: "グループにいません",
  createChannel: "以下のステップでシステムを作成できます",
  createChannelDes: "以下のステップでシステムを作成できます",
  joinViaInvite:
    "システムのオーナーにメールを送信して招待を受け取ることもできます。",
  deleteConfirm: "削除してもよろしいですか？",
  update: "更新",
  viewAll: "すべて表示",
  aboutMe: "自己紹介",
  noReferrals: "紹介はまだありません！",
  noCertificates: "エキスパートはまだ証明書を更新していません！",
  today: "今日",
  yesterday: "昨日",
  tomorrow: "明日",
  from: "から",
  to: "まで",
  justNow: "たった今",
  openFile: "ファイルを開く",
  openFileDes: "ブラウザでファイルを開きますか？",
  active: "アクティブ",
  updateAvailable: "新しい更新があります",
  updateAvailableDes:
    "App Storeで新しい更新が利用可能です。ダウンロードしますか？",
  seemore: "...さらに表示",
  selectImage: "画像を選択",
  draft: "下書き",
  public: "公開",
  private: "プライベート",
  add: "追加",
  cancelEdit: "編集をキャンセル",
  cancelEditDes: "変更は保存されません。続行しますか？",
  clear: "すべてクリア",
  searchForKey: "キーワード検索結果: ",
  viewMore: "詳細を表示",
  role: "役割",
  free: "無料",
  level: "レベル",
  post: {
    likes: (count: number) => `${count} いいね`,
    post: "投稿",
    posts: "投稿",
    detailPost: (name) => `${name}の投稿`,
    createPost: "投稿を作成",
    category: "カテゴリー",
    title: "タイトル",
    content: "内容",
    poll: "投票",
    removePoll: "投票を削除",
    addOption: "オプションを追加",
    addVideo: "ビデオを追加",
    addVideoDes: "YouTube、Vimeo、またはWistiaのリンクを追加してください。",
    link: "リンク",
    pleaseInputTitleOrContent: "内容を追加してください",
    pleaseSelectCategory: "カテゴリーを選択してください",
    pollMinLength: "投票には最低2つの選択肢が必要です",
    createPostSuccess: "投稿に成功",
    like: "いいね",
    liked: "いいね済み",
    share: "シェア",
    comment: "コメント",
    comments: "コメント",
    likeThisPost: "いいね",
    personLiked: "この投稿をいいねした人",
    emptyComment: "コメントはありません",
    emptyCommentDes: "コメントを残してください",
    emptyPost: "投稿はありません",
    postInvalid: "投稿が存在しません",
    emptyPostTitle: "投稿がありません",
    emptyPostDes:
      "友人や専門家が投稿をすると、ここに表示され、その投稿に対していいねやシェア、コメントができます。",
    report: "投稿を報告",
    save: "投稿を保存",
    likeError: "いいねの送信に失敗しました。再試行してください！",
    savePostSuccess: "投稿を保存しました",
    listPostSave: "保存した投稿",
    deleteFromSave: "保存リストから削除",
    emptyListSave: "保存した投稿はありません",
    uploadFileFaild:
      "ファイルのアップロードに失敗しました。再試行してください！",
    uploadImageFaild: "画像のアップロードに失敗しました。再試行してください！",
    uploadVideoFaild:
      "ビデオのアップロードに失敗しました。再試行してください！",
    sharePost:
      "今日からIKIGAI Coachコミュニティに参加して、最大1000ポイントの報酬を受け取りましょう。",
    shareCode: (txt: string) =>
      `一緒にIKIGAIコーチコミュニティに参加して、最大10000ポイントのボーナスを受け取りましょう。ボーナスを受け取るには、「${txt}」にアクセスしてください。`,
  },
  navigation: {
    dashboard: "ダッシュボード",
    courses: "コース",
    leaderboards: "ランキング",
    notifications: "通知",
    menu: "メニュー",
    messages: "メッセージ",
    event: "イベント",
    challenge: "チャレンジ",
    gift: "ギフト",
    podcast: "ポッドキャスト",
    mission: "ミッション",
    notificationDes:
      "通知をオフにすると、ホームページに通知アイコンが表示されます",
  },
  switchGroups: "グループを切り替え",
  createGroup: "グループを作成",
  login: {
    continueFacebook: "Facebookで続行",
    continueGoogle: "Googleで続行",
    continueApple: "Appleで続行",
    email: "メール",
    emailPhone: "メール/電話番号",
    fullname: "フルネーム",
    description: "説明",
    password: "パスワード",
    signin: "ログイン",
    signup: "サインアップ",
    signinWithPassword: "パスワードでログイン",
    dontHaveAccount: "アカウントをお持ちでないですか？",
    or: "または",
    requireLogin: "この機能を使用するにはログインが必要です",
  },
  validate: {
    emailInvalid: "メールが無効です",
    emailPhoneInvalid: "メール/電話が無効です",
    numberInvalid: "番号が無効です",
    requiredEmail: "メールが必要です",
    requiredPassword: "パスワードが必要です",
    requiredFullName: "フルネームが必要です",
    errorOldPassword: "古いパスワードが必要です",
    errorNewPassword: "新しいパスワードが必要です",
    errorConfirmPasswordNotMatch: "パスワードが一致しません",
    errorConfirmPassword: "確認用のパスワードが必要です",
    requiredDate: "日付が必要です",
    requiredName: "名前が必要です",
    requiredTime: "時間が必要です",
    requiredDuration: "期間が必要です",
    requiredLocation: "場所が必要です",
    requiredAttend: "出席が必要です",
    requiredLink: "リンクが必要です",
    requiredDayOfWeeks: "曜日が必要です",
    requiredOccurrences: "出現回数が必要です",
    numberOccurrences: "出現回数は数値である必要があります",
    invalidInput: "入力が無効です",
    requiredDescription: "説明が必要です",
    requiredLevel: "レベルが必要です",
    requiredCourse: "コースが必要です",
    pointBetween: "ポイントは:minから:maxの間である必要があります",
    requiredPhoneNumber: "電話番号が必要です",
    phoneNumberInvalid: "電話番号が無効です",
  },
  home: {
    whatonYourMind: "何を考えていますか",
    dontHasPermissionToCreate: "新しい投稿を作成できません",
    commentSuccess: "コメントが成功しました",
    typeComment: "コメントを入力してください...",
    recentActivity: "最近の活動",
    mostPopular: "最も人気のある",
    mostLike: "最もいいね",
    trending: "トレンド",
    beFirstComment: "最初のコメントをする",
    image: "画像",
    file: "ファイル",
    poll: "投票",
    select: "選択",
    maximunImage: "最大",
    emptyList: "空のリスト",
    deletePostSuccess: "投稿を削除しました",
    deletePost: "投稿を削除しますか？",
    deleteComment: "コメントを削除",
  },
  chat: {
    search: "検索",
    sendMessage: "メッセージを送る",
    startCall: "通話を開始",
    cancel: "キャンセル",
    weHaveRemovedErrorPhoto:
      "エラーの写真ファイルまたは1分以上の動画を削除しました",
    sendYourAudioMessage: "オーディオメッセージを送信してください",
    releaseToSend:
      "送信するには解放し、右に移動してハンズフリーモードを使用してください",
    holdToRecord: "録音するには押し続けてください",
    permissionToRecord:
      "この機能を使用するには、録音、データの書き込み、ライブラリへのアクセスの許可が必要です",
    grandPermission: "許可を付与する",
    noPeopleFound: "現在、このチャンネルには誰もいません",
    emptyListChat:
      "誰とも話したことがありません。誰かとの会話を始めてみてください",
    typeMessage: "メッセージを入力してください...",
    lastSeen: "最後に見た: ",
    desRecord: "録音を開始するにはマイクアイコンをタップしてください",
    addMember: "メンバーを追加",
    addMemberSuccess: "メンバーを追加しました",
    createGroupSuccess: "グループチャットを作成しました",
    selectGroup: "グループを選択",
    selectMember: "メンバーを選択",
    mediaFile: "メディア、ファイル",
    createGroup: "グループを作成する：",
    addToGroup: "グループに追加する：",
    sendFiles: "写真、ファイル、リンクを送信する",
    privacyAndSupport: "プライバシー＆サポート",
    blockUser: "ユーザーをブロック",
    report: "報告する",
    groupAction: "グループアクション",
    leave: "グループを脱退",
    leaveSuccess: "グループを脱退しました",
    renameGroup: "グループ名を変更",
    renameGroupSuccess: "グループ名を変更しました",
    renameGroupFaild: "グループ名の変更に失敗しました",
    enterGroupName: "グループ名を入力してください",
  },
  keyboard: {
    writeSomething: "何かを書いてください",
    sending: "送信中...",
  },
  common: {
    yrs: "年",
    hrs: "時間",
    mins: "分",
    secs: "秒",
    seconds: "秒",
    minutes: "分",
    hours: "時間",
    days: "日",
    months: "月",
    years: "年",
    at: "時",
  },
  course: {
    requestBuyCourse: "すべてのビデオを見るためにコースを購入してください",
    isPreview: "プレビュー",
    warningPrice: "コースの価格を選択してください",
    referUserGuideHere: "使用ガイドはこちらを参照してください",
    publicMode: "公開モード",
    desReferal: (txt: string) =>
      `ユーザーがアプリをインストールしてこのコースを購入すると、あなたは対応する${txt}を受け取ります。金額はあなたの収益ページに更新されます。`,
    uploadVideoPreview: "紹介ビデオをアップロード",
    uploadAlbumPreview: "紹介アルバムをアップロード",
    previewMentor: "プレビューメンター",
    prepareCourse: "これらのコースは現在編集中です！",
    suggestPickCourse: "以下から適切なコースを選択してください！",
    slogan: "教育は力です！",
    course: "コース",
    add: "追加",
    maxLesson: (num: string | number) => `最大授業数は${num}回です。`,
    warningSelectLesson: (num: string | number) =>
      `${num}回のセッションを選択してください`,
    emptyLesson: "先生はその日の予定がいっぱいです。",
    call11With: (type: "teacher" | "student", name: string) =>
      `${name}と1対1の${type === "student" ? "生徒" : "先生"}通話`,
    isFirst: "最初のレッスン",
    warningDelete: "このコースを削除しますか？",
    warningFull: "情報を完全に選択してください",
    duration: "期間",
    timeStart: "開始",
    day: "日",
    schedule: "スケジュール",
    selectedTime: "少なくとも1つのレッスンを選択してください",
    courseMine: "私のコース",
    coursePrice: "上級コース",
    courseFree: "基本コース",
    newCourse: "新しいコース",
    createCourse: "コースを作成",
    updateCourse: "コースを更新",
    uploadCoverImageOrVideo: "コースの紹介動画/画像をアップロード",
    warningUploadCoverImageOrVideo: "コースの紹介動画/画像を選択してください",
    uploadCoverImage: "背景画像をアップロード",
    addCourse: "コースを追加",
    courseName: "コース名",
    courseDescription: "コースの説明",
    courseLongDescription: "コースの詳細",
    whoCanAccessThisCourse: "コースにアクセスできるメンバー",
    publish: "公開",
    videoTooLong: "5秒以下の動画を選択してください",
    pleaseFillInformation: "情報を入力してください",
    createCourseSuccess: "コースの作成に成功",
    open: "開く",
    join: "すぐに参加",
    joined: "参加済み",
    description: "説明",
    mentor: "チャンネルオーナー",
    viewProfile: "プロフィールを見る",
    educationProgram: "教育プログラム",
    viewMore: "もっと見る",
    hideLess: "少なく表示",
    rate: "評価",
    emptyRate: "評価なし",
    rankTeacher: "講師ランキング",
    student: "学生",
    students: "学生",
    many: "",
    courseContent: "コース内容",
    requestSkills: "必要なスキル",
    information: "情報",
    instructor: "専門家",
    titleModule: "モジュールタイトル",
    titleLesson: "レッスンタイトル",
    updateModule: "モジュールを更新",
    updateModuleSuccess: "更新成功",
    createModuleSuccess: "作成成功",
    addModule: "モジュールを追加",
    enterModuleName: "モジュール名を追加",
    media: "画像 & 動画",
    chooseFile: "ファイルを選択",
    downloadDocument: "ドキュメントをダウンロード",
    openWebsite: "ドキュメントを開く",
    editModule: "レッスンとモジュールを編集",
    consistsOf: "構成",
    parts: "部分",
    lectures: "レクチャー",
    requireLevel: "必要なレベル",
    requireLevelDes:
      "残念ながら、このコースを開くのに十分なレベルではありません",
    emptyCourse: "コースがありません",
    price: "価格",
    watchCourse: "コースを見る",
    notJoinedCourse: "まだコースに参加していません",
    mineCourse: "学んだコース",
    freeCourse: "無料コース",
    priceCourse: "上級コース",
    more: "もっと見る",
    completeCourse: "完了",
    activeCourse: "アクティブなコース",
    activeCourseDes:
      "このコースはレベル :level と :coin が必要です。手動でコースをアクティブにするにはウェブサイトをご覧ください。続けますか？",
    activeCourseSuccess: "コースのアクティブ化に成功",
    publicCourse: "コースを公開",
    notificationPublicCourse: "このコースを公開しますか？",
    publicCourseSuccess: "コースの公開に成功",
    noModuleInCourse: "レッスンがありません",
    selectVideoModule: "開始するレッスンを選択",
    teacher: "専門家",
    typeLearning: "学習のタイプ",
    formLearning: "学習形式",
    skills: "カテゴリー",
    filterSpeaker: "地元の専門家",
    viewResult: (text: string) =>
      text != 0 ? text + "のコースを見る" : "結果が見つかりません",
    moreCouresBy: (name: string) => `${name}のコース`,
    viewResultTutor: (text: string) =>
      text != 0 ? text + "の専門家を見る" : "結果が見つかりません",
    priceCourse: "コースの価格",
    filterLevel: "コースレベル",
    select: "選択",
    price_low: "価格: 最低",
    price_high: "価格: 最高",
    rating: "最高評価",
    newest: "新着",
    lastUpdate: "最後の更新",
    buyNow: "今すぐ購入",
    addToCart: "カートに追加",
    filter: "フィルター",
    formOfLearn: "学習形式",
    allForms: "すべて",
    callOneVsOne: "1対1で学ぶ",
    salfLearning: "ビデオで学ぶ",
    callGroup: "グループで学ぶ",
    leave: "休暇予定",
    newClass: "新しいクラス",
    addLeave: "休暇を追加する",
    note: "注記",
    offline: "直接学ぶ",
    allSkills: "すべて",
    listening: "聞く",
    reading: "読む",
    writing: "書く",
    Speaking: "話す",
    careerGuidance: "キャリアガイダンス",
    life: "生活",
    finance: "財務",
    health: "健康",
    business: "ビジネス",
    pricePerCourse: "コースの価格",
    minimum: "最低",
    maximum: "最高",
    levelsOfStudy: "コースレベル",
    timeAvailable: "学習時間",
    dayTime: "昼間",
    eveningAndNight: "夕方と夜",
    onlyEnglish: "ネイティブの先生と学ぶ",
    levelsOfTutor: "講師レベル",
    bestSeller: "ベストセラー",
    growYourListening: "リスニングスキルを向上させる",
    growYourReading: "リーディングスキルを向上させる",
    growYourWriting: "ライティングスキルを向上させる",
    growYourSpeaking: "スピーキングスキルを向上させる",
    sortBy: "ソート方法",
    calendar: "スケジュール",
    reviews: "レビュー",
    apply: "適用",
    placeholderReiview: "レビューを入力",
    sendReview: "レビューを送信",
    updateReview: "レビューを更新",
    certifications: "認定",
    previewThisCourse: "コース紹介",
    watchIntro: "紹介動画を見る",
    title: "タイトル",
    longDescription: "コース詳細",
    startTime: "開始時間",
    endTime: "終了時間",
    limitMember: "最大学生数",
    member: (txt: string | number) => `${txt}人の学生`,
    wriveAReview: "レビューを書く",
    chat: "チャット",
    addLession: "レッスンを追加",
    addFileCourse: "添付ファイルを選択",
    addVideoCourse: "コースのビデオを選択",
    flashSale: "セール",
    titleCourseCategory: "キーワードで検索結果: ",
    assignTask: "課題を割り当てる",
    openVideoRoom: "クラスに入る",
    createClass: "クラスを作成",
    listClass: "クラスリスト",
    createClassSuccess: "クラスの作成に成功",
    addLesson: "レッスンを追加",
    moreTime: "レッスンを追加",
    updateLesson: "レッスンを更新",
    addLessonSuccess: "レッスンの追加に成功",
    addVideo: "ビデオを追加",
    addFile: "ファイルを追加",
    addPart: "部分を追加",
    addPartSuccess: "部分の追加に成功",
    aboutThisCourse: "コース情報",
    shareThisCourse: (courseName: string) =>
      `今日中にたくさんの特典を受け取るために、${courseName}コースを今すぐ購入してください。ダウンロードは`,
    resources: "資料",
    addCourseToFavourites: "お気に入りに追加",
    reportAPlaybackProblem: "再生問題を報告",
    enrollNow: "すぐに参加",
    viewHomework: "宿題を見る",
    Lectures: "レクチャー",
    warningSelectTime: "時間を選択してください",
    warningSelectImage: "コースの画像を選択してください",
    warningSelectTimeGreater: "開始時間は終了時間より前にすることはできません",
    deleteClass: "クラスを削除",
    deleteClassSuccess: "クラスの削除に成功",
    deleteClassError: "クラスの削除に失敗",
    uploadVideoFailed: "画像/ビデオのアップロードに失敗",
    deleteClassDes: "このクラスを削除しますか？",
    deleteModule: "モジュールを削除",
    deleteModuleSuccess: "モジュールの削除に成功",
    deleteModuleError: "モジュールの削除に失敗",
    deleteModuleDes: "このモジュールを削除しますか？",
    typeCourse: "コースタイプ",
    videoReviewCourse: "コース紹介ビデオ",
    requiredTitle: "タイトルは必須です",
    discountEntry: "開始日",
    endAt: "終了日",
    noreview: "レビューなし",
    selectModal: "選択",
    myCourse: "私のコース",
    noClass: "クラスがありません",
    manageClass: "クラスを管理",
    manageCourse: "コースを管理する",
    recommendCourse: "おすすめコース",
    teachingTime: "教えた時間",
    sortByTutor: "講師でソート",
    warningLengthRequired: "レビューは10文字以上でなければなりません",
    updateRateSuccess: "評価の更新に成功",
    sendRateSuccess: "評価の送信に成功",
    level_low: "レベル: 最低",
    level_high: "レベル: 最高",
    delete: "コースを削除",
    report: "コースを報告",
    deleteCourseSuccess: "コースの削除に成功",
    updateSuccess: "更新に成功",
    timeStartAt: "開始時間",
    allCourse: "すべてのコース",
    allTutor: "専門家",
    durationCall11: "コースの期間",
    lessionCount: "レッスンの数",
    messagePublic:
      "コースを公開することを選択した場合、表示される前にIkigai Coachの管理チームによって審査されます。審査には営業日で1日以内がかかります。",
    draft: "下書き",
    public: "公開",
  },
  seeAll: "すべて見る",
  settings: {
    numberOfDays: "日数",
    addPermission: "権限を追加",
    permission: "権限",
    shortcut: "ショートカット",
    options: "オプションと設定",
    calendar: "カレンダー",
    events: "イベント",
    members: "メンバー",
    changePassword: "パスワードを変更",
    accountSetting: "アカウント設定",
    channelSetting: "チャンネル設定",
    settingNoti: "通知のカスタマイズ",
    switchChannel: "チャンネルを切り替え",
    leaderboards: "リーダーボード",
    about: "チャンネル情報",
    boss: "チャンネルオーナー",
    settings: "設定",
    inviteMemberUser: "メンバーを招待",
    inviteMemberMentor: "メンバーを追加",
    inviteMemberSuggestMentor: "コミュニティを拡大",
    inviteMemberSuggestUser: "収入を増やす",
    profile: "プロフィール",
    logout: "ログアウト",
    logoutDes: "ログアウトしますか？",
    invite: "招待",
    general: "一般",
    shortDes: "説明",
    categories: "カテゴリ",
    plugins: "プラグイン",
    metrics: "測定",
    gamification: "ゲーミフィケーション",
    links: "リンク",
    linksInvite: "招待リンク",
    reject: "拒否",
    paid: "支払済み",
    billing: "支払い",
    pending: "保留",
    block: "ブロック",
    remove: "削除",
    notificationLevel: "{need point}ポイントを集めてランクを上げる",
    maxLevel: "最大レベルに達しました",
    shortcuts: "ショートカット",
    becomeAMentor: "メンターになる",
    becomeMentorDes: "メンターになると以下の特権があります:",
    becomeMentorDes1: "無制限の売上特権",
    becomeMentorDes2: "システム内でのコース作成権限",
    becomeMentorDes3: "VIP向けの数十万の特権",
    addLevel: "レベルを追加",
    deleteDes: "{level}を削除してもよろしいですか？",
    point: "ポイント",
    diamond: "ダイヤモンド",
    settingPoint: "ポイントの設定",
    inviteUser:
      "このリンクで招待された人は、メンバー資格の審査プロセスを経ます。招待を資格審査をスキップさせたい場合は、メールで招待してください。",
    sendEmailSuccess: "招待がメールに送信されました",
    newAudio: "音声を変更",
    soundSetting: "あなたの音声を追加",
    deleteAccount: "アカウントを削除",
    deleteAccountConfirm: "(!!) このアカウントを削除しますか？",
    deleteAccountSuccess: "アカウントの削除に成功しました",
    deleteAccountFaild: "アカウントの削除に失敗しました",
    deleteAccountDes:
      "私たちのサービスを改善するためのフィードバックをお願いします。",
    enterReason: "理由を入力",
    category: "カテゴリ",
    channel: "チャンネル",
    comment: "コメント",
    course: "コース",
    level: "レベル",
    module: "レクチャー",
    request: "投稿",
    create: "追加",
    createChannel: "チャンネルを作成",
    update: "編集",
    delete: "削除",
    banUser: "ユーザーをブロック",
    banUserDes: ":usernameをブロックしますか？",
    removeUser: "ユーザーをチャンネルから削除",
    removeUserDes: ":usernameをチャンネルから削除しますか？",
    descriptionPoint:
      "これは、各アクションに対して受講生が受け取るポイントの数です",
    publicStatus:
      "誰でもチャンネル内の人物とその投稿を見ることができます。内容は検索ツールで見つけることができます。",
    privateStatus:
      "メンバーのみがチャンネル内の人物とその投稿を見ることができます。内容は検索ツールから隠されています。",
    navigationBar: "ナビゲーションバー",
    createNewChannel: "あなたのチャンネルを作成",
    copyLink: "リンクをコピー",
    customNavigationBar: "カスタムナビゲーションバー",
    navigationBarDes:
      "下部のナビゲーションバーに3つのボタンを選択できます（デフォルトはホームとタスクの2つのボタンを含む）。すべてのチャンネルメンバーは、あなたの設定に従ってこのナビゲーションバーに自動的に切り替わります。",
    inviteDes:
      "あなたは紹介した人々ごとに4000ポイントを受け取ります。紹介された人々は1000ポイントを受け取ります。",
    changeLanguage: "言語を変更",
    warningDeleteAccount: "アカウントを削除しますか？",
  },
  profile: {
    editProfile: "プロフィールを編集",
    saveProfile: "プロフィールを保存",
    profile: "プロフィール",
    account: "アカウント",
    notifications: "通知",
    chat: "チャット",
    bio: "自己紹介",
    addBio: "自己紹介を追加",
    birthday: "誕生日",
    address: "住所",
    phoneNumber: "電話番号",
    socialLink: "ソーシャルリンク",
    updateProfileSuccess: "プロフィールを更新しました",
    oldPassword: "古いパスワード",
    newPassword: "新しいパスワード",
    confirmPassword: "パスワードを確認",
    changePassword: "パスワードを変更",
    notifyMeByEmail: "メールで通知",
    dontNotifyMeByEmail: "メールで通知しない",
    userNotifications: "ユーザー通知",
    whenSomebodyFollowsMe: "誰かがフォローしたとき",
    whenIEarnMoneyFromReferrals: "紹介で収入が発生したとき",
    groupNotifications: "グループ通知",
    digestEmailFrequency: "ダイジェストメール頻度",
    digestEmailFrequencyDes:
      "グループにアクセスしていないときの人気の投稿とメンバーの活動を要約してメールで送信",
    notificationsEmailFrequency: "通知メール頻度",
    notificationsEmailFrequencyDes:
      "フォローしている投稿/メンバーのいいね、コメント、言及、未読の活動を要約してメールで送信",
    postLikesNotifications: "いいねの通知",
    postLikesNotificationsDes: "誰かが投稿をいいねしたときに通知",
    adminAnnouncements: "管理者からのお知らせ",
    adminAnnouncementsDes: "管理者が新しい投稿をしたときに通知",
    eventReminders: "イベントリマインダー",
    eventRemindersDes: "イベントが開始する前に通知",
    daily: "毎日",
    weekly: "毎週",
    every14Days: "14日ごと",
    monthly: "毎月",
    never: "通知しない",
    mins: "分",
    hourly: "毎時",
    hours: "時間",
    notifyMe: "通知する",
    dontNotifyMe: "通知しない",
    yes: "はい",
    no: "いいえ",
    notifyChat: "チャット通知をオンにする",
    emailNotifications: "メール通知",
    emailNotificationsDes:
      "メールで通知を受け取る。オンラインの場合、メールは送信されません。",
    whoCanMessageMe: "メッセージを送る人",
    whoCanMessageMeDes:
      "グループメンバーだけがあなたにメッセージを送ることができます。下記でグループを選択してください。",
    on: "オン",
    off: "オフ",
    pointToLevelUp: "ポイントでレベルアップ",
    permisisonDenied: "アクセス権がありません",
    permissionDeniedDes: (text: string) =>
      `現在、${text}へのアクセス権がありません。設定に進みますか？`,
    shareProfile: "プロフィールを共有",
  },
  profileTeacher: {
    revenua: "収益",
    withdraw: "引き出し",
    setUpAccount: "口座設定",
    myCourse: "私のコース",
    schedule: "授業スケジュール",
    discount: "割引コード",
    chat: "生徒とチャット",
    setTeaching: "授業時間の設定",
    manageClass: "クラス管理",
    customProfile: "プロフィールのカスタマイズ",
    manageCerti: "証明書の管理",
    myClub: "私のクラブ",
    myPodcast: "私のポッドキャスト",
    guide: "使用方法ガイド",
    Security: "セキュリティとポリシー",
    finance: "ファイナンス",
    course: "コース",
    teacherPage: "教師ページ",
    guideUse: "ガイド",
    titleBtn: "生き甲斐コーチ教師",
    desBtn: "教師専用ページにアクセスする",
    profile: "プロフィールを見る",
    balance: "残高",
    task: "任務",
  },
  member: {
    chat: "チャット",
    membership: "メンバーシップ",
    memberOfGroup: "グループのメンバー",
    followSuccess: "{name}をフォローしました。",
    unfollowSuccess: "{name}のフォローを解除しました。",
    blockSuccess: "{name}をブロックしました",
    deleteSuccess: "削除しました",
    deleteInviteJoinChannel: "{name}のチャンネルへの招待をキャンセルしますか？",
  },
  event: {
    addEvent: "イベントを追加",
    updateEvent: "イベントを更新",
    title: "タイトル",
    date: "日付",
    time: "時間",
    duration: "開催時間（時間）",
    timezone: "タイムゾーン",
    recurringEvent: "定期的なイベント",
    location: "イベントの場所",
    link: "リンク",
    description: "説明",
    whoCanAttendThisEvent: "誰がこのイベントに参加できますか",
    remindMembersByEmail: "1日前にメールでメンバーにリマインド",
    create: "作成",
    library: "ライブラリ",
    repeatOn: "繰り返し",
    end: "終了",
    repeatEvery: "毎に繰り返し",
    pleaseSelectDay: "繰り返しの日を選択してください",
    after: "後",
    occurrences: "回出現",
    uploadCoverImage: "カバー画像をアップロード",
    allMembers: "すべてのメンバー",
    membersAtLevel: "レベルのメンバー",
    membersInCourse: "コースのメンバー",
    endDate: "終了日",
    never: "絶対になし",
    createEventSuccess: "イベントが作成されました",
    pleaseSelectImage: "画像を選択してください",
    peopleInterested: "興味を持っている人",
    interest: "興味",
    interested: "興味あり",
    eventOfSpeaker: "スピーカーのイベント",
    detailEvent: "イベントの詳細",
    suggestEvent: "イベントの提案",
    yourEvent: "あなたのイベント",
    allEvent: "すべてのイベント",
    join: "参加",
    eventNotFoundToday: "今日のイベントは見つかりません",
    eventNotFound: "現在、イベントはありません",
    permissionCreateLivestreamEvent:
      "イベント内でライブストリームを作成する権限がありません",
    permissionUpdateLivestreamEvent:
      "イベント内のライブストリームを更新する権限がありません",
    historyLivestream: "ライブストリームの履歴",
    timeLivestream: "ライブ時間",
    eventFinish: "イベントが終了",
    eventConfirm: "ビデオ通話を終了しますか",
    eventEndLive: "ライブストリームを停止しますか",
    events: "イベント",
    upComing: "今後のイベント",
    pastEvent: "過去のイベント",
    going: "参加",
    eventBy: "主催者",
    deleteEvent: "イベントを削除",
    editEvent: "イベントを編集",
    confirmDelete: "削除してもよろしいですか",
    deleteEventSuccess: "イベントが削除されました",
    editEventError: "イベント時間を超えたため編集できません",
    eventEnded: "イベントが終了しました",
    deleteEventError:
      "イベントが既に発生した場合、このアクションを実行できません",
    emptyEventTitle: "イベントがありません",
    emptyEventDes:
      "友達や専門家がイベントを作成すると、ここに表示されます。その後、そのイベントに参加できます。",
  },
  notifications: {
    notifications: "通知",
    markAll: "すべてを既読にする",
    turnonChat: "メッセージがあるときに通知をオンにする",
    turnonPost: "新しい投稿があるときに通知をオンにする",
    turnonCourse: "コースからの新しい情報があるときに通知をオンにする",
    emptyNotification: "現在、通知はありません",
  },
  invite: {
    invitePeople: "招待する",
    toJoin: "参加する {channel}",
    sendInvite: "招待を送る",
    getLink: "共有リンクを取得",
    titleInvite: "紹介コードはありますか？",
    desInvite: "友達から受け取った紹介コードをここに入力してください！",
    enterCode: "コードを入力",
    enterCodeSuccess: "紹介コードが正常に入力されました",
    enterCodeFaild: "コードが正しくありません、再度試してください。",
    send: "送る",
    emptyListInvite: "あなたのコードを入力した人はまだいません",
    codeActivations: "コードのアクティベーション",
  },
  categories: {
    addCategory: "カテゴリを追加",
    edit: "編集",
    delete: "削除",
    add: "追加",
  },
  gamifications: {
    description:
      "もっと活気のある雰囲気にしましょう！このレベルに適切な名前を選んで、ユーザーがより多くのインタラクションを行い、授業をアンロックするように奨励します。",
    level: "レベル",
    point: "ポイント",
    pointHigher: "レベル{level}より高いポイント",
    pointLower: "レベル{level}より低いポイント",
    pleaseInputPoint: "ポイントを入力してください",
  },
  liveStream: {
    endLive: "ライブセッションを一時停止",
    startLive: "ライブセッションを開始",
    tapToAddDescription: "説明を追加するにはタップ",
    goLive: "ライブ開始",
    finish: "終了",
    createLiveStream: "ライブストリームを作成",
    createLivestreamError:
      "ライブストリームの作成に失敗しました。後でもう一度試してください",
    imageThumbnail: "ライブストリームのサムネイル",
    liveStreamNow: "今すぐライブ",
    userJoinLive: ":usernameが参加しました",
    userLeftLive: ":usernameが退室しました",
    commentHere: "コメントはここに表示されます",
    swipeLeft: "右にスワイプしてコメントを見る",
    livestreamEnded: "ライブストリームが終了しました",
    livestreamNotStarted: "ライブストリームはまだ開始されていません",
    back: "戻る",
    writeComment: "コメントを書く...",
    noRoleCreate: "ライブストリームのセッションを作成する権限がありません",
    connecting: "接続中",
    infoLivestream: "ライブストリーム情報",
    otherPlatform: "他のプラットフォーム",
    notePlatform:
      "注意：この方法でライブストリームを行うと、カメラでライブストリームを行う場合よりも遅延が大きくなります。",
    joinCoursesSuccessfully: "コースへの参加に成功しました",
    questionEndLivestream: "ライブストリームを終了してもよろしいですか？",
    watch: "視聴",
    pinProduct: "商品をピン留め",
    addCover: "画像を選択",
    change: "変更",
    warning: "ライブストリームを開始する前に画像を選択してください",
    likes: "いいね",
    streamPending: "ライブストリーム セッションが間もなく始まります",
  },
  startChatDesc:
    "彼らの学習の旅や共通の趣味について質問するメッセージを送信して、会話を開始しましょう",
  challenge: {
    suggestPickChallenge: "下のチャレンジに参加しましょう！",
    mineChallenge: "参加中",
    create: "新規作成",
    join: "参加",
    postDate: "投稿日",
    challenges: "チャレンジ",
    checkin: "アクティビティを報告",
    historyActivity: "アクティビティ履歴",
    conditionFree: "すべてのメンバーが参加可能",
    conditionPoint: "ポイントが{point}以上のメンバー向け",
    conditionLevel: "レベルが{level}以上のメンバー向け",
    account: "アカウント",
    point: "ポイント",
    rank: "ランク",
    mine: "私のもの",
    all: "すべて",
    timeStart: "時間：$time",
    suggestJoin: "チャレンジに参加して、価値のある賞品を獲得しましょう！",
    joinNow: "今すぐ参加",
    slogan: "成長のための競争",
    createChallenge: "基本情報",
    startDate: "開始日",
    leaderboard: "リーダーボード",
    information: "情報",
    general: "概要",
    condition: "参加条件",
    playRule: "ルール",
    detail: "詳細",
    members: "プレイヤー",
    reward: "報酬",
    notification: "通知",
    endDate: "終了日",
    requireChallenge: "参加条件",
    pleaseInputAvatar: "チャレンジの画像を追加してください",
    selectGame: "ゲームを選択",
    configGame: "ゲームの設定",
    gameName: "ゲーム名",
    requireGameName: "ゲーム名を入力してください",
    scoringCriteria: "スコアリング基準",
    scoringCriteriaGuide:
      "これはチャレンジのスコアリング方法です。\nスコアリング方法とフォーマットを選択してください。\n例：売上競争ゲーム。\nスコアリング方法は：スクリーンショットと売上。\nスクリーンショット - 画像形式、売上 - ポイント形式。",
    type: "タイプ",
    gift: "ギフト",
    giftChallengeComplete: "チャレンジ完了時のギフト",
    addGift: "ギフトを追加",
    giftName: "ギフト名",
    valueGift: "ギフトの価値",
    newGift: "新しいギフト",
    info: "情報",
    stage: "ステージ",
    stageSetting: "ステージ設定",
    addStage: "時間を追加",
    stageName: "ステージ名",
    typeCheckin: "チェックインタイプ",
    createChallengeSuccess: "新規 チャレンジの作成に成功しました",
    noChallenge: "まだチャレンジがありません",
    deleteDescription: "このチャレンジを削除してもよろしいですか？",
    quantity: "数量",
    publicStatus: "条件を満たせば誰でも参加可能",
    privateStatus: "参加メンバーはBossの承認が必要",
    noMember: "参加メンバーリストは空です",
    noPending: "リストは空です",
    uploadImage: "画像をアップロード",
    member: "メンバー",
    activity: "アクティビティ",
    recentActivity: "最近のアクティビティ",
    addActivity: "アクティビティを追加",
    content: "内容",
    requireContent: "入力してください",
    reason: "理由",
    rejected: "拒否",
    aproved: "承認",
    reject: "拒否",
    aprove: "承認",
    pending: "保留",
    status: "ステータス",
    aproveDes: "アクティビティを承認",
    rejectDes: "アクティビティを拒否",
    waitingLiveStream: "開始予定",
    endedLiveStream: "終了",
    watchLive: "ライブを見る",
    goLive: "ライブ開始",
    noActivity: "アクティビティはありません",
    people: "人々",
    maxUser: "最大プレイヤー数",
    infinityUserJoin: "無制限",
    cannotUpdateChallenge: "このチャレンジは更新できません",
    past: "終了",
    present: "進行中",
    future: "開始予定",
    public: "誰でも参加可能",
    pendingStatus: "保留中",
    createNewGame: "新しいゲームを作成",
    createNewGameDes: "ゲームのフィールドと名前を自分で設定します",
    title: "チャレンジ名",
    pleaseAddGiftChallenge: "チャレンジにギフトを追加してください",
    memberList: "参加メンバーリスト",
    deleteUserSuccess: "メンバー削除に成功しました",
    deleteUser: "メンバー削除",
    deleteUserDes: "このメンバーをチャレンジから削除してもよろしいですか？",
    createNextCycle: "次のサイクルで自動作成",
    addAllUser: "すべてのユーザーを自動追加",
    challengeHasBeenDeleeted: "チャレンジが削除されました",
    pleaseAddInfoStage: "チャレンジのステージ情報を入力してください",
  },
  codeActivations: {
    sortBy: "ソート方法",
    timeLatest: "時間：新しい順",
    priceHighest: "価格：高い順",
    header: "コードをアクティベート",
    referrer: "紹介者",
    copyCodeSuccsess: "コードのコピーに成功",
    activate: "アクティベート",
    goTo: "移動",
    referrerCode: "紹介コード",
    referrerList: "紹介者リスト",
  },
  mentor: {
    user: "ユーザー",
    mentor: "メンター",
    listMentor: "メンターリスト",
    listUser: "ユーザーリスト",
    addMentor: "メンターを追加",
    addSuccess: "追加に成功",
    addMentorDes: ":usernameをメンターに追加してよろしいですか？",
    deleteMentorDes: ":usernameをメンターリストから削除しますか？",
    addUser: "ユーザーを追加",
    addUserDes: ":usernameをリストに追加しますか？",
    deleteUserDes: ":usernameをリストから削除しますか？",
    deleteUser: "ユーザー削除",
    deleteMentor: "メンター削除",
    analytics: "分析",
    today: "今日",
    yesterday: "昨日",
    thisMonth: "今月",
    lastMonth: "先月",
    estimateEarn: "推定収益",
    history: "履歴",
    settingProfit: "利益設定",
    paymentHistory: "支払い履歴",
    selectDate: "日付を選択",
    last7day: "過去7日間",
    last30day: "過去30日間",
    info: "情報",
    product: "製品",
    course: "コース",
    time: "時間",
    transactionValue: "取引価格",
    commission: "コミッション",
    incomeValue: "収入",
    userBuy: "購入ユーザー",
    date: "日付",
    unitPrice: "VND",
    settingsCommissionDes:
      "紹介者が製品を購入するときに紹介者が受け取るコミッション率（％）",
    commissionMentor: "メンターへのコミッション率（％）",
    commissionUser: "ユーザーへのコミッション率（％）",
    timeJoin: "参加日",
    withdraw: "引き出し",
    userWithdraw: "引き出しユーザー",
    timeWithdraw: "時間",
    moneyWithdraw: "金額",
    statusWithdraw: "ステータス",
    changeStatus: "ステータス変更",
    done: "完了",
    processing: "処理中",
    fail: "失敗",
    infoCommission: "コミッション情報",
    commissionHeader:
      "この機能は、チャンネル所有者がチームを構築し、販売者を育てるためのサポートを提供するためのものです。\nこの機能の特徴は、チャンネル所有者がコミュニティ内のユーザーを3 つの役割に分け、それぞれの役割に対して一定のコミッションを提供できる点です。",
    textCommissionBoss:
      "- この役割では、ユーザーは完全に自分のコミュニティをコントロールし、他のユーザー（メンター、ユーザー）に権限を与えることができます。\n- メンターとユーザーの各取引ごとのコミッション率を設定できます。",
    textCommissionMentor:
      "- チャンネル所有者が指定したユーザー数を管理します。\n- 管理するユーザーからの取引ごとに終身コミッションを受け取ります。\n- 新しいメンバーをコミュニティに紹介することで、管理するユーザー数を増やすことができます。",
    textCommissionUser:
      "- コミュニティ内で他のユーザーが製品を購入すると、コミッションを受け取ります。",
    yourIncome: "収入",
    pleaseGoToWebsiteToWithdraw:
      "ウェブサイトにログインして引き出しフォームを送信してください",
  },
  coupon: {
    coupon: "割引コード",
    couponMyCourse: "私のコースの割引コード",
    createCoupon: "新しい割引コードを追加",
    updateCoupon: "割引コードを更新",
    saveCoupon: "割引コードを保存",
    add: "追加",
    applyCoupon: "割引コードを適用",
    update: "更新",
    save: "保存",
    title: "割引コードの名前",
    description: "説明",
    promotion: "割引率",
    addCouponSuccess: "割引コードの追加に成功しました！",
    addCouponFailed:
      "割引コードの追加に失敗しました。後ほど再試行してください。",
    updateCouponSuccess: "割引コードの更新に成功しました！",
    updateCouponFailed:
      "割引コードの更新に失敗しました。後ほど再試行してください。",
    listCouponForMyCourse: "私のコースの割引コードリスト",
    percentage: "パーセンテージ（%）",
    value: "割引額",
    warningCoupon: "無効な割引額",
    period: "期間",
    type: "割引タイプ",
    deleteCouponSuccess: "割引コードの削除に成功しました！",
    deleteCouponFaild:
      "割引コードの削除に失敗しました。後ほど再試行してください。",
    warningDeleteCoupon: "この割引コードを本当に削除しますか？",
    selectCourse: "コースを選択",
    choose: "選択済み",
    chooseProduct: "製品を選択",
    applyForProduct: "製品に適用",
    reduce: "削減",
    reductionLevel: "割引レベル",
    notDisplay: "購入者に表示しない",
  },
  gift: {
    gift: "ギフト",
    noGift: "ギフトはまだありません",
    addGift: "新しいギフトを追加",
    updateGift: "ギフトを更新",
    giftName: "ギフト名",
    giftValue: "価値(VND)",
    quantity: "数量",
    conditionalGift: "ギフト受取条件",
    birthday: "誕生日",
    likeNumber: "「いいね」の数",
    commentNumber: "コメント数",
    moduleNumber: "学習済みモジュール数",
    createSuccess: "ギフトの追加に成功しました",
    left: "残り",
    noLeft: "在庫切れ",
    deleteGiftDes: "ギフト :name を削除してよろしいですか？",
    priceDesc: "価値が高い順",
    priceAsc: "価値が低い順",
    timeDesc: "新しいギフト",
    timeAsc: "古いギフト",
    qtyDesc: "数量が多い順",
    qtyAsc: "数量が少ない順",
    info: "情報",
    receiverUser: "受取ユーザー",
    prepare: "準備中",
    transport: "配送中",
    received: "受取済み",
    cancel: "キャンセル",
    sendGift: "ギフトを送る",
    selectGift: "ギフトを選択",
    selectPeople: "人を選択",
    add: "追加",
    added: "追加済み",
    sendGiftSuccess: "ギフト送信に成功しました",
    sendGiftDescription: ":gift ギフトを :user ユーザーに送信しますか？",
    listReceive: "受取リスト",
    digitalGift: "デジタルギフト",
    normalGift: "通常のギフト",
    giftDigitalUrl: "デジタルギフトURL",
    giftDigitalFile: "デジタルギフトファイル",
    giftDigitalDes:
      "この情報は、ユーザーがギフト受取条件を満たした場合に表示されます。",
    giftNormalDes: "この情報は、ユーザーに常に表示されます。",
    giftInfo: "ギフト情報",
    uploadFile: "ギフトをアップロード",
  },
  extension: {
    inDevelop: "開発中",
    bought: "インストール済み",
    extensions: "拡張機能",
    goToWeb: "ウェブサイトにアクセスしてインストールしますか？",
    setup: "設定",
    extensionTitle: "無限の拡張機能で最適化",
    extensionDescription: "ニーズに応え、無制限に拡張します",
    extensionInfo: "拡張機能について",
    price: "価格",
    freeTrial: "無料トライアル",
    go: "開始",
    noticeFeatureExtend:
      "この機能を延長するためにウェブサイトに移動しますか。続行しますか？",
    feature: "機能",
    featureExpired:
      "この機能はあと :day 日で期限切れになります。中断なく使用を続けるためにアップグレードしてください。",
    watchNow: "すぐに見る",
    joinNow: "今すぐ参加",
    freeTrialDay: "無料トライアル :day 日間",
  },
  updateProfile: {
    phoneNumber: "電話番号を入力",
    validatePhoneNumber: "電話番号の確認",
    otp: "OTPコードを入力",
    resend: "再送する",
    invalidCode: "OTPコードが正しくありません",
    pleaseWait: "お待ちください",
    otherPhoneNumber: "別の電話番号を入力",
    otherChannel: "他のチャンネルでログインしますか？",
    otherAccount: "他のアカウントを使用しますか？ログアウト",
    phoneNumberAlreadyInUse: "この電話番号は既に使用されています",
    continueWithoutVerity: "認証なしで続行",
    getOTPFailed: "OTPコードの取得に失敗しました。再試行してください！",
    verifySuccess: "認証成功",
    requireOtp: "OTPコードを入力してください",
    verifyDes:
      "いつでもサポートを受けるために電話番号を提供していただきたいです。電話番号の認証を希望しない場合は、このステップをスキップしてください。",
    skip: "スキップ",
  },
  permission: {
    NotiMissionSuccess: "おめでとうございます、ミッションを完了しました",
    todayPermission: "今日のミッション",
    Perform: "実行",
    completeMissionAndGift: "ミッションを完了して豪華なギフトを受け取る",
    giftToday: "今日のギフト",
    completeNow: "今すぐ今日のミッションを完了！",
    mission: "ミッション",
    pleaseChooseMission: "ミッションを選択してください",
    likePost: "投稿を「いいね」する",
    likeComment: "コメントを「いいね」する",
    inviteParticipants: "参加者を招待する",
    commentPost: "投稿にコメントする",
    uploadPost: "投稿をアップロードする",
    viewCourse: "コースの動画を見る",
    addMission: "ミッションを追加",
    titleMission: "ミッションのタイトル",
    pleaseInputCountMission: "ミッションの数を入力してください",
    deleteMissionSure: "このミッションを削除してもよろしいですか？",
    reward: "報酬",
    physicalGift: "物理的なギフト",
    numberCoin: "ダイヤモンドの数",
    missionCompleted: "ミッションが完了しました",
    missionName: "ミッション名",
    createSuccess: "ミッションの作成に成功",
    updateProfile: "プロフィールの更新",
    nextMissions: "次の日のミッション",
    missionDayIs: "第{day}日のミッション",
    missionOver: "ミッションが終了しました",
    youCanEditAndDelete: "ミッションを編集および削除できます",
    deleteMissionSuccess: "ミッションの削除に成功",
    notificationUpdateMission:
      "ミッションを編集すると、以前の記録がすべて失われます。このミッションを編集してもよろしいですか？",
    updateMission: "ミッションの更新",
    updateMissionSuccess: "ミッションの更新に成功",
    prev: "前へ",
    next: "次へ",
    diamond: "ダイヤモンド",
    dontHaveModuleGift:
      "ギフト機能をまだ購入していません！チャンネル上のメンバーの相互作用を促進するために今すぐ取得してください。",
    dontHaveMission:
      "{day}日のミッションが追加されていません。少なくとも1つのミッションを追加してください！",
    updateSuccess: "更新に成功",
    errorsValidateMissionDay: "{day}日にミッションを追加してください",
    descriptionUpdateProfile: "(名前と電話番号の更新)",
    errorsValidateCountMissionDay: "{day}日のミッションの数を追加してください",
    completeCourse: "コースを完了する",
    inviteUser: "ユーザーを招待する",
    congratulation: "おめでとうございます、ギフトを受け取りました",
  },
  podcast: {
    createPlaylist: "プレイリストを作成",
    createPodcast: "ポッドキャストを作成",
    myPodcast: "私のポッドキャスト",
    uploadePodcast: "ポッドキャストをアップロード",
    selectPodcast: "ポッドキャストリストを選択してください",
    warningSelectCover: "ポッドキャストのカバー画像をアップロード",
    warningUploadPodcast: "アップロードするポッドキャストファイルを選択",
    createPodcastSuccess: "ポッドキャストのアップロードに成功しました",
    createPodcastFaild: "ポッドキャストのアップロードに失敗しました",
    public: "公開",
    member: "メンバー",
    updating: "ポッドキャストは更新中です。後でもう一度お試しください。",
    listPodcast: "ポッドキャストのリスト",
    emptyList: "ポッドキャストがありません",
    infoPodcast: "ポッドキャスト情報を入力",
    titlePodcast: "タイトル",
    contentPodcast: "内容",
    createPodcastSuccessfully: "ポッドキャストの作成に成功",
    updatePodcastSuccessfully: "ポッドキャストの更新に成功",
    imageRequired: "画像を追加してください",
    titleRequired: "ポッドキャストのタイトルを入力してください",
    addPodcast: "ポッドキャストを追加",
    record: "録音",
    uploadFile: "ファイルをアップロード",
    stop: "停止",
    hint: "内容のヒント",
    thumbnail: "ポッドキャストのサムネイルを選択",
    artist: "アーティスト",
    info: "情報",
    list: "リスト",
    add: "追加",
    description: "説明",
    listenNow: "今すぐ聴く",
    category: "カテゴリ",
    audio: "オーディオ",
    language: "言語",
    showMore: "もっと見る",
    countReview: (val: string | number) => `レビュー (${val})`,
    showAllReview: "すべてのレビューを表示",
    writeAReview: "レビューを書く",
    warningReviewShort: "レビューは10文字以上必要です",
    sendReviewSuccess: "レビューの送信に成功",
    emptyReview: "レビューはまだありません",
    cancel: "キャンセル",
    send: "送信",
    title: "タイトル",
    review: "レビュー（オプション）",
  },
  faq: {
    titleFaq:
      "ユーザーのニーズに応じて、仮想通貨「Point」とダイヤモンドが誕生しました。",
    whatIsPoint: "Pointとは？",
    whatIsDiamond: "ダイヤモンドとは？",
    descriptionPoint:
      "コミュニティ内でのインタラクション（コメント、いいね、投稿、メンバーの招待、コースの視聴、出席確認など）に応じて、メンバーは管理者の設定に従ってPointを獲得します。\n\nこの仮想通貨を使用して、レベルアップや新しいコースのアンロックができます。",
    descriptionDiamond:
      "コミュニティ内でダイヤモンドを獲得するためには、日常的なタスクや出席確認などのタスクを完了する必要があります。\n\nダイヤモンドは、コミュニティ内でコースを購入するために使用できます（1ダイヤモンドは1000VNĐ相当）。",
    actionPoint:
      "コミュニティ内でのインタラクションに応じて、メンバーはPointを獲得します。",
    personPoint:
      "メンバーはこの仮想通貨を使用して、レベルアップや新しいコースをアンロックできます。",
    titleDiamond:
      "コミュニティ内でダイヤモンドを獲得するためには、日常的なタスクや出席確認などのタスクを完了する必要があります。",
    personDiamond:
      "メンバーはダイヤモンドを使用してコースを購入することができます（1ダイヤモンドは1000VNĐ相当）。",
    noteDiamond:
      "注意: Pointとダイヤモンドは、メンバーが対話しているコミュニティでのみ有効です。",
  },
  introduce: {
    scrollDownToSeeNewPost: "最新の投稿を見るには下にスクロール",
    introducePoint: "コースのアンロックに使用",
    introduceDiamond: "購入用の仮想通貨",
  },
  results: "結果",
  sort_by_relevance: "関連性でソート",
  noResult: "結果が見つかりません",
  startChat: "チャットを開始！",
  startDesc:
    "英語の学習旅行に関する質問をしたり、面白いトピックで議論を始めるメッセージを送信してください",
  noNewMessageTittle: "新しいメッセージはありません",
  noNewMessageDesc:
    "他の人と連絡を取るか、有料コースを購入すると、メッセージがこちらに表示されます",
  actionView: {
    sendYourAudioMessage: "あなたのオーディオメッセージを送信",
    releaseToSend:
      "送信するにはリリース、右にスワイプしてハンズフリーモードに切り替え",
    holdToRecord: "録音するには長押し",
  },
  mediaKeyboard: {
    chooseFromGallery: "ギャラリーから選択",
    permissionToRecord:
      "この機能を使用するには録音、データの記録、ギャラリーへのアクセスの許可が必要です",
    grandPermission: "許可する",
    weHaveRemovedErrorPhoto:
      "1分以上のエラーのある写真またはビデオファイルを削除しました",
    attention: "注意!",
    imageIsError: "画像にエラーがあります!",
    shootAVideo: "ビデオを撮影",
    takeAPhoto: "写真を撮影",
  },
  keyboard: {
    writeSomething: "メッセージを入力...",
    sending: "送信中...",
  },
  audio: {
    titlePodcast: "ポッドキャストのタイトル",
    description: "説明",
    playlist: "プレイリスト",
    typeOfPodcast: "ポッドキャストの種類",
    full: "フル",
    trailer: "予告編",
    uploadAudio: "オーディオをアップロード",
    play: "再生",
    pause: "一時停止",
    resume: "再開",
    stop: "停止",
    send: "送信",
    audioBook: "オーディオブック",
    typeAudio: "オーディオタイプ",
    recommendBook: "推奨書籍",
    teacherPodcast: "先生のポッドキャスト",
    episodeList: "エピソードリスト",
    continueListen: "続けて聴く",
    listen: "再生回数",
    allAudio: "すべてのオーディオ",
    noListen: "再生回数なし",
    orientation: "オリエンテーション",
    life: "生活",
    health: "健康",
    business: "ビジネス",
    finance: "財務",
    emptyAudio: "オーディオがありません",
    isFirst: "リストの先頭です",
    isLast: "リストの最後です",
    shareAudio: (txt: string) =>
      `IKIGAI Coachアプリをダウンロードして、最高のオーディオブックを聴こう: ${txt}`,
    listened: "聞いた",
  },
  livestream: {
    hello: "こんにちは",
    inputTitle: "ライブストリームのタイトルを入力",
  },
  purchase: {
    headerBookLesson: "レッスンを予約",
    headerChooseClass: "クラスを選択",
    timeDuration: "学習時間",
    chooseDay: "学習日を選択",
    chooseDayDes: "最大4日まで選択できます",
    timeNote: "あなたのタイムゾーン、Asia/Ho Chi Minh (GMT +7:00)",
    morning: "朝",
    Afternoon: "午後",
    Night: "夜",
    hoursNote: "最大2つの学習時間帯を選択できます",
    orderNow: "支払う！",
    participants: "参加者",
    startDate: "開始日",
    endDate: "終了日",
    startCourse: "開講日時を設定",
    endCourse: "終了日時",
  },
  payment: {
    paymentmethod: "支払い方法",
    paymentdetail: "支払い詳細",
    totalpayment: "合計金額",
    sendImageSuccess: "画像送信成功",
    vnpay: "VNPay",
    smartbanking: "スマートバンキング",
    formforLearning: "学習方法",
    class: "クラス",
    days: "学習日",
    learningtime: "学習時間",
    promo: "プロモーション",
    errorpaymentmethod: "支払い方法を選択していません",
    couresfree: "無料コース",
    coursePrice: "コース価格",
    livePrice: "ライブ配信価格",
    completecheckout: "支払い完了",
    promotion: "プロモーション",
    notePurchase:
      "取引完了まで少し時間がかかる場合があります。成功したらお知らせします",
    paymentsuccess: "支払い成功",
    completepayment:
      "支払いが完了したら、下のボタンをクリックしてコースを楽しむことができます。",
    gomylearning: "学習へ進む",
    uploadfile: "ファイルをアップロード",
    send: "送信",
    sendPro: "取引情報を送信",
    saveQRCode: "QRコードを保存",
    tocomplete:
      "支払いを完了するために、以下のアカウントに振り込みを行ってください：",
    content: "振り込み内容",
    courseNotAvailable: "コースは利用できません",
    selectlang: "言語を選択する",
  },
  settingUser: {
    language: "言語",
    hightandweigh: "身長/体重の単位",
    space: "距離の単位",
    deletecache: "キャッシュを削除",
    noti: "通知",
    hidden: "Ikigai Coach Gから一時的に非表示",
    block: "未知の人からのメッセージをブロック",
    blackList: "ブラックリスト",
    setting: "設定",
    private: "プライバシー",
    support: "カスタマーサポート",
    aboutus: "私たちについて",
    mycouse: "私のコース",
    purchaseCouse: "購入したコース",
    discount: "割引コード",
    codeActivations: "コードの有効化",
    becomeATutor: "メンターになる",
  },
  aboutUs: {
    aboutUs: "私たちについて",
    termofus: "利用規約",
    privacy: "プライバシーポリシー",
    cookie: "Cookieポリシー",
    return: "返品ポリシー",
    deleteacount: "アカウントを削除",
  },
  call: {
    mutedAll: "全員のミュート",
    unMutedAll: "ミュート解除",
    inComingCall: "着信中の通話...",
    titleCamera: "カメラへのアクセスが必要です",
    messageCamera:
      "他の人に電話をかけるためには、カメラへのアクセスが必要です。",
    titleMic: "マイクロフォンへのアクセスが必要です",
    messageMic:
      "他の人に電話をかけるためには、マイクロフォンへのアクセスが必要です。",
  },
  listCategory: {
    course: "コース",
    tutor: "専門家",
    club: "クラブ",
    affiliate: "アフィリエイト",
    descriptionTitle: "機能を探索",
  },
  recommendCourse: "おすすめコース",
  ieltsHunterLive: "IKIGAI Coach Live",
  nameTutor: (name: string) => `${name}のコース`,
  titleLive: "Nguyễn Trung KiênのIELTSライティングクラス",
  titleName: "IELTS Listening [MASTERCLASS]: 2024年にBand 7+を達成",
  best: "ベストセラー",
  ratings: "2.3K レーティング",
  buy: "購入",
  pin: "ピン",
  unPin: "ピンを解除",
  priceNew: "1,500,000đ",
  priceOld: "5,000,000đ",
  selectCategory: "カテゴリを選択",
  selectImage1: "画像",
  selectVideo: "ビデオ",
  selectLive: "ライブビデオ",
  selectFile: "ファイルを選択",
  en: "英語",
  vi: "ベトナム語",
  jp: "日本語",
  leaderBoard: "リーダーボード",
  inprogress: "進行中",
  complete: "完了",
  signOut: "サインアウト",
  gotIt: "了解",
  task: {
    inviteFriend: "友達を招待",
    yourscore: "IKIgaiの意味",
    powered: "サポートされた",
    mycode: "私のコード",
    level: "レベル",
    task: "タスク",
    score: "スコア",
    listening: "リスニング",
    speaking: "スピーキング",
    reading: "リーディング",
    writing: "ライティング",
    missions: "ミッション",
    get: "取得",
    complete: "完了",
    notComplete: "未完了",
  },
  homework: {
    header: "宿題リスト",
    assignment: "割り当て",
    assign: "割り当て",
    addClassCmt: "コメントを追加",
    detailTask: "宿題の詳細",
    classCmt: "コメント",
    yourWork: "あなたの宿題",
    addWork: "作業を追加",
    handedIn: "提出済み",
    unsubmit: "未提出",
    unsubmitDes:
      "添付ファイルを追加または変更するために提出をキャンセルしてください。完了したら再提出してください。",
    removeAtt: "添付ファイルを削除しますか？",
    removeAttDes: "添付ファイルを削除してもよろしいですか？",
    handInYourWork: "作業を提出しますか？",
    handInYourWorkDes: (text) => text + "添付ファイルを送信しますか？",
    privateCmt: "プライベートコメント",
    privateCmtDes: "プライベートコメントを追加",
    intructions: "指示",
    studentWork: "学生の作業",
    assigned: "割り当て済み",
    marked: "評価済み",
    acceptSub: "提出を承認",
    assignTitle: "割り当てタイトル",
    description: "説明",
    attachment: "添付ファイル",
    score: "スコア",
    mark: "点数を入力",
    points: "ポイント",
    dueDate: "締切日",
    topic: "トピック",
    createWork: "作業を作成",
    selectClass: "クラスを選択",
    selectDouDate: "締切日を選択",
    createTaskSuccess: "タスクの作成に成功しました",
    deleteTaskSuccess: "タスクの削除に成功しました",
    updateTaskSuccess: "タスクの更新に成功しました",
    handedInSuccess: "提出が成功しました",
    markError: "点数は数値で100以下でなければなりません",
    forYou: "あなたのために",
    following: "フォロー中",
    trending: "流行っている",
    mostPopular: "最も人気がある",
    emptyTask: "宿題はありません",
  },
  introwelcome: {
    text11: "あなたの人生の旅を向上させる",
    text12:
      "個人成長、心理学、生活スキルのコースで変革の旅を始めましょう。自分自身の力を信じて成長する",
    text21: "キャリアの可能性を開放する",
    text22:
      "キャリアに焦点を当てた多くのコースがここにあります。専門的な成長と成功へのあなたの扉",
    text31: "あなたの財務の未来をコントロール",
    text32:
      "財務の秘密を開放するコース。予算、投資、財務計画に関する専門家によるガイダンスで財務をコントロールし、安全な未来を築き上げる",
    text41: "ビジネス成功を開放する",
    text42:
      "起業、マーケティング、管理に関するコースを探索してください。ビジネスの世界でスキルを向上させ、成長する",
    text51: "どこでもいつでも健康をケアする",
    text52:
      "IKIGAI Coachでトップの健康コースを探索してください。あなた自身の健康を管理し、自己成長を促進する場所",
  },
  discover: {
    study: "学習",
    dictionary: "辞書",
    shop: "ショップ",
    finduser: "ユーザーを検索",
    findTutor: "専門家を検索",
    coins: "コイン",
    level: "レベル",
    leaderboard: "リーダーボード",
    poits: "ポイント",
    feature: "特長",
    ieltsPractice: "IELTS練習",
  },
  gamificaiton: {
    youEarn: "あなたが獲得する",
    collectPoint: "ポイントを集める",
    levelUp: "レベルアップ！",
    levelUpDes:
      "ミッションを完了し、スキルを向上させてポイントとレベルを上げます。",
  },
  affiliate: {
    currentlyAvailable: "現在利用可能",
    shareCode: "コードを共有",
    saleNow: "今すぐ販売",
    saleCourse: "販売", // Hanbai
    aff: "収益", // Shūeki
    moneyOut: "引き出し", // Hikidashi
    referal: "紹介者", // Shōkaisha
    yourIncome: "あなたの収入",
    withdraw: "引き出し",
    today: "今日",
    thisMonth: "今月",
    lastMonth: "先月",
    date: "日付",
    product: "製品",
    user: "ユーザー",
    customer: "顧客",
    emptyTransaction: "トランザクションリストは空です",
    fromDate: "開始日",
    toDate: "終了日",
    commission: "レヴェヌア",
    commissionSale: "販売手数料: 20%",
    desCommission:
      "あなたが紹介したユーザーがコースを購入すると、コースの20%の手数料を受け取ります。例えば、コースの価格が10,000,000 VNDの場合、ユーザーがコースを成功裏に購入すると2,000,000 VNDを受け取ります！",
    referalCommission: "紹介手数料: 5%",
    desRef:
      "あなたが共同作業者を紹介すると、共同作業者のお客様が購入を成功させた場合、注文金額の5%に相当する報酬を受け取ります。",
    noTransaction: "トランザクションは発生していません",
    // description: "紹介されたメンバーが購入すると、報酬が発生します(",
    description:
      "あなたの紹介コードを入力した紹介者は、各注文で売上の20％に相当するコミッションを受け取ります。さらに、最大5％の紹介コミッションを受け取るチャンスもあります。",
    description2: "% 報酬",
    description3:
      "). 例: 価格が1,000,000ドンのコースを紹介すると、報酬は80,000ドン → 80 ",
    whyJoin: "なぜアフィリエイトに参加するのか？",
    text1: "IKIGAI COACH と一緒に販売して収入を増やしましょう",
    text2: "お客様がコースを購入するとすぐにお金が入金されます",
    text3: "リアルタイムで収益を管理",
    text4: "銀行口座に引き出し",
    totalAmount: "合計金額",
    totalCoin: "合計コイン",
    emptyProduct: "製品リストは空です",
    emptyUser: "ユーザーリストは空です",
    filter: "フィルターする",
    money: "お金",
  },
  emptyList: "リストは空です",
  emptyCalendar: "空のカレンダー",
  withDraw: {
    header: "出金",
    your_money: "あなたの金額",
    withdraw_amount: "出金金額",
    min_withdraw_des: "最低出金額は100,000đ",
    bank_des: "出金時間制限なし",
    add_bank: "銀行を追加",
    bank_title: "銀行口座",
    card_number: "カード/口座番号",
    card_number_placeholder: "カード/口座番号を入力",
    card_name: "カード所有者の名前を入力",
    card_number_error: "カード番号は4から14文字でなければなりません",
    search_bank: "銀行を検索",
    choose_bank: "銀行を選択",
    bank_acc: "銀行口座",
    addBankSuccess: "銀行カードの追加に成功",
    addBankFaild: "銀行カードの追加に失敗または既に存在します",
    withDrawSuccess: "出金依頼が成功しました",
    withDrawFaild: "出金依頼に失敗しました",
  },
  referrals: {
    yourReferral: "紹介者",
    viewProfile: "プロフィールを見る",
  },
  ieltsPractice: {
    praticeTest: "模擬テスト",
    writing: "ライティング",
    listening: "リスニング",
    reading: "リーディング",
    speaking: "スピーキング",
    answers: "答え",
    questions: "質問",
    submitSucces: "提出成功",
    desSubmitSuccess: "結果は5-10分後に表示されます",
    submit: "提出",
    timeout: "時間切れ！",
    hidePassage: "パッセージを隠す",
    showPassage: "パッセージを表示",
    waittingResult: "結果待ち",
    emptyPraticeTest: "模擬テストリストは空です",
  },
  club: {
    memberToAdmin: "管理者権限を付与",
    adminToMember: "管理者権限を取り消す",
    toAdminSuccess: "管理者権限付与に成功",
    toAdminFaild: "管理者権限付与に失敗、後で再試行",
    toMemberSuccess: "管理者権限取り消しに成功",
    addMember: "メンバーを追加",
    toMemberFaild: "管理者権限取り消しに失敗、後で再試行",
    deleteMember: (name: string) => `${name}をクラブから削除`,
    deleteMemberSuccess: (name: string) => `${name}をクラブから削除しました`,
    deleteMemberFaild: "削除に失敗、後で再試行",
    emptyClub: "クラブリストは空です",
    addCover: "カバー画像を追加",
    leaveGroup: "クラブを退出",
    warningLeave: "このクラブから本当に退出しますか？",
    sendEliteClub:
      "クラブへの参加リクエストを送信しました。クラブのオーナーからの承認をお待ちください。",
    file: "ファイル/画像",
    event: "イベント",
    course: "コース",
    addImage: "画像を追加",
    member: "メンバー",
    admin: "管理者",
    leader: "リーダー",
    infoClubError: "クラブ情報を取得できませんでした、後で再試行",
    joinClubFalid: "クラブ参加に失敗、後で再試行",
    clubName: "クラブ名",
    nameYourClub: "あなたのクラブ名",
    chooseYourClubPrice: "クラブ参加料を選択",
    writeSomethingClub: "クラブの説明を入力",
    clubPrice: "クラブ参加料",
    description: "説明",
    createClub: "クラブを作成",
    createClubSuccess: "クラブ作成に成功",
    createClubFaild: "クラブ作成に失敗、後で再試行",
    updateClub: "クラブを更新",
    updateClubSuccess: "クラブ更新に成功",
    updateClubFaild: "クラブ更新に失敗、後で再試行",
    warningSelectImage: "カバー画像を選択していません",
    warningSelectType: "クラブの種類を選択していません",
    clubOfTyoe: "クラブの種類",
    club: "クラブ",
    title1: "人気のクラブ",
    title2: "管理しているクラブ",
    title3: "参加したクラブ",
    create: "新規作成",
    sortBy: "クラブをソート",
    mostVisited: "最も訪れられた",
    clubs: "クラブA-Z",
    join: "最近参加",
    attended: "参加",
    attended2: "参加",
    ago: "前",
    purchaseJoin: "クラブ参加のための購入",
    about: "情報",
    seeMore: "さらに表示",
    history: "履歴",
    title: "クラブリーダーと管理者",
    group: "クラブ活動",
    newPosts: "今日の新しい投稿",
    members: "メンバー",
    joinGruop: "クラブに参加",
    inCome: "先週参加",
    created: "作成された",
    tab1: "人気",
    tab2: "あなたの",
    tab3: "参加済み",
    des1: "クラブは",
    des2: "に最後に名前が変更されました",
    des3: "と",
    des4: "他のメンバーが管理者です。",
    createAt: (create: string, update: string) =>
      create !== update
        ? `クラブは${create}に作成されました。最後の名前変更は${update}に行われました。`
        : `クラブは${create}に作成されました。`,
    desLeader: "はリーダーです",
    desAdmin: (member: number) =>
      member > 0 ? `と${member}人の他のメンバーが管理者です。` : "。",
    createEvent: "イベントを作成",
    gallery: "選択",
    createEvent2: "イベントを作成",
    eventName: "イベント名",
    startDate: "開始日",
    endDate: "終了日",
    location: "場所",
    chooseStartDate: "開始日を選択",
    chooseEndDate: "終了日を選択",
    enterLocation: "場所を入力",
    featureMember: "注目のメンバー",
    imageClub: "画像リスト",
    becomeElite: "Eliteクラブのメンバーになる",
    benefitsJoin: "Eliteクラブに参加すると以下の特典があります",
    desBenefit1: "年に1回のヒーリングツアー参加",
    desBenefit2: "トップ専門家との39時間の1対1コーチング",
    desBenefit3: "トップクラスの人々とのコミュニティ参加",
    priceJoin: "参加費: 39,000,000đ",
    enterInfo: "以下の情報を入力してください",
    business: "ビジネス",
    address: "住所",
    currentAssets: "現在の資産",
    fullName: "氏名",
    phoneNumber: "電話番号",
    profession: "職業",
    position: "役職",
    submit: "送信",
    settingClub: "クラブ設定",
    namAndDes: "クラブ名と説明",
    deleteGroup: "クラブを削除",
    deleteGroupSuccess: "クラブ削除に成功",
    sendRequest: "情報送信に成功",
  },
  close: "閉じる",
  setup: {
    title1: "興味を持っている1つまたは複数のトピックを選択してください。",
    life: "生活",
    business: "ビジネス",
    finance: "ファイナンス",
    orientation: "オリエンテーション",
    health: "健康",
    charity: "チャリティ",
    title2: "IKIGAI Coachをどのように使用したいですか？",
    des: "規制上の理由と、私たちが好奇心から知りたいからです！",
    lifeCoaching: "ライフコーチング",
    personalDevelopment: "個人的成長",
    goalSetting: "目標設定",
    timeMana: "時間管理",
    stressMana: "ストレス管理",
    healthAndWell: "健康とウェルネス",
    nutri: "栄養とダイエット",
    fitness: "フィットネスと運動",
    mental: "メンタルヘルス",
    sleep: "睡眠改善",
    businessCare: "ビジネスとキャリア",
    businessCoa: "ビジネスコーチング",
    careerDeve: "キャリア開発",
    entre: "起業",
    leaderSkill: "リーダーシップスキル",
    workLife: "ワークライフバランス",
    title3: "IKIGAI Coachに来た理由は何ですか？",
    seeking: "バランスを求める",
    expl: "目的を探求する",
    needing: "サポートが必要",
    goal: "目標設定",
    other: "その他",
    errorChoose: "一つ以上のオプションを選択してください！",
  },
  validateTime: "スケジュール時間は現在の時間よりも後でなければなりません！",
  updateLivestream: {
    deleteSuccess: "ライブストリームのスケジュールを正常に削除しました",
    confirmDelete: "このライブストリームのスケジュールを削除しますか？",
    orderLive: "ライブストリームを注文する",
    makePlan: "スケジュールを作成する",
    makePlanSuccess: "スケジュールが正常に作成されました",
    happenning: "進行中",
    list: "ライブストリーム一覧",
    planDes: "放送スケジュールはホームページに表示されます",
  },
  manageCertificate: {
    title: "証明書管理",
    des: "あなたの証明書はホームページに表示されます",
    addCertificate: "証明書を追加",
    addCertificateSuccess: "証明書が正常に追加されました",
    deleteCertificate: "証明書を削除",
    confirmDeleteCertificate: "この証明書を削除しますか？",
    deleteCertificateSuccess: "証明書が正常に削除されました",
    editCertificate: "証明書を編集",
    editCertificateSuccess: "証明書が正常に編集されました",
    certificate: "証明書",
    desCertificate: "証明書の説明",
    chooseImageCertificate: "証明書の画像を選択",
    chooseImageCertificateError: "証明書の画像を選択してください",
    chooseCertificate: "証明書を選択",
    chooseCertificateSuccess: "証明書が正常に選択されました",
    chooseCertificateError: "証明書を選択してください",
    chooseCertificateDes: "証明書の説明を選択してください",
    issuedBy: "発行者",
    year: "学年",
    description: "説明",
  },
  subscription: {
    title: "サブスクリプションサービス",
    des: "サブスクリプションサービスはホームページに表示されます",
    addSubscription: "サブスクリプションサービスを追加",
    addSubscriptionSuccess: "サブスクリプションサービスの追加に成功しました",
    deleteSubscription: "サブスクリプションサービスを削除",
    confirmDeleteSubscription: "このサブスクリプションサービスを削除しますか？",
    deleteSubscriptionSuccess: "サブスクリプションサービスの削除に成功しました",
    editSubscription: "サブスクリプションサービスを編集",
    editSubscriptionSuccess: "サブスクリプションサービスの編集に成功しました",
    description:
      "アップロードされたポッドキャストのコンテンツから追加収入を得る",
  },
  label: "タイトル",
  description: "説明",
  premiumAccount: {
    freeTrial: "3日間の無料試用",
    day: "日",
    month: "月",
    months: "ヶ月",
    year: "年",
    save: "保存",
    getIt: "プレミアムへ行く",
    noThanks: "いいえ、結構です",
    des1: "自動更新はいつでもキャンセルできます",
    des2IOS:
      "サブスクリプションはiTunesアカウントを通じて課金されます。現在のサブスクリプション期間が終了する24時間前にキャンセルしない限り、サブスクリプションは自動的に更新されます。メンバーシップを取得することは、以下の条件と契約に同意することを意味します。",
    des2Android:
      "サブスクリプションはGoogle Playアカウントを通じて課金されます。現在のサブスクリプション期間が終了する24時間前にキャンセルしない限り、サブスクリプションは自動的に更新されます。メンバーシップを取得することは、以下の条件と契約に同意することを意味します。",
    des3: "付加価値サービス規約、Ikigai Coach プライバシーポリシー、自動更新サブスクリプションの規約",
    error: "エラー",
    getServiceFail: "サービス取得に失敗しました",
    whiteGPro: "プレミアム",
    proDes:
      "プレミアムにアップグレードして、あなたを気に入っている人を見たり、トラベルモードを有効にしたり、無制限のメッセージ返信や通話を利用しましょう！",
    getPro: "プレミアムを取得",
    unlimitedViewUser: "ホームページでユーザーを無制限に閲覧",
    fullVisitorList: "完全な訪問者リスト",
    unlimitedChangeLocation: "場所の無制限変更",
    call30minutes: "チャットルームごとに30分間の無料通話",
    fullFollowList: "完全なフォローリスト",
    unlimitedReplyMessage: "無制限のメッセージ返信",
    advanceFilter:
      "ユーザーの詳細フィルター（役割、距離、体型、オンライン時間）",
    fullFilter: "ユーザーの完全フィルター",
    spotLight: "チャットリスト、ホームページでスポットライト",
    proFunction: "プレミアム機能",
    upgrade: "アップグレード",
    startDate: "開始日: ",
    endDate: "終了日: ",
    unlimitedCall: "無制限の通話",
    endsIn: "終了まで",
    only: "のみ",
    promotionLeft: "残りのプロモーション - 取得",
    rightNow: "今すぐオフ！",
    days: "日",
    weeks: "週間",
    week: "週間",
    listServiceEmpty: "サービスリストが空です",
    free: "無料",
    trial: "試用",
    then: "次に",
    from: "から",
    subscribe: "サブスクライブ",
    start: "開始",
  },
  creator: "コンテンツクリエーター",
  loadingRoom: "教室に入っています",
  leaving: (v) => v + " は部屋を去りました",
};
