/* eslint-disable max-len */

export default {
  detail: "Chi tiết",
  setting: "Cài đặt",
  openSetting: "Mở cài đặt",
  language: "Ngôn ngữ",
  darkMode: "Chế độ tối",
  switchLanguage: "Đổi ngôn ngữ",
  approve: "Đồng ý",
  cancel: "Huỷ",
  placeholderEmaiPhone: "Email/Số điện thoại",
  placeholderEmail: "Email",
  placeholderVerifyCode: "Mã xác thực",
  placeholderPasword: "Mật khẩu",
  forgotPassword: "Quên mật khẩu",
  verifyCodeTitle: (text: string) =>
    `Nhập mã xác thực nhận được từ email ${text}`,
  signIn: "Đăng nhặp",
  signUp: "Đăng ký",
  signInWith: "Đăng nhập với",
  continue: "Tiếp tục",
  continueWith: (text: string) => `Tiếp tục với ${text}`,
  enterNewPassword: "Nhập mật khẩu mới",
  confirmPassword: "Xác nhận mật khẩu",
  enterOTP: "Nhập mã otp",
  updatePassword: "Cập nhật mật khẩu",
  save: "Lưu",
  required: "Ô nhập không được để trống",
  invalid: "Không hợp lệ",
  or: "Hoặc",
  welcomeBack: "Mừng bạn trở lại",
  minLength: (number: number) => `tối thiểu ${number} ký tự`,
  needAnAccount: "Cần một tài khoản? ",
  registerNow: "Đăng ký!",
  createNewAccount: "Tạo tài khoản",
  fullname: "Họ và tên",
  haveAnAccount: "Đã có tài khoản? ",
  loginNow: "Đăng nhập ngay!",
  welcomeHeader: "Chào mừng đến với thế giới ngôn ngữ",
  welcomeDescription: "Học tập không bao giờ là dễ dàng, với IELTS bạn sẽ ..",
  startNow: "Bắt đầu",
  createPassSuccess: "Tạo mật khẩu mới thành công!",
  loginSuccess: "Đăng nhập thành công!",
  error: {
    unknown: "Có lỗi không xác định xảy ra!",
    invalidPhoneEmail: "SĐT/Email không hợp lệ",
    invalidEmail: "Email không hợp lệ",
    invalidPhone: "Phone không hợp lệ",
    invalidLink: "Link không hợp lệ",
    invalidYoutube: "Kênh youtube không hợp lệ",
    invalidFacebook: "Link Youtube không hợp lệ",
    minLengthPass: "Mật khẩu phải ít nhất 6 kí tự",
    passDoesNotMatch: "Mật khẩu xác nhận không trùng khớp",
    errorPatternPass:
      "Mật khẩu gồm ít nhất 8 kí tự ký tự có chữ cái, số và kí tự đặc biệt, viết thường và viết hoa",
    isOffline: "Kết nối với internet và thử lại",
  },
  channelLocked: "Kênh tạm thời đang bị khoá",
  channelLockedDes: "Truy cập vào website kích hoạt kênh",
  create_Channel: "Tạo Kênh",
  unblock: "Mở khóa",
  unblockDes: "Bạn có muốn mở khoá cho :username",
  cancel: "Hủy",
  postCategory: "Chuyên mục",
  createPost: "Tạo bài viết",
  placeholderContent: "Nội dung",
  channelLocked: "Kênh tạm thời đang bị khoá",
  channelLockedDes: "Truy cập vào website kích hoạt kênh",
  unblock: "Mở khóa",
  unblockDes: "Bạn có muốn mở khoá cho :username",
  confirm: "Xác nhận",
  somethingWentWrong: "Hệ thống xảy ra lỗi. Vui lòng thử lại sau.",
  notFound: "Danh sách trống",
  offlineNetwork: "Mất kết nối mạng",
  onlineNetwork: "Mạng dữ liệu đã được kết nối lại",
  all: "Tất cả",
  goToWeb: "Bạn có muốn truy cập vào website để xem chi tiết?",
  orderDetail: "Thông tin chi tiết",
  loadingLogin: "Đang tham gia ...",
  seconds: "giây",
  minutes: "phút",
  hours: "giờ",
  days: "ngày",
  weeks: "tuần",
  months: "tháng",
  years: "năm",
  ago: "trước",
  copied: "Đã sao chép",
  thankyouForReport:
    "Báo cáo thành công, chúng tôi sẽ xem xét và xử lý vi phạm!",
  copy: "Sao chép",
  report: "Báo cáo",
  block: "Chặn",
  blockedDes: "Các bạn sẽ không thể nhìn thấy hoặc liên hệ với nhau",
  blockedUser: "Bạn đã chặn trang cá nhân của :username",
  commentAs: "Bình luận dưới tên",
  replying: "Phản hồi",
  reply: "phản hồi",
  like: "thích",
  comment: "bình luận",
  delete: "Xóa",
  edit: "Chỉnh sửa",
  duplicate: "Nhân bản",
  copyLink: "Sao chép liên kết",
  pinToTop: "Ghim lên đầu",
  turnOfComments: "Tắt bình luận",
  turnOnComments: "Bật bình luận",
  deleteSuccess: "Xóa thành công",
  updateSuccess: "Cập nhật thành công",
  pinned: "Đã ghim",
  loadingMore: "Đang tải thêm",
  hide: "Gỡ",
  online: "Online",
  offline: "Offline",
  status: "Chi tiết",
  joined: "Đã tham gia",
  bio: "Thông tin",
  contributions: "Đóng góp",
  follower: "Người theo dõi",
  following: "Đang theo dõi",
  follow: "Theo dõi",
  unfollow: "Bỏ theo dõi",
  followed: "Đã theo dõi",
  message: "Nhắn tin",
  filter: "Lọc",
  sort: "Sắp xếp",
  save: "Lưu",
  search: "Tìm kiếm...",
  notInGroup: "Bạn đang không ở trong nhóm nào",
  createChannel: "Bạn có thể tạo hệ thống theo những bước sau",
  notInGroup: "Bạn đang không ở trong nhóm nào",
  createChannelDes: "Bạn có thể tạo hệ thống theo những bước sau",
  joinViaInvite:
    "Bạn có thể gửi email đến chủ hệ thống vì họ có thể mời bạn tham gia.",
  deleteConfirm: "Bạn có chắc chắn muốn xóa không?",
  update: "Cập nhật",
  viewAll: "Xem tất cả",
  aboutMe: "Về tôi",
  today: "Hôm nay",
  yesterday: "Hôm qua",
  tomorrow: "ngày mai",
  from: "Từ",
  to: "Đến",
  continue: "Tiếp tục",
  justNow: "Vừa xong",
  openFile: "Xem file",
  openFileDes: "Bạn có muốn mở file bằng trình duyệt không?",
  active: "Hoạt động",
  updateAvailable: "Có bản cập nhật mới",
  updateAvailableDes: "Đã có bản cập nhật mới trên App Store. Tải xuống?",
  seemore: "...Xem thêm",
  selectImage: "Chọn ảnh",
  draft: "Bản nháp",
  public: "Công khai",
  private: "Riêng tư",
  add: "Thêm mới",
  cancelEdit: "Xác nhận hủy",
  cancelEditDes: "Các chỉnh sửa sẽ không được lưu lại. Bạn có muốn tiếp tục?",
  clear: "Xoá tất cả",
  searchForKey: "Kết quả cho từ khoá: ",
  viewMore: "Xem chi tiết",
  role: "Vai trò",
  free: "Miễn phí",
  level: "Cấp độ",
  post: {
    post: "Đăng",
    posts: "Bài viết",
    createPost: "Tạo bài viết",
    category: "Chuyên mục",
    title: "Tiêu đề",
    content: "Nội dung",
    poll: "Bình chọn",
    removePoll: "Xóa Bình chọn",
    addOption: "Thêm lựa chọn",
    addVideo: "Thêm Video",
    addVideoDes: "Thêm liên kết Youtube, Vimeo or Wistia.",
    link: "Liên kết",
    pleaseInputTitleOrContent: "Vui lòng thêm nội dung",
    pleaseSelectCategory: "Vui lòng chọn chuyên mục",
    pollMinLength: "Cuộc bình chọn cần ít nhất 2 câu trả lời",
    createPostSuccess: "Đăng bài thành công",
    like: "Thích",
    liked: "Đã thích",
    share: "Chia sẻ",
    comment: "Bình luận",
    comments: "bình luận",
    likeThisPost: "lượt thích",
    personLiked: "Những người thích bài viết này",
    emptyComment: "Hãy là người đầu tiên bình luận",
    emptyCommentDes:
      "Hãy gửi ý kiến ​​của bạn cho bài viết này nhé! Vui lòng tuân thủ các nguyên tắc cộng đồng khi tham gia thảo luận tại IELTS Hunter.",
    emptyPost: "Chưa có bài viết nào",
    postInvalid: "Bài đăng không tồn tại",
    emptyPostTitle: "Không có bài viết",
    emptyPostDes:
      "Khi một người bạn hoặc giáo viên đăng một bài viết, nó sẽ xuất hiện ở đây và sau đó bạn có thể thích, chia sẻ và bình luận về bài đăng đó.",
    report: "Báo cáo bài viết",
    save: "Lưu bài viết",
    likeError: "Gửi lượt thích thất bại vui lòng thử lại!",
    savePostSuccess: "Lưu bài viết thành công",
    listPostSave: "Bài viết đã lưu",
    deleteFromSave: "Xoá khỏi danh sách đã lưu",
    emptyListSave: "Danh sách bài viết đã lưu trống",
  },
  navigation: {
    dashboard: "Trang chủ",
    courses: "Khóa học",
    leaderboards: "Xếp hạng",
    notifications: "Thông báo",
    menu: "Menu",
    messages: "Tin nhắn",
    event: "Sự kiện",
    challenge: "Thử thách",
    gift: "Quà tặng",
    podcast: "Podcast",
    mission: "Nhiệm vụ",
    notificationDes:
      "Khi bạn bỏ chọn thông báo thì biểu tượng thông báo sẽ xuất hiện tại trang chủ",
  },
  switchGroups: "Chuyển hệ thống",
  createGroup: "Tạo hệ thống",
  login: {
    continueFacebook: "Tiếp tục với Facebook",
    continueGoogle: "Tiếp tục với Google",
    continueApple: "Tiếp tục với Apple",
    email: "Email",
    emailPhone: "Email / Số điện thoại",
    fullname: "Tên đầy đủ",
    description: "Mô tả",
    password: "Mật khẩu",
    signin: "Đăng nhập",
    signup: "Đăng ký",
    signinWithPassword: "Đăng nhập với mật khẩu",
    dontHaveAccount: "Bạn chưa có tài khoản?",
    or: "Hoặc",
    orContinueWith: "Hoặc tiếp tục với",
    descriptionSignin: "Ấn đăng nhập nghĩa là bạn đồng ý với ",
    descriptionSignup: "Ấn đăng ký nghĩa là bạn đồng ý với ",
    termConditions: "Điều khoản & Điều kiện",
    privacyPolicy: "Chính sách",
    and: " và ",
    our: "",
    alreadyHaveAccount: "Bạn vừa tạo tài khoản?",
    letYouIn: "Hãy đăng nhập",
    createYourAccount: "Tạo tài khoản",
    loginError: "Lỗi đăng nhập, vui lòng thử lại!",
    registerSuccess: "Đăng ký thành công",
    forgotPassword: "Quên mật khẩu",
    send: "Gửi",
    forgotPasswordSuccess:
      "Gửi email thành công, vui lòng kiểm tra email của bạn!",
    requireLogin: "Bạn cần đăng nhập để sử dựng chức năng này",
  },
  validate: {
    emailInvalid: "Email không tồn tại",
    emailPhoneInvalid: "Email / Số điện thoại không tồn tại",
    requiredEmail: "Vui lòng điền email hoặc số điện thoại",
    requiredPassword: "Vui lòng điền mật khẩu",
    requiredFullName: "Vui lòng điền tên đầy đủ",
    errorOldPassword: "Vui lòng điền mật khẩu cũ",
    errorNewPassword: "Vui lòng điền mật khẩu mới",
    errorConfirmPasswordNotMatch: "Mật khẩu không đúng",
    errorConfirmPassword: "Vui lòng xác nhận mật khẩu",
    requiredDate: "Vui lòng điền ngày",
    requiredName: "Vui lòng điền tên",
    requiredTime: "Vui lòng điền thời gian",
    requiredDuration: "Vui lòng điền thời lượng",
    requiredLocation: "Vui lòng điền địa điểm",
    requiredAttend: "Vui lòng điền Người tham dự",
    requiredLink: "Vui lòng điền liên kết",
    requiredDayOfWeeks: "Vui lòng điền thứ",
    requiredOccurrences: "Vui lòng điền sự kiện",
    numberOccurrences: "Sự kiện phải điền bằng số",
    invalidInput: "Thông tin không hợp lệ",
    requiredDescription: "Vui lòng điền mô tả",
    requiredLevel: "Vui lòng chọn cấp độ",
    requiredCourse: "Vui lòng chọn khoá học",
    pointBetween: "Số điểm phải lớn hơn :min",
    percentBetween: "Số % phải lớn hơn :min và nhỏ hơn",
    requiredPhoneNumber: "Vui lòng điền số điện thoại",
    phoneNumberInvalid: "Số điện thoại không đúng định dạng",
    requrireValue: "Vui lòng điền giá trị",
    numberInvalid: "Vui lòng điền số",
    requireQuantity: "Vui lòng điền số lượng",
    requirePoint: "Vui lòng điền số điểm",
    requireAvatar: "Vui lòng chọn ảnh",
    requiredUser: "Vui lòng điền số lượng",
    requiredContent: "Vui lòng điền nội dung",
    errorCommission:
      "Hoa hồng của người dùng không được vượt quá hoa hồng của mentor",
    numberOfDayInvalid:
      "Số ngày diễn ra vui lòng nằm trong khoảng từ 1-10 ngày",
    requireMission: "Vui lòng chọn nhiệm vụ",
    requireCountMission: "Vui lòng nhập số lượng nhiệm vụ",
    requirePhone: "Vui lòng điền số điện thoại",
    invalidUsernamePassword:
      "Thông tin đăng nhập không chính xác. Vui lòng thử lại!",
    passwordInvalid:
      "Mật khẩu phải bao gồm chữ viết hoa, chữ thường, số và ký tự đặc biệt!",
    maxUserInvalid: "Số lượng người phải lớn hơn 1 và nhỏ hơn 100.000.000",
    urlInvalid: "Đường dẫn không hợp lệ",
    requiredEmailEdit: "Vui lòng điền email",
  },
  home: {
    whatonYourMind: "Bạn đang nghĩ gì?",
    dontHasPermissionToCreate: "Bạn không thể tạo bài viết mới",
    commentSuccess: "Bình luận thành công",
    typeComment: "Điền bình luận...",
    recentActivity: "Bài viết gần đây",
    mostPopular: "Bài viết nổi bật",
    mostLike: "Bài viết nhiều lượt thích",
    trending: "Xu hướng",
    beFirstComment: "Trở thành người đầu tiên bình luận",
    dailyMission: "Nhiệm vụ hàng ngày",
    doMissionNow: "Thực hiện ngay",
    times: "lần",
    image: "Ảnh",
    file: "Tài liệu",
    poll: "Bình chọn",
    checkinForGift: "Báo danh nhận quà",
    checkinSuggest: "Bạn có một rương chưa mở",
    checkinCallToAction: "Mở rương ngay",
    select: "Xong",
    maximunImage: "Chọn tối đa :count ảnh",
    emptyList: "Danh sách bài viết trống",
    noNewPost: "Không còn bài viết mới",
    deleteImage: "Xoá tất cả ảnh ",
    moreComment: "Xem thêm...",
    sending: "Đang gửi...",
    sendingError: "Có lỗi xảy ra!",
    resend: "Gửi lại",
    shortcuts: "Lối tắt",
    remarkable: "Đáng chú ý",
    viewMore: "Xem thêm",
    deletePost: "Bạn có muốn xoá bài viết này?",
    deleteComment: "Bạn muốn xoá bình luận",
    postNeedApproval: "{post} bài viết cần phê duyệt",
    postApproval: "Duyệt bài viết",
    approval: "Duyệt",
    postPending: "{post} bài viết đang chờ duyệt",
    notificationPostPending:
      "Đăng bài thành công, bài viết cần chờ chủ kênh duyệt!",
    approvalSuccess: "Duyệt bài viết thành công",
    deletePostSuccess: "Xoá bài viết thành công",
  },
  dailyChest: {
    openGuide: "NHẤN MỞ RƯƠNG\nđể khám phá phần thưởng",
    guideGoldChest: "RƯƠNG VÀNG dành cho sự kiện đặc biệt",
    guideSilverChest:
      "Bạn sẽ nhận một lượt mở RƯƠNG BẠC mỗi ngày khi đăng nhập",
    guideBronzeChest: "Bạn sẽ nhận một lượt mở RƯƠNG ĐỒNG mỗi 5 PHÚT",
    countChest: "Bạn còn $qyt lượt mở",
    receive: "Nhận ngay",
    countdownBronzeChest: "Còn $time để mở rương",
  },
  chat: {
    search: "Tìm kiếm",
    cancel: "Hủy",
    weHaveRemovedErrorPhoto: "Hệ thống xóa tệp lỗi và video dài hơn 1 phút",
    sendYourAudioMessage: "Gửi tin nhắn âm thanh của bạn",
    releaseToSend:
      "Nhả để gửi, chuyển sang bên phải để sử dụng chế độ rảnh tay",
    holdToRecord: "Giữ để ghi âm",
    permissionToRecord:
      "Cần có quyền ghi, ghi dữ liệu và truy cập thư viện để sử dụng chức năng này",
    grandPermission: "Cấp quyền",
    noPeopleFound: "Hiện tại kênh này chưa có ai để có thể trò chuyện",
    emptyListChat:
      "Bạn chưa từng nói chuyện với ai. Hãy thử bắt đầu cuộc trò chuyện với",
    imageError: "Phát hiện ảnh lỗi. Vui lòng thử lại",
    typeMessage: "Nhập tin nhắn...",
    lastSeen: "Lần cuối xem: ",
  },
  keyboard: {
    writeSomething: "Nhập tin nhắn",
  },
  common: {
    yrs: "năm",
    hrs: "giờ",
    mins: "phút",
    secs: "giây",
    seconds: "giây",
    minutes: "phút",
    hours: "giờ",
    days: "ngày",
    months: "tháng",
    years: "năm",
    at: "lúc",
  },
  course: {
    prepareCourse: "Các khóa học này đang được biên soạn!",
    suggestPickCourse: "Lựa chọn khóa học phù hợp với bạn phía dưới !",
    slogan: "Giáo dục là sức mạnh!",
    course: "Khóa học",
    courseMine: "Khóa học của tôi",
    coursePrice: "Khóa học nâng cao",
    courseFree: "Khóa học cơ bản",
    newCourse: "Khóa học mới",
    createCourse: "Tạo khoá học",
    updateCourse: "Cập nhật khóa học",
    uploadCoverImageOrVideo: "Tải lên ảnh nền hoặc video",
    uploadCoverImage: "Tải lên ảnh nền",
    addCourse: "Thêm khóa học",
    courseName: "Tên khóa học",
    courseDescription: "Mô tả khóa học",
    courseLongDescription: "Chi tiết khoá học",
    whoCanAccessThisCourse: "Thành viên có thể truy cập khóa học",
    publish: "Công khai",
    videoTooLong: "Vui lòng chọn một video ngắn hơn 5 giây",
    pleaseFillInformation: "Vui lòng điền thông tin",
    createCourseSuccess: "Tạo khoá học thành công",
    open: "Mở",
    join: "Tham gia ngay",
    joined: "Đã tham gia",
    description: "Mô tả",
    mentor: "Chủ kênh",
    viewProfile: "Xem hồ sơ",
    educationProgram: "Chương trình giảng dạy",
    viewMore: "Xem thêm",
    hideLess: "Ẩn bớt",
    rate: "Đánh giá",
    rankTeacher: "Xếp hạng giảng viên",
    student: "Học viên",
    courseContent: "Nội dung khoá học",
    requestSkills: "Kỹ năng cần có",
    information: "Thông tin",
    instructor: "Người hướng dẫn",
    titleModule: "Tiêu đề mô-đun",
    updateModule: "Cập nhật mô-đun",
    updateModuleSuccess: "Cập nhật thành công",
    createModuleSuccess: "Tạo thành công",
    addModule: "Thêm học phần",
    enterModuleName: "Thêm tên học phần",
    media: "Ảnh & Video",
    chooseFile: "Chọn tệp",
    downloadDocument: "Tải tài liệu",
    openWebsite: "Mở Website",
    editModule: "Chỉnh sửa bài học và học phần",
    consistsOf: "Bao gồm",
    parts: "phần",
    lectures: "bài giảng",
    requireLevel: "Yêu cầu cấp độ",
    requireLevelDes: "RẤT TIẾC BẠN CHƯA ĐỦ LEVEL ĐỂ MỞ KHÓA HỌC NÀY",
    emptyCourse: "Không có khoá học nào",
    price: "Giá",
    watchCourse: "Xem khoá học",
    notJoinedCourse: "Bạn chưa tham gia khoá học nào",
    mineCourse: "Khóa học đã học",
    freeCourse: "Khóa học miễn phí",
    priceCourse: "Khoá học nâng cao",
    more: "Xem thêm",
    completeCourse: "Đã hoàn thành",
    activeCourse: "Kích hoạt khoá học",
    activeCourseDes:
      "Khoá học này yêu cầu level :level và :coin để có thể kích hoạt. Để kích hoạt khoá học thủ công vui lòng truy cập website. Tiếp tục?",
    activeCourseSuccess: "Kích hoạt khoá học thành công",
    publicCourse: "Công khai khoá học",
    notificationPublicCourse: "Bạn chắc chắn muốn công khai khoá học này?",
    publicCourseSuccess: "Công khai khoá học thành công",
    noModuleInCourse: "Chưa có bài học nào",
    teacher: "Giáo viên",
    typeLearning: "Kiểu học tập",
    formLearning: "Hình thức học",
    skills: "Kỹ năng",
    filterSpeaker: "Giáo viên bản địa",
    viewResult: (text: string) =>
      text != 0 ? "Xem " + text + " khoá học" : "Không tìm thấy kết quả",
    viewResultTutor: (text: string) =>
      text != 0 ? "Xem " + text + " giáo viên" : "Không tìm thấy kết quả",
    priceCourse: "Giá khoá học",
    filterLevel: "Cấp độ khoá học",
    select: "Chọn",
    price_low: "Giá: thấp nhất",
    price_high: "Giá: cao nhất",
    rating: "Đánh giá cao nhất",
    newest: "Mới nhất",
    lastUpdate: "Lần cập nhật gần đây nhất",
    buyNow: "Mua ngay",
    addToCart: "Thêm vào giỏ hàng",
    filter: "Locj",
    formOfLearn: "Kiểu học",
    allForms: "Tất cả",
    callOneVsOne: "Học 1-1",
    salfLearning: "Học theo video",
    callGroup: "Học nhóm",
    skills: "Kỹ năng",
    allSkills: "Tất cả kỹ năng",
    listening: "Nghe",
    reading: "Đọc",
    writing: "Viết",
    Speaking: "Nói",
    pricePerCourse: "Giá khoá học",
    minimum: "Từ",
    maximum: "Đến",
    levelsOfStudy: "Cấp của học viên",
    timeAvailable: "Thời gian học",
    dayTime: "Ban ngày",
    eveningAndNight: "Buổi tối",
    onlyEnglish: "Học bằng Tiếng Anh",
    levelsOfTeacher: "Cấp của giáo viên",
    bestSeller: "Bán chạy nhất",
    growYourListening: "Phát triển kỹ năng nghe",
    growYourReading: "Phát triển kỹ năng đọc",
    growYourWriting: "Phát triển kỹ năng viết",
    growYourSpeaking: "Phát triển kỹ năng nói",
    sortBy: "Sắp xếp theo",
    calendar: "Lịch học",
    reviews: "Lượt",
    apply: "Áp dụng",
    placeholderReiview: "Nhập đánh giá của bạn",
    sendReview: "Gửi đánh giá",
    updateReview: "Cập nhật đánh giá",
    certifications: "Chứng chỉ",
    previewThisCourse: "Giới thiệu khoá học",
    title: "Tiêu đề",
    longDescription: "Chi tiết khoá học",
    startTime: "Ngày bắt đầu",
    endTime: "Ngày kết thúc",
    limitMember: "Học viên tối đa",
    createClass: "Tạo lớp",
    createClassSuccess: "Tạo lớp thành công",
    addLesson: "Thêm bài học",
    addLessonSuccess: "Thêm bài học thành công",
    addPart: "Thêm học phần",
    addPartSuccess: "Thêm học phần thành công",
  },
  seeAll: "Xem tất cả",
  settings: {
    numberOfDays: "Số ngày diễn ra",
    addPermission: "Cài đặt nhiệm vụ",
    permission: "Nhiệm vụ",
    shortcut: "Lối tắt",
    options: "Tác vụ và cài đặt",
    calendar: "Lịch",
    events: "Sự kiện",
    members: "Thành viên",
    changePassword: "Đổi mật khẩu",
    accountSetting: "Cài đặt tài khoản",
    channelSetting: "Cài đặt kênh",
    settingNoti: "Tùy chỉnh thông báo",
    switchChannel: "Đổi kênh",
    leaderboards: "Bảng thành tích",
    about: "Thông tin kênh",
    boss: "Chủ kênh",
    settings: "Cài đặt",
    inviteMemberUser: "Mời thành viên",
    inviteMemberMentor: "Thêm thành viên",
    inviteMemberSuggestMentor: "Mở rộng cộng đồng",
    inviteMemberSuggestUser: "Gia tăng thu nhập",
    profile: "Hồ sơ",
    logout: "Đăng xuất",
    logoutDes: "Bạn có muốn đăng xuất?",
    invite: "Đề xuất",
    general: "Chung",
    shortDes: "Mô tả",
    categories: "Chuyên mục",
    plugins: "Plugins",
    metrics: "Đo lường",
    gamification: "Gamifications",
    links: "Liên kết",
    linksInvite: "Liên kết giới thiệu",
    billing: "Thanh toán ",
    pending: "Đang chờ",
    block: "Khóa",
    remove: "Xoá",
    notificationLevel: "Thu thập {need point} điểm để thăng hạng",
    maxLevel: "Bạn đã đạt tối đa cấp độ",
    shortcuts: "Lối tắt",
    becomeAMentor: "Nâng cấp Mentor",
    becomeMentorDes: "Trở thành Mentor để:",
    becomeMentorDes1: "Hưởng đặc quyền doanh số không giới hạn",
    becomeMentorDes2: "Được quyền tạo khoá học trong hệ thống",
    becomeMentorDes3: "Và hàng trăm ngàn đặc quyền dành cho VIP",
    addLevel: "Thêm Level",
    deleteDes: "Bạn có chắc chắn muốn xoá {level}?",
    point: "Điểm",
    diamond: "Kim cương",
    settingPoint: "Cài đặt điểm",
    inviteUser:
      "Những người được mời bằng liên kết này sẽ trải qua quá trình phê duyệt tư cách thành viên. Muốn lời mời của bạn bỏ qua quá trình phê duyệt? Mời qua email",
    sendEmailSuccess: "Một lời mời đã được gửi đến email",
    newAudio: "Thay ghi âm",
    soundSetting: "Thêm âm thanh của bạn",
    deleteAccount: "Xoá tài khoản",
    deleteAccountConfirm: "(!!) Bạn có muốn xoá tài khoản này không?",
    deleteAccountDes:
      "Giúp chúng tôi cải thiện dịch vụ của chúng tôi trước khi rời đi.",
    enterReason: "Điền lý do",
    category: "Chuyên mục",
    channel: "Kênh",
    comment: "Bình luận",
    course: "Khoá học",
    level: "Level",
    module: "Bài giảng",
    request: "Bài đăng",
    create: "Thêm",
    createChannel: "Tạo kênh",
    update: "Sửa",
    delete: "Xoá",
    banUser: "Khoá người dùng",
    banUserDes: "Bạn chắc chắn muốn khoá :username?",
    removeUser: "Xoá User khỏi kênh",
    removeUserDes: "Bạn chắc chắn muốn xoá :username ra khỏi kênh",
    descriptionPoint:
      "Đây là số điểm mà học viên sẽ nhận được đối với mỗi hành động tương ứng",
    publicStatus:
      "Ai cũng có thể thấy ai đang ở trong kênh và những gì họ đăng lên. Nội dung có thể được tìm thấy bởi các công cụ tìm kiếm.",
    privateStatus:
      "Chỉ các thành viên mới có thể xem ai đang ở trong kênh và những gì họ đăng. Nội dung được ẩn khỏi các công cụ tìm kiếm.",
    navigationBar: "Thanh điều hướng",
    createNewChannel: "Tạo kênh của bạn",
    copyLink: "Sao chép liên kết",
    customNavigationBar: "Tuỳ chỉnh thanh điều hướng",
    navigationBarDes:
      "Tùy chọn 3 nút cho thanh điều dưới phía dưới (mặc định bao gồm 2 nút trang chủ và tác vụ). Tất cả các thaành viên trong kênh sẽ được tự động chuyển sang thanh điều hướng này theo cài đặt của bạn.",
    inviteDes:
      "Hãy sao chép liên kết này và gửi lời mời tới bạn bè. Bạn sẽ nhận được :percent% tổng doanh thu tới từ số thành viên mà bạn đã mời. \n" +
      "Đây là cơ hội tuyệt vời để bạn gia tăng thu nhập và khẳng định vị trí trong cộng đồng.\n" +
      "Thêm một thành viên mới là bạn đang tiến gần hơn đến nguồn doanh thu khổng lồ không giới hạn.",
  },
  profile: {
    editProfile: "Sửa hồ sơ",
    profile: "Hồ sơ",
    account: "Tài khoản",
    notifications: "Thông báo",
    chat: "Chat",
    bio: "Giới thiệu",
    birthday: "Ngày sinh",
    address: "Địa chỉ",
    phoneNumber: "Số điện thoại",
    socialLink: "Đường dẫn mạng xã hội",
    updateProfileSuccess: "Cập nhật hồ sơ thành công",
    oldPassword: "Mật khẩu cũ",
    newPassword: "Mật khẩu mới",
    confirmPassword: "Xác nhận mật khẩu",
    changePassword: "Thay đổi mật khẩu",
    notifyMeByEmail: "Thông báo cho tôi qua email",
    dontNotifyMeByEmail: "Không thông báo qua email",
    userNotifications: "Thông báo",
    whenSomebodyFollowsMe: "Khi có ai đó theo dõi tôi",
    whenIEarnMoneyFromReferrals: "Khi tôi có doanh thu từ hệ thống của tôi",
    groupNotifications: "Thông báo trong nhóm",
    digestEmailFrequency: "Tần suất thông báo email",
    digestEmailFrequencyDes:
      "Tóm tắt các bài đăng phổ biến và hoạt động của thành viên khi bạn không truy cập nhóm",
    notificationsEmailFrequency: "Tần suất gửi email",
    notificationsEmailFrequencyDes:
      "Tóm tắt các lượt thích, bình luận, đề cập và hoạt động chưa đọc cho các bài đăng/thành viên tôi theo dõi",
    postLikesNotifications: "Thông báo khi được thích",
    postLikesNotificationsDes: "Thông báo cho tôi khi ai đó thích bài viết",
    adminAnnouncements: "Thông báo của quản trị viên",
    adminAnnouncementsDes: "Thông báo cho tôi khi có bài viết mới từ quản trị",
    eventReminders: "Lời nhắc sự kiện",
    eventRemindersDes: "Thông báo trước khi sự kiện xảy ra",
    daily: "Hàng ngày",
    weekly: "Hàng tuần",
    every14Days: "Sau mỗi 14 ngày",
    monthly: "Hàng tháng",
    never: "Không bao giờ",
    mins: "phút",
    hourly: "Hàng giờ",
    hours: "giờ",
    notifyMe: "Thông báo",
    dontNotifyMe: "Không làm phiền",
    yes: "Đồng ý",
    no: "Hủy",
    notifyChat: "Bật tiếng thông báo",
    emailNotifications: "Thông báo qua email",
    emailNotificationsDes:
      " Gửi thông báo qua email. Chúng tôi sẽ không gửi email nếu bạn đang trực tuyến.",
    whoCanMessageMe: "Ai có thể nhắn tin cho bạn?",
    whoCanMessageMeDes:
      "Only members in the group you're in can message you. You choose what group users can message you from by turning your chat on/off below. Chỉ thành viên trong nhóm có quyền nhắn tin cho bạn. Hãy chọn nhóm bằng cách bật tắt phía dưới.",
    on: "Bật",
    off: "Tắt",
    pointToLevelUp: "điểm để thăng hạng",
    permisisonDenied: "Không có quyền truy cập",
    permissionDeniedDes: (text: string) =>
      `Hiện tại đang không có quyền truy cập ${text}. Bạn có muốn vào Cài đặt để có thể tiếp tục?`,
    shareProfile: "Chia sẻ",
  },
  member: {
    chat: "Hội thoại",
    membership: "Thành viên",
    memberOfGroup: "Thành viên trong nhóm",
    followSuccess: "Theo dõi {name} thành công.",
    unfollowSuccess: "Huỷ theo dõi với {name}.",
    blockSuccess: "Đã khoá {name} thành công",
    deleteSuccess: "Xoá thành công",
    deleteInviteJoinChannel:
      "Bạn có chắc chắn huỷ lời mời tham gia Channel của {name}?",
  },
  event: {
    addEvent: "Thêm sự kiện",
    updateEvent: "Cập nhật sự kiện",
    title: "Tiêu đề",
    date: "Ngày",
    time: "Giờ",
    duration: "Thời gian diễn ra (giờ)",
    timezone: "Múi giờ",
    recurringEvent: "Sự kiện cố định",
    location: "Sự kiện được tổ chức tại",
    link: "Link",
    description: "Mô tả",
    whoCanAttendThisEvent: "Ai có thể tham dự sự kiện này",
    remindMembersByEmail: "Nhắc thành viên qua email trước 1 ngày",
    create: "Tạo",
    library: "Thư viện",
    repeatOn: "Lặp lại",
    end: "Kết thúc",
    repeatEvery: "Lặp lại sau",
    pleaseSelectDay: "Hãy chọn ngày lặp lại sự kiện",
    after: "Sau",
    occurrences: "lần xuất hiện",
    uploadCoverImage: "Tải lên ảnh bìa",
    allMembers: "Toàn bộ thành viên",
    membersAtLevel: "Thành viên ở cấp độ",
    membersInCourse: "Thành viên trong khoá học",
    endDate: "Ngày kết thúc",
    never: "Không bao giờ",
    createEventSuccess: "Tạo sự kiện thành công",
    pleaseSelectImage: "Hãy chọn ảnh bìa",
    peopleInterested: "người đã tham gia",
    interest: "Tham gia",
    interested: "Đã tham gia",
    eventOfSpeaker: "Sự kiện của diễn giả",
    detailEvent: "Chi tiết sự kiện ",
    suggestEvent: "Gợi ý sự kiện",
    yourEvent: "Sự kiện của bạn",
    allEvent: "Tất cả sự kiện",
    join: "Tham gia",
    eventNotFoundToday: "Không có sự kiện nào",
    eventNotFound: "Hiện tại chưa có sự kiện nào",
    permissionCreateLivestreamEvent:
      "Bạn không có quyền tạo livestream trong sự kiện",
    permissionUpdateLivestreamEvent:
      "Bạn không có quyền sửa livestream trong sự kiện",
    historyLivestream: "Lịch sử livestream",
    timeLivestream: "Thời gian live",
    eventFinish: "Sự kiện kết thúc",
  },
  notifications: {
    notifications: "Thông báo",
    markAll: "Đánh dấu đã đọc",
    turnonChat: "Bật thông báo khi có tin nhắn tới",
    turnonPost: "Bật thông báo khi có bài đăng mới",
    turnonCourse: "Bật thông báo khi có các thông tin mới từ khoá học",
    emptyNotification: "Hiện tại chưa có thông báo nào",
  },
  invite: {
    invitePeople: "Mời tham gia",
    toJoin: "tham gia {channel}",
    sendInvite: "Gửi lời mời",
    getLink: "Lấy đường dẫn để chia sẻ",
  },
  categories: {
    addCategory: "Thêm chuyên mục",
    edit: "Sửa",
    delete: "Xoá",
    add: "Thêm",
  },
  gamifications: {
    description:
      "Hãy làm cho không khí náo nhiệt hơn! Hãy chọn tên dành cho cấp độ này để tạo hứng khởi. Khuyến khích người dùng tương tác nhiều hơn để mở khoá bài học.",
    level: "Cấp",
    point: "Điểm",
    pointHigher: "Điểm phải cao hơn Level {level}",
    pointLower: "Điểm phải thấp hơn Level {level}",
    pleaseInputPoint: "Vui lòng nhập điểm",
  },
  liveStream: {
    endLive: "Tạm dừng phiên trực tiếp",
    startLive: "Bắt đầu phiên trực tiếp",
    tapToAddDescription: "Ấn để thêm nội dung miêu tả",
    goLive: "Bắt đầu trực tiếp",
    finish: "Kết thúc",
    createLiveStream: "Tạo Livestream",
    createLivestreamError: "Tạo Livestream không thành công, thử lại sau",
    imageThumbnail: "Ảnh bìa Livestream",
    liveStreamNow: "Phát Live ngay",
    userJoinLive: ":username đã tham gia",
    userLeftLive: ":username đã rời khỏi",
    commentHere: "Bình luận sẽ xuất hiện tại đây",
    swipeLeft: "Vuốt qua phải để xem bình luận",
    livestreamEnded: "Livestream đã kết thúc",
    livestreamNotStarted: "Livestream chưa diễn ra",
    back: "Quay trở lại",
    writeComment: "Viết bình luận...",
    noRoleCreate: "Bạn không có quyền tạo phiên livestream",
    connecting: "Đang kết nối",
    infoLivestream: "Thông tin Livestream",
    otherPlatform: "Nền tảng khác",
    notePlatform:
      "Lưu ý: Khi livestream bằng cách này thì phiên live sẽ có độ trễ lớn hơn so với việc phát phiên live bằng camera",
    joinCoursesSuccessfully: "Tham gia khoá học thành công",
    questionEndLivestream: "Bạn có chắc chắn kết thúc phiên livestream?",
    watch: "Xem",
    pinProduct: "Ghim sản phẩm",
  },
  challenge: {
    suggestPickChallenge: "Tham gia các thử thách phía dưới ngay nào!",
    mineChallenge: "Đang tham gia",
    create: "Tạo mới",
    join: "Tham gia",
    postDate: "Ngày đăng",
    challenges: "Thử thách",
    checkin: "Báo cáo hoạt động",
    historyActivity: "Lịch sử hoạt động",
    conditionFree: "Tất cả thành viên đều có thể tham gia",
    conditionPoint: "Dành cho các thành viên có số điểm từ ",
    conditionLevel: "Dành cho các thành viên có cấp độ từ ",
    account: "Tài khoản",
    point: "Điểm",
    rank: "Thứ hạng",
    mine: "Của tôi",
    all: "Tất cả",
    timeStart: "Thời gian: $time",
    suggestJoin: "Hãy tham gia thử thách để nhận những phần quà giá trị!",
    joinNow: "Tham gia ngay",
    slogan: "Cạnh tranh để phát triển",
    createChallenge: "Thông tin cơ bản",
    startDate: "Ngày bắt đầu",
    leaderboard: "Bảng xếp hạng",
    information: "Giới thiệu",
    general: "Tổng quan",
    condition: "Điều kiện tham gia",
    playRule: "Cách chơi",
    detail: "Chi tiết",
    members: "Người chơi",
    reward: "Phần thưởng",
    notification: "Thông báo",
    endDate: "Ngày kết thúc",
    requireChallenge: "Điều kiện tham gia",
    pleaseInputAvatar: "Vui lòng thêm ảnh challenge",
    selectGame: "Chọn Game mẫu",
    configGame: "Cấu hình Game",
    gameName: "Tên game",
    requireGameName: "Vui lòng điền tên game",
    scoringCriteria: "Tiêu chí tính điểm",
    scoringCriteriaGuide:
      "Đây là phương thức điểm danh của Challenge.\nVui lòng lựa chọn Cách tính điểm và định dạng.\nVí dụ: Game đua doanh thu.\nCách tính điểm là: Ảnh chụp màn hình và Doanh số.\nVới Ảnh chụp màn hình - định dạng Ảnh, Doanh số - định dạng Điểm.",
    type: "Hình thức",
    gift: "Quà tặng",
    giftChallengeComplete: "Quà tặng hoàn thành challenge",
    addGift: "Thêm quà tặng",
    giftName: "Tên quà tặng",
    valueGift: "Giá trị quà tặng",
    newGift: "Quà tặng mới",
    info: "Thông tin",
    stage: "Chặng",
    stageSetting: "Cài đặt chặng",
    addStage: "Thêm mốc thời gian",
    stageName: "Tên chặng",
    typeCheckin: "Hình thức điểm danh",
    createChallengeSuccess: "Tạo mới challenge thành công",
    noChallenge: "Chưa có challenge nào",
    deleteDescription: "Bạn có chắc chắn muốn xoá challenge này?",
    quantity: "Số lượng",
    publicStatus: "Ai cũng có thể tham gia Challenge nếu đủ điều kiện",
    privateStatus: "Những thành viên tham gia cần Boss duyệt để vào Challenge",
    noMember: "Danh sách tham gia trống",
    noPending: "Danh sách trống",
    uploadImage: "Tải ảnh lên",
    member: "Thành viên",
    activity: "Hoạt động",
    recentActivity: "Hoạt động gần đây",
    addActivity: "Thêm hoạt động",
    content: "Nội dung",
    requireContent: "Vui lòng điền",
    reason: "Lý do",
    rejected: "Từ chối",
    aproved: "Đã duyệt",
    reject: "Từ chối",
    aprove: "Được chấp nhận",
    pending: "Chờ duyệt",
    status: "Tình trạng",
    aproveDes: "Duyệt hoạt động",
    rejectDes: "Từ chối hoạt động",
    waitingLiveStream: "Sắp diễn ra",
    endedLiveStream: "Đã kết thúc",
    watchLive: "Xem Live",
    goLive: "Go Live",
    noActivity: "Chưa có hoạt động nào",
    people: "Mọi người",
    maxUser: "Người chơi tối đa",
    infinityUserJoin: "Không giới hạn",
    cannotUpdateChallenge: "Không thể sửa challenge này",
    past: "Đã kết thúc",
    present: "Đang diễn ra",
    future: "Sắp tới",
    public: "Ai cũng có thể tham gia",
    pendingStatus: "Đang chờ duyệt",
    createNewGame: "Tạo game mới",
    createNewGameDes: "Bạn sẽ tự tạo các trường và tên của game",
    title: "Tên challenge",
    pleaseAddGiftChallenge: "Vui lòng thêm quà tặng cho challenge",
    memberList: "Danh sách tham gia",
    deleteUserSuccess: "Xoá thành viên thành công",
    deleteUser: "Xoá thành viên",
    deleteUserDes: "Bạn có muốn xoá :username ra khỏi challenge này?",
    createNextCycle: "Tự động tạo ở chu kì tiếp theo",
    addAllUser: "Tự động thêm tất cả người dùng",
    challengeHasBeenDeleeted: "Thử thách đã bị xoá",
    pleaseAddInfoStage: "Vui lòng điền đầy đủ thông tin chặng của Challenge",
  },
  mentor: {
    user: "Người dùng",
    mentor: "Mentor",
    listMentor: "Danh sách mentor",
    listUser: "Danh sách người dùng",
    addMentor: "Thêm mentor",
    addSuccess: "Thêm mới thành công",
    addMentorDes: "Bạn có chắc chắn muốn thêm :username trở thành mentor",
    deleteMentorDes: "Bạn muốn xoá :username khỏi danh sách mentor",
    addUser: "Thêm mới người dùng",
    addUserDes: "Bạn có muốn thêm :username vào danh sách",
    deleteUserDes: "Bạn muốn xoá :username khỏi danh sách nhận thưởng",
    deleteUser: "Xoá người dùng",
    deleteMentor: "Xoá mentor",
    analytics: "Thống kê",
    today: "Hôm nay",
    yesterday: "Hôm qua",
    thisMonth: "Tháng này",
    lastMonth: "Tháng trước",
    estimateEarn: "Doanh thu ước tính",
    history: "Lịch sử",
    settingProfit: "Cài đặt hoa hồng",
    paymentHistory: "Lịch sử thanh toán",
    selectDate: "Chọn ngày",
    last7day: "7 ngày trước",
    last30day: "30 ngày trước",
    info: "Thông tin",
    product: "Sản phẩm",
    course: "Khoá học",
    time: "Thời gian",
    transactionValue: "Giá tiền",
    commission: "Hoa hồng",
    incomeValue: "Doanh thu",
    userBuy: "Người mua",
    date: "Ngày",
    unitPrice: "VND",
    settingsCommissionDes:
      "Hoa hồng(%) mà người giới thiệu nhận được khi người được giới thiệu mua sản phẩm ",
    commissionMentor: "Hoa hồng cho mentor(%)",
    commissionUser: "Hoa hồng cho user(%)",
    timeJoin: "Ngày tham gia",
    withdraw: "Rút tiền",
    userWithdraw: "Người rút",
    timeWithdraw: "Thời gian",
    moneyWithdraw: "Số tiền",
    statusWithdraw: "Trạng thái",
    changeStatus: "Đổi trạng thái",
    done: "Hoàn thành",
    processing: "Đang xử lý",
    fail: "Từ chối",
    infoCommission: "Thông tin về về hoa hồng",
    commissionHeader:
      "Đây là tính năng hỗ trợ cho các chủ kênh xây dựng đội nhóm, truyền nhân bán hàng.\n\nMột điểm đặc biệt ở tính năng này đó là chủ kênh có thể phân cấp người dùng trong cộng đồng thành 3 vai trò lần lượt là: chủ kênh, mentor và người dùng cũng như cung cấp cho họ một mức hoa hồng nhất định cho mỗi lần giới thiệu được thành viên phát sinh mua hàng.",
    textCommissionBoss:
      "- Ở vai trò này, người dùng sẽ hoàn toàn kiểm soát, điều hành cộng đồng của riêng mình và có thể chỉ định phân quyền cho những người dùng khác (mentor, user).\n- Bạn có thể thiết lập mức hoa hồng cho mentor và user với mỗi giao dịch phát sinh.",
    textCommissionMentor:
      "- Quản lý số người dùng nhất định theo chỉ định của chủ kênh.\n- Nhận hoa hồng trọn đời từ mỗi giao dịch phát sinh của nhóm người mình quản lý.\n- Gia tăng số lượng thành viên quản lý (user) bằng cách giới thiệu thành viên mới vào cộng đồng.",
    textCommissionUser:
      "- Nhận được hoa hồng khi giới thiệu được người khác mua sản phẩm trong cộng đồng.",
    yourIncome: "Thu nhập của bạn",
    pleaseGoToWebsiteToWithdraw:
      "Vui lòng đăng nhập vào web để có thể gửi form rút tiền",
  },
  gift: {
    gift: "Quà tặng",
    noGift: "Chưa có phần quà nào",
    addGift: "Thêm mới quà tặng",
    updateGift: "Chỉnh sửa quà tặng",
    giftName: "Tên quà tặng",
    giftValue: "Giá trị(VND)",
    quantity: "Số lượng",
    conditionalGift: "Điều kiện nhận quà",
    birthday: "Sinh nhật",
    likeNumber: "Lượt thích",
    commentNumber: "Lượt bình luận",
    moduleNumber: "Số bài đã học",
    createSuccess: "Thêm mới quà tặng thành công",
    left: "Còn lại",
    noLeft: "Đã hết",
    deleteGiftDes: "Bạn có chắc chắn muốn xoá quà tặng :name",
    priceDesc: "Giá trị giảm dần",
    priceAsc: "Giá trị tăng dần",
    timeDesc: "Phần quà mới nhất",
    timeAsc: "Phần quà cũ nhất",
    qtyDesc: "Số lượng giảm dần",
    qtyAsc: "Số lượng tăng dần",
    info: "Thông tin",
    receiverUser: "Người nhận",
    prepare: "Đang chuẩn bị",
    transport: "Đang vận chuyển",
    received: "Đã nhận",
    cancel: "Đã huỷ",
    sendGift: "Gửi quà tặng",
    selectGift: "Chọn quà",
    selectPeople: "Chọn người",
    add: "Thêm",
    added: "Đã thêm",
    sendGiftSuccess: "Gửi quà tặng thành công",
    sendGiftDescription:
      "Bạn có chắc chắn muốn gửi :gift phần quà tới :user thành viên?",
    listReceive: "Danh sách nhận quà",
    digitalGift: "Quà tặng số",
    normalGift: "Quà vật lý",
    giftDigitalUrl: "Đường dẫn quà tặng",
    giftDigitalFile: "File quà tặng",
    giftDigitalDes:
      "Thông tin này sẽ hiện ra cho người dùng khi người đó đủ điều kiện nhận quà",
    giftNormalDes: "Thông tin này luôn luôn hiển thị cho người dùng",
    giftInfo: "Thông tin quà tặng",
    uploadFile: "Thêm quà tặng",
  },
  extension: {
    inDevelop: "Đang phát triển",
    bought: "Đã cài đặt",
    extensions: "Extensions",
    goToWeb: "Bạn có muốn truy cập vào website để cài đặt?",
    setup: "Cài đặt",
    extensionTitle: "Mở Rộng Không Giới Hạn Với Kho Extensions",
    extensionDescription: "Đáp Ứng Nhu Cầu & Mở Rộng\nKhông Giới Hạn",
    extensionInfo: "Giới thiệu về Extension",
    price: "Chi phí",
    freeTrial: "Dùng thử miễn phí",
    go: "Vào",
    noticeFeatureExtend:
      "Bạn có muốn sang website để gia hạn tính năng này. Tiếp tục?",
    feature: "Tính năng",
    featureExpired:
      " sẽ hết hạn sau :day ngày. Nâng cấp ngay để không bị gián đoạn sử dụng",
    watchNow: "Xem ngay",
    joinNow: "Tham gia ngay",
    freeTrialDay: "Dùng Thử Miễn Phí :day Ngày.",
  },
  updateProfile: {
    phoneNumber: "Nhập số điện thoại",
    validatePhoneNumber: "Xác thực số điện thoại",
    otp: "Nhập mã OTP",
    resend: "Gửi lại",
    invalidCode: "Mã OTP không chính xác",
    pleaseWait: "Vui lòng đợi",
    otherPhoneNumber: "Nhập số điện thoại khác",
    otherChannel: "Bạn muốn đăng nhập vào kênh khác?",
    otherAccount: "Sử dụng tài khoản khác? Đăng xuất",
    phoneNumberAlreadyInUse: "Số điện thoại này đã được sử dụng",
    continueWithoutVerity: "Tiếp tục mà không cần xác thực",
    getOTPFailed: "Lấy mã OTP thất bại. Vui lòng thử lại!",
    verifySuccess: "Xác thực thành công",
    requireOtp: "Vui lòng nhập mã OTP",
    verifyDes:
      "Chúng tôi mong muốn bạn cung cấp số điện thoại để có thể hỗ trợ bạn bất cứ lúc nào. Nếu bạn không muốn xác thực số điện thoại thì bạn có thể bỏ qua bước này.",
    skip: "Bỏ qua",
  },
  permission: {
    NotiMissionSuccess: "Chúc mừng bạn đã hoàn thành nhiệm vụ",
    todayPermission: "Nhiệm vụ hôm nay",
    Perform: "Thực hiện",
    completeMissionAndGift: "Hoàn thành nhiệm vụ và nhận quà khủng",
    giftToday: "Phần thưởng hôm nay",
    completeNow: "Hoàn thành ngay nhiệm vụ hôm nay!",
    mission: "Nhiệm vụ",
    pleaseChooseMission: "Mời chọn nhiệm vụ",
    likePost: "Thích bài viết",
    likeComment: "Thích bình luận",
    inviteParticipants: "Mời người tham gia",
    commentPost: "Comment bài viết",
    uploadPost: "Đăng tải bài viết",
    viewCourse: "Xem video khóa học",
    addMission: "Thêm nhiệm vụ",
    titleMission: "Tên nhiệm vụ",
    pleaseInputCountMission: "Vui lòng nhập số lượng nhiệm vụ",
    deleteMissionSure: "Bạn có chắc chắn muốn xoá nhiệm vụ này?",
    reward: "Phần thưởng",
    physicalGift: "Quà vật lý",
    numberCoin: "Số kim cương",
    missionCompleted: "Nhiệm vụ đã hoàn thành",
    missionName: "Tên nhiệm vụ",
    createSuccess: "Tạo nhiệm vụ thành công",
    updateProfile: "Cập nhật hồ sơ",
    nextMissions: "Nhiệm vụ các ngày tiếp theo",
    missionDayIs: "Nhiệm vụ ngày thứ {day}",
    missionOver: "Nhiệm vụ đã qua",
    youCanEditAndDelete: "Bạn có thể chỉnh sửa và xoá nhiệm vụ",
    deleteMissionSuccess: "Xoá nhiệm vụ thành công",
    notificationUpdateMission:
      "Khi chỉnh sửa nhiệm vụ, các dữ liệu ghi nhận trước đó sẽ mất hết. Bạn có chắc chắn chỉnh sửa nhiệm vụ này?",
    updateMission: "Cập nhật nhiệm vụ",
    updateMissionSuccess: "Cập nhật nhiệm vụ thành công",
    prev: "Trước",
    next: "Sau",
    diamond: "Kim cương",
    dontHaveModuleGift:
      "Bạn chưa mua tính năng Tặng Quà! Sở hữu ngay để kích thích tương tác thành viên trên kênh.",
    dontHaveMission:
      "Chưa thêm nhiệm vụ cho ngày {day}. Vui lòng thêm ít nhất một nhiệm vụ!",
    updateSuccess: "Cập nhật thành công",
    errorsValidateMissionDay: "Vui lòng thêm nhiệm vụ vào ngày {day}",
    descriptionUpdateProfile: "(Cập nhật tên và số điện thoại)",
    errorsValidateCountMissionDay:
      "Vui lòng thêm số lượng nhiệm vụ trong ngày {day}",
    completeCourse: "Hoàn thành khoá học",
    inviteUser: "Mời người dùng",
    congratulation: "CHÚC MỪNG BẠN ĐÃ NHẬN ĐƯỢC PHẦN QUÀ",
  },
  podcast: {
    listPodcast: "Danh sách Podcasts",
    emptyList: "Không có podcast nào",
    infoPodcast: "Nhập thông tin podcast",
    titlePodcast: "Tiêu đề",
    contentPodcast: "Nội dung",
    createPodcastSuccessfully: "Tạo mới podcast thành công",
    updatePodcastSuccessfully: "Chỉnh sửa podcast thành công",
    imageRequired: "Vui lòng thêm ảnh",
    titleRequired: "Vui lòng điền tiêu đề của podcast",
    addPodcast: "Thêm podcast",
    record: "Ghi âm",
    uploadFile: "Tải file lên",
    stop: "Dừng",
    hint: "Gợi ý nội dung",
    thumbnail: "Chọn ảnh nổi bật cho podcast",
    artist: "Tác giả",
    info: "Thông tin",
    list: "Danh sách",
    add: "Thêm",
  },
  faq: {
    titleFaq:
      "Để phục vụ nhu cầu sử dụng của người dùng, đồng tiền ảo với tên gọi Point và kim cương đã ra đời.",
    whatIsPoint: "Point là gì?",
    whatIsDiamond: "Kim cương là gì",
    descriptionPoint:
      "Khi tương tác trong cộng đồng như bình luận, thích, đăng bài, mời thành viên hay xem bài học hoặc điểm danh, các thành viên sẽ nhận được số Point tương ứng theo cài đặt từ quản trị viên.\n\nThành viên có thể sử dụng đồng tiền ảo này tích luỹ để lên cấp, mở khoá các khoá học mới.",
    descriptionDiamond:
      "Để nhận được kim cương trong cộng đồng, các thành viên sẽ phải hoàn thành các nhiệm vụ và điểm danh hàng ngày.\n\nCác thành viên có thể sử dụng kim cương để mua bán các khoá học,…( mỗi kim cương tương ứng 1000 vnđ) trong cộng đồng.",
    actionPoint:
      "Khi tương tác trong cộng đồng như bình luận, thích, đăng bài, mời thành viên hay xem bài học hoặc điểm danh, các thành viên sẽ nhận được số Point tương ứng theo cài đặt từ quản trị viên.",
    personPoint:
      "Thành viên có thể sử dụng đồng tiền ảo này tích luỹ để lên cấp, mở khoá các khoá học mới.",
    titleDiamond:
      "Để nhận được kim cương trong cộng đồng, các thành viên sẽ phải hoàn thành các nhiệm vụ và điểm danh hàng ngày.",
    personDiamond:
      "Các thành viên có thể sử dụng kim cương để mua bán các khoá học,…( mỗi kim cương tương ứng 1000 vnđ) trong cộng đồng.",
    noteDiamond:
      "Lưu ý: Point và kim cương chỉ có giá trị khi sử dụng trên kênh của cộng đồng mà thành viên đang tương tác mà thôi.",
  },
  introduce: {
    scrollDownToSeeNewPost: "Kéo xuống để xem bài viết mới nhất",
    introducePoint: "Sử dụng để mở khoá các khoá học trong kênh",
    introduceDiamond: "Một loại tiền ảo dùng như tiền mua hàng",
  },
  results: "kết quả",
  sort_by_relevance: "Sắp xếp theo tiêu chí",
  noResult: "Không tìm thấy kết quả",
  startChat: "Bắt đầu cuộc trò chuyện!",
  startDesc:
    "Gửi những tin nhắn hỏi về hành trình học tiếng anh hoặc thảo luận những chủ đề thú vị để bắt đầu cuộc trò chuyện",
  noNewMessageTittle: "Không có tin nhắn mới",
  noNewMessageDesc:
    "Khi bạn liên lạc người khác hoặc trả phí khoá học, tin nhắn sẽ hiển thị ở đây",
  actionView: {
    sendYourAudioMessage: "Gửi tin nhắn âm thanh của bạn",
    releaseToSend:
      "Nhả để gửi, chuyển sang bên phải để sử dụng chế độ rảnh tay",
    holdToRecord: "Giữ để ghi âm",
  },
  mediaKeyboard: {
    chooseFromGallery: "Chọn từ thư viện",
    permissionToRecord:
      "Cần có quyền ghi, ghi dữ liệu và truy cập thư viện để sử dụng chức năng này",
    grandPermission: "Cấp quyền",
    weHaveRemovedErrorPhoto:
      "Chúng tôi đã xóa các tệp ảnh hoặc video có lỗi dài hơn 1 phút",
    attention: "Chú ý!",
    imageIsError: "Ảnh bị lỗi!",
    shootAVideo: "Quay video",
    takeAPhoto: "Chụp ảnh",
  },
  keyboard: {
    writeSomething: "Nhập tin nhắn...",
    sending: "Đang gửi...",
  },
  audio: {
    pause: "Tạm dừng",
    resume: "Tiếp tục",
    stop: "Dừng",
    send: "Gửi",
  },
  livestream: {
    hello: "Xin chào",
    inputTitle: "Nhập tiêu đề cho phiên livestream",
  },
  purchase: {
    headerBookLesson: "Đặt lịch học",
    headerChooseClass: "Chọn lớp",

    timeDuration: "Thời lượng học",
    chooseDay: "Chọn ngày học",
    chooseDayDes: "Bạn chỉ được chọn tối đa 4 ngày",
    timeNote: "Múi giờ của bạn, Asia/Ho Chi Minh (GMT +7:00)",
    morning: "Sáng",
    Afternoon: "Chiều",
    Night: "Tối",
    hoursNote: "Bạn chỉ được chọn tối đa 2 khung giờ học",
    orderNow: "Thanh toán!",
    participants: "Thành viên",
    startDate: "Ngày bắt đầu",
    endDate: "Ngày kết thúc",
  },
  payment: {
    paymentmethod: "Phương thức thanh toán",
    paymentdetail: "Chi tiết thanh toán",
    totalpayment: "Tổng tiền",
    vnpay: "VNPay",
    smartbanking: "Smart Banking",
    formforLearning: "Hình thức học",
    class: "Lớp",
    days: "Ngày học",
    learningtime: "Thời gian học",
    promo: "Khuyến mãi",
    errorpaymentmethod: "Bạn chưa chọn phương thức thanh toán",
    couresfree: "Khoá học miễn phí",
    completecheckout: "Hoàn tất thanh toán",
    promotion: "Khuyến mãi",
    notePurchase:
      "Giao dịch sẽ mất ít phút để hoàn thành, khi thành công chúng tôi thông báo đến bạn",
    paymentsuccess: "Giao dịch thành công",
    completepayment:
      "Khi bạn đã hoàn tất việc thanh toán của mình. Bạn chỉ cần nhấp vào nút bên dưới để tận hưởng khóa học.",
    gomylearning: "Đi đến lớp học",
    uploadfile: "Gửi file",
    send: "Gửi",
    sendPro: "Gửi thông tin giao dịch",
    saveQRCode: "Lưu mã QR",
    tocomplete:
      "Để hoàn tất quá trình thanh toán, vui lòng thực hiện chuyển khoản tới số tài khoản bên dưới:",
  },
  settingUser: {
    language: "Ngôn ngữ",
    hightandweigh: "Đơn vị chiều cao/cân nặng",
    space: "Đơn vị khoảng cách",
    deletecache: "Xoá bộ nhớ đệm",
    noti: "Thông báo",
    hidden: "Tạm ẩn tôi khỏi WhiteG",
    block: "Chặn tin nhắn từ người lạ",
    blackList: "Danh sách đen",
    setting: "Cài đặt",
    private: "Bảo mật & riêng tư",
    support: "Hỗ trợ khách hàng",
    aboutus: "Về chúng tôi",
  },
  aboutUs: {
    aboutUs: "Về chúng tôi",
    termofus: "Điều khoản sử dụng",
    privacy: "Chính sách bảo mật",
    cookie: "Chính sách cookie",
    return: "Chính sách hoàn trả",
    deleteacount: "Xoá tài khoản",
  },
  call: {
    inComingCall: "Cuộc gọi đến...",
    titleCamera: "Cần truy cập vào quyền camera trên máy của bạn",
    messageCamera:
      "Để gọi cho người khác, chúng tôi cần truy cập vào camera của bạn.",
    titleMic: "Cần quyền truy cập microphone",
    messageMic:
      "Để gọi điện thoại cho người khác, chúng tôi cần quyền truy cập vào microphone của bạn.",
  }
};
