export default {
  home: "Trang chủ",
  profile: "Hồ sơ",
  detail: "Chi tiết",
  setting: "Cài đặt",
  language: "Ngôn ngữ",
  darkMode: "Chế độ tối",
  switchLanguage: "Đổi ngôn ngữ",
  approve: "Đồng ý",
  cancel: "Huỷ",
  placeholderEmaiPhone: "Email/Số điện thoại",
  placeholderPasword: "Mật khẩu",
  forgotPassword: "Quên mật khẩu",
  signIn: "Đăng nhặp",
  signUp: "Đăng ký",
  signInWith: "Đăng nhập với",
  continue: "Tiếp tục",
  continueWith: (text: string) => `Tiếp tục với ${text}`,
  enterNewPassword: "Nhập mật khẩu mới",
  confirmPassword: "Xác nhận mật khẩu",
  enterOTP: "Nhập mã otp",
  updatePassword: "Cập nhật mật khẩu",
  save: "Lưu",
  required: "không được để trống",
  invalid: "không hợp lệ",
  or: "Hoặc",
  welcomeBack: "Mừng bạn trở lại",
  minLength: (number: number) => `tối thiểu ${number} ký tự`,
  needAnAccount: "Cần một tài khoản? ",
  registerNow: "Đăng ký!",
  createNewAccount: "Tạo tài khoản",
  fullname: "Họ và tên",
  haveAnAccount: "Đã có tài khoản? ",
  loginNow: "Đăng nhập ngay!",
};
