/* eslint-disable max-len */
export default {
  // --- Common & Auth ---
  detail: "Chi tiết",
  setting: "Cài đặt",
  openSetting: "Mở cài đặt",
  language: "Ngôn ngữ",
  darkMode: "Chế độ tối",
  switchLanguage: "Đổi ngôn ngữ",
  approve: "Chấp thuận",
  cancel: "Hủy",
  placeholderEmaiPhone: "Email / Số điện thoại",
  placeholderEmail: "Email",
  placeholderVerifyCode: "Mã xác thực",
  placeholderPasword: "Mật khẩu",
  placeholderRePasword: "Nhập lại mật khẩu",
  forgotPassword: "Quên mật khẩu?",
  verifyCodeTitle: (text) => `Nhập mã xác thực được gửi đến ${text}`,
  signIn: "Đăng nhập",
  signUp: "Đăng ký",
  signInWith: "Đăng nhập bằng",
  continue: "Tiếp tục",
  continueWith: (text) => `Tiếp tục với ${text}`,
  enterNewPassword: "Nhập mật khẩu mới",
  confirmPassword: "Xác nhận mật khẩu",
  enterOTP: "Nhập OTP",
  updatePassword: "Cập nhật mật khẩu",
  save: "Lưu",
  required: "bắt buộc",
  invalid: "Không hợp lệ",
  or: "Hoặc",
  hi: "Xin chào",
  welcomeBack: "Khởi động hành trình sống khỏe ngay hôm nay!",
  minLength: (number) => `tối thiểu ${number} ký tự`,
  needAnAccount: "Chưa có tài khoản? ",
  registerNow: "Đăng ký ngay!",
  createNewAccount: "Tạo tài khoản mới!",
  fullname: "Họ và tên",
  haveAnAccount: "Đã có tài khoản? ",
  loginNow: "Đăng nhập ngay!",
  welcomeHeader: "Chào mừng đến với CaloSnap",
  welcomeDescription: "Theo dõi calo chưa bao giờ dễ dàng đến thế! Với CaloSnap bạn sẽ...",
  startNow: "Bắt đầu ngay",
  sendingError: "Đã xảy ra lỗi!",
  createPassSuccess: "Tạo mật khẩu mới thành công!",
  loginSuccess: "Đăng nhập thành công!",
  goBackHome: "Về trang chủ",
  next: "Tiếp theo",
  other: "Khác",
  keepGoing: "Cố lên!",
  changeLanguage: "Chọn ngôn ngữ",

  // --- Tabs ---
  homes: "Trang chủ",
  chats: "Tin nhắn",
  discovers: "Khám phá",
  profile: "Hồ sơ",
  statistics: {
    title: "Thống kê",
    overview: "Tổng quan",
    comingSoon: "Tính năng sắp ra mắt",
  },
  health: {
    title: "Sức khỏe",
    overview: "Tổng quan",
    comingSoon: "Tính năng sắp ra mắt",
  },

  // --- Errors ---
  error: {
    unknown: "Lỗi không xác định!",
    invalidPhoneEmail: "SĐT/Email không hợp lệ",
    invalidEmail: "Email không hợp lệ",
    invalidPhone: "Số điện thoại không hợp lệ",
    invalidLink: "Liên kết không hợp lệ",
    passDoesNotMatch: "Mật khẩu xác nhận không khớp",
    minLengthPass: "Mật khẩu phải có ít nhất 6 ký tự",
    isOffline: "Vui lòng kết nối mạng và thử lại!",
  },

  // --- Actions ---
  reset: "Đặt lại",
  apply: "Áp dụng",
  blackList: {
    unblock: "Bỏ chặn",
    unBlockSuccess: "Bỏ chặn thành công!",
    warningUnblock: (name) => `Bạn muốn bỏ chặn ${name}?`,
  },
  you: "Bạn",
  permissions: {
    titleCamera: "Cần quyền truy cập Camera",
    messageCamera: "Chúng tôi cần quyền truy cập camera để chụp ảnh món ăn của bạn",
    denied: "Quyền bị từ chối. Vui lòng bật trong cài đặt.",
    negative: "Hủy",
    positive: "Đồng ý",
  },

  // --- Social & Chat ---
  postCategory: "Chọn danh mục",
  createPost: "Tạo bài viết",
  placeholderContent: "Bạn đang nghĩ gì?",
  confirm: "Xác nhận",
  somethingWentWrong: "Có lỗi xảy ra. Vui lòng thử lại.",
  notFound: "Danh sách trống",
  offlineNetwork: "Bạn đang ngoại tuyến",
  onlineNetwork: "Đã khôi phục kết nối internet",
  all: "Tất cả",
  seconds: "giây",
  minutes: "phút",
  hours: "giờ",
  days: "ngày",
  weeks: "tuần",
  months: "tháng",
  schedule: "Lịch trình",
  years: "năm",
  ago: "trước",
  copied: "Đã sao chép",
  copy: "Sao chép",
  report: "Báo cáo",
  block: "Chặn",
  unBlockUser: "Bỏ chặn",
  commentAs: "Bình luận với tư cách",
  replying: "Đang trả lời",
  reply: "trả lời",
  like: "thích",
  comment: "bình luận",
  delete: "Xóa",
  edit: "Sửa",
  copyLink: "Sao chép liên kết",
  deleteSuccess: "Xóa thành công",
  updateSuccess: "Cập nhật thành công",
  online: "Đang hoạt động",
  offline: "Ngoại tuyến",
  status: "Trạng thái",
  joined: "Đã tham gia",
  bio: "Tiểu sử",
  follower: "Người theo dõi",
  following: "Đang theo dõi",
  follow: "Theo dõi",
  unfollow: "Bỏ theo dõi",
  followed: "Được theo dõi",
  message: "Nhắn tin",
  filter: "Lọc",
  sort: "Sắp xếp",
  search: "Tìm kiếm...",
  update: "Cập nhật",
  viewAll: "Xem tất cả",
  aboutMe: "Giới thiệu",
  today: "Hôm nay",
  yesterday: "Hôm qua",
  tomorrow: "Ngày mai",
  from: "Từ",
  to: "Đến",
  selectImage: "Chọn ảnh",
  public: "Công khai",
  post: {
    likes: (count) => `${count} lượt thích`,
    post: "Đăng",
    posts: "Bài viết",
    createPost: "Tạo bài viết",
    category: "Danh mục",
    title: "Tiêu đề",
    content: "Nội dung",
    createPostSuccess: "Đăng bài thành công",
    like: "Thích",
    liked: "Đã thích",
    share: "Chia sẻ",
    comment: "Bình luận",
    comments: "bình luận",
    emptyComment: "Chưa có bình luận nào",
    emptyPost: "Chưa có bài viết nào",
    emptyPostDes: "Chia sẻ hành trình sức khỏe của bạn với bạn bè!",
    report: "Báo cáo bài viết",
    save: "Lưu bài viết",
    savePostSuccess: "Lưu thành công",
    uploadImageFaild: "Tải ảnh thất bại. Vui lòng thử lại!",
  },
  
  // --- Chat ---
  chat: {
    search: "Tìm kiếm",
    sendMessage: "Gửi tin nhắn",
    cancel: "Hủy",
    typeMessage: "Nhập tin nhắn...",
    lastSeen: "Truy cập lần cuối: ",
    addMember: "Thêm thành viên",
    createGroupSuccess: "Tạo nhóm chat thành công",
    selectGroup: "Chọn nhóm",
    selectMember: "Chọn thành viên",
    mediaFile: "Ảnh, tập tin",
    createGroup: (txt) => `Tạo nhóm với ${txt}`,
    sendFiles: "Gửi ảnh, tệp, liên kết",
    blockUser: "Chặn người dùng",
    report: "Báo cáo",
    leave: "Rời nhóm",
    renameGroup: "Đổi tên nhóm",
    enterGroupName: "Nhập tên nhóm",
  },

  // --- Home / Dashboard (Calorie App Core) ---
  home: {
    whatonYourMind: "Bạn đang nghĩ gì?",
    recentActivity: "Hoạt động gần đây",
    macros: {
      CARBS: "Tinh bột (Carbs)",
      PROTEIN: "Đạm (Protein)",
      FAT: "Chất béo (Fat)",
    },
    week: {
      dayShort: "T__INDEX__", // Giữ logic index hoặc đổi thành T2, T3... nếu cần
      sunShort: "CN",
    },
    daily: {
      intake: "Nạp vào",
      burn: "Tiêu thụ",
      valuePrefix: "",
    },
    emptyMealsTitle: "Chưa có bữa ăn nào!",
    emptyMealsSub: "Nhấn + để thêm bữa ăn đầu tiên trong ngày.",
    greeting: "Hôm nay",
    dashboard: {
      caloriesLabel: "Mục tiêu Calo",
      stepsLabel: "Mục tiêu Bước chân",
      waterLabel: "Mục tiêu Nước",
      consumedLabel: "Đã nạp",
      burnedLabel: "Tiêu hao",
      unitCalories: "kcal",
      unitSteps: "bước",
      unitWater: "ml",
    },
    banner: {
      title: "Trợ lý Calo AI",
      download: "Tải về",
      premiumPrefix: "Không quảng cáo.",
      premiumCta: "Nâng cấp Premium",
    },
  },

  // --- Calorie Scanner / Result ---
  scanner: {
    title: "CaloSnap",
    analysisSuccess: "Phân tích thành công!",
    saveSuccess: "Đã lưu bữa ăn!",
    saveError: "Lỗi khi lưu dữ liệu.",
    deleteIngredientTitle: "Xóa thành phần",
    deleteIngredientMessage: "Bạn có chắc muốn xóa?",
    cancel: "Hủy",
    delete: "Xóa",
    cameraPermissionTitle: "Cần quyền Camera",
    cameraPermissionMessage: "Vui lòng cấp quyền...",
    openSettings: "Cài đặt",
    health: "Sức Khỏe",
    nutritionTitle: "Calo & Dinh dưỡng",
    quantity: "Số lượng",
    calories: "Calo",
    carbs: "Tinh bột",
    protein: "Chất đạm",
    fat: "Chất béo",
    ingredients: "Thành phần",
    addIngredient: "Thêm thành phần mới",
    tweakHint: 'Muốn tinh chỉnh kết quả của bạn? Nhấn "Sửa kết quả" và cho chúng tôi biết!',
    editResult: "Sửa kết quả",
    save: "Lưu",
    mealDetail: "Chi tiết bữa ăn",
    result: "Kết quả",
  },

  // --- Intro (first-time welcome) ---
  intro: {
    title: "Theo dõi calo\ndễ dàng hơn",
    getStarted: "Bắt đầu",
    alreadyHaveAccount: "Đã có tài khoản? ",
    signIn: "Đăng nhập",
  },

  // --- Login / Auth ---
  login: {
    requireLogin: "Vui lòng đăng nhập để tiếp tục",
    continueFacebook: "Tiếp tục với Facebook",
    continueGoogle: "Tiếp tục với Google",
    continueApple: "Tiếp tục với Apple",
    email: "Email",
    emailPhone: "Email / Số điện thoại",
    password: "Mật khẩu",
    signin: "Đăng nhập",
    signup: "Đăng ký",
    dontHaveAccount: "Chưa có tài khoản?",
    or: "Hoặc",
    termConditions: "Điều khoản & Điều kiện",
    privacyPolicy: "Chính sách bảo mật",
    alreadyHaveAccount: "Đã có tài khoản?",
    createYourAccount: "Tạo tài khoản mới",
    loginError: "Lỗi đăng nhập, vui lòng thử lại!",
    registerSuccess: "Đăng ký thành công",
    forgotPassword: "Quên mật khẩu",
    send: "Gửi",
    forgotPasswordSuccess: "Đã gửi email khôi phục, vui lòng kiểm tra hộp thư!",
  },

  // --- Validations ---
  validate: {
    emailInvalid: "Email không hợp lệ",
    requiredEmail: "Vui lòng nhập Email",
    requiredPassword: "Vui lòng nhập mật khẩu",
    requiredFullName: "Vui lòng nhập họ tên",
    errorConfirmPasswordNotMatch: "Mật khẩu không khớp",
    requiredDate: "Vui lòng chọn ngày",
    requiredTime: "Vui lòng chọn giờ",
  },

  // --- Setting User & Profile ---
  settingUser: {
    language: "Ngôn ngữ",
    hightandweigh: "Chiều cao / Cân nặng",
    space: "Không gian",
    deletecache: "Xóa bộ nhớ đệm",
    noti: "Thông báo",
    blackList: "Danh sách chặn",
    setting: "Cài đặt",
    private: "Bảo mật & Quyền riêng tư",
    support: "Hỗ trợ khách hàng",
    aboutus: "Về chúng tôi",
  },
  
  aboutUs: {
    aboutUs: "Về chúng tôi",
    termofus: "Điều khoản sử dụng",
    privacy: "Chính sách bảo mật",
    deleteacount: "Xóa tài khoản",
  },

  // --- Profile Screen specific (CaloSnap style) ---
  profile: {
    title: "Hồ sơ",
    editProfile: "Chỉnh sửa hồ sơ",
    saveProfile: "Lưu hồ sơ",
    account: "Tài khoản",
    notifications: "Thông báo",
    bio: "Tiểu sử",
    addBio: "Thêm tiểu sử",
    
    // Groups in Setting Profile
    goals: "Mục tiêu",
    customization: "Tùy chỉnh",
    other: "Khác",
    followUs: "Theo dõi CaloSnap",
    
    // Goal Items
    weight: "Cân nặng",
    calories: "Calo",
    nutrition: "Dinh dưỡng",
    diet: "Chế độ ăn",
    steps: "Bước chân",
    water: "Nước",
    
    // Customization Items
    restart: "Bắt đầu lại",
    reminders: "Nhắc nhở",
    darkMode: "Chế độ tối",
    language: "Ngôn ngữ",
    addBurnedCalories: "Cộng calo tiêu thụ vào mục tiêu",
    metricSystem: "Hệ mét",
    
    // Other Items
    rateApp: "Đánh giá CaloSnap",
    freeQuota: "Hạn mức miễn phí",
    support: "Hỗ trợ",
    privacyPolicy: "Chính sách bảo mật",
    termsOfUse: "Điều khoản sử dụng",
    medicalSources: "Nguồn thông tin y tế",
    deleteAccount: "Xóa tài khoản",
    
    // Social & Account
    login: "Đăng nhập",
    id: "ID",
    tiktok: "TikTok",
    facebook: "Facebook",
    
    // Descriptions
    addBurnedCaloriesDesc: "Tăng giới hạn calo hàng ngày dựa trên hoạt động",
    metricSystemDesc: "Tắt để sử dụng đơn vị đo lường Imperial (lbs/ft)",
    deleteAccountDesc: "Xóa tất cả dữ liệu và khởi tạo lại",
    
    // Pro Banner
    proBannerTitle: "CaloSnap",
    proBadge: "PRO",
    proDescription: "Trải nghiệm AI thông minh không lo bị gián đoạn - Nhanh chóng đạt được mục tiêu.",
    proButton: "Dùng thử miễn phí",
    
    // Footer
    footerVersion: "CaloSnap 1.6.18+63",
    footerCopyright: "© 2025 CaloSnap. All rights reserved.",
    
    // Goal Details
    weightGoalTitle: "Mục tiêu cân nặng",
    caloriesGoalTitle: "Mục tiêu Calo",
    dietGoalTitle: "Chế độ ăn",
    stepsGoalTitle: "Mục tiêu bước chân",
    waterGoalTitle: "Mục tiêu uống nước",
    stepsUnit: "bước / ngày",
    waterUnit: "ml",
    chooseLanguageSubtitle: "Chọn ngôn ngữ bạn muốn sử dụng",
  },

  // --- Diet Types ---
  dietTypes: {
    BALANCED: "Cân bằng",
    LOW_CARB: "Ít Carb (Low Carb)",
    LOW_FAT: "Ít chất béo",
    HIGH_PROTEIN: "Giàu Protein",
    KETO: "Keto",
    VEGETARIAN: "Chay",
  },

  // --- Premium / Payment ---
  premiumAccount: {
    freeTrial: "Dùng thử miễn phí 3 ngày",
    day: "Ngày",
    month: "Tháng",
    year: "Năm",
    save: "Tiết kiệm",
    getIt: "Nâng cấp Premium",
    noThanks: "Không, cảm ơn",
    whiteGPro: "Premium",
    proDes: "Nâng cấp lên Premium để sử dụng AI phân tích chuyên sâu và không giới hạn!",
    getPro: "Nhận Premium",
    upgrade: "Nâng cấp",
    restore: "Khôi phục giao dịch",
  },
  
  payment: {
    paymentmethod: "Phương thức thanh toán",
    totalpayment: "Tổng thanh toán",
    paymentsuccess: "Thanh toán thành công",
  },

  // --- Affiliate ---
  affiliate: {
    yourIncome: "Thu nhập của bạn",
    withdraw: "Rút tiền",
    product: "Sản phẩm",
    customer: "Khách hàng",
    commission: "Hoa hồng",
    revenua: "Doanh thu",
  },

  // --- Notifications ---
  notifications: {
    notifications: "Thông báo",
    markAll: "Đánh dấu tất cả là đã đọc",
    emptyNotification: "Hiện không có thông báo nào",
  },
  
  // --- Common units/time ---
  common: {
    seconds: "giây",
    minutes: "phút",
    hours: "giờ",
    days: "ngày",
  },

  // --- Empty States ---
  emptyList: "Danh sách trống",
  noResult: "Không tìm thấy kết quả!",
  
  // --- Buttons ---
  close: "Đóng",
  done: "Xong",
  seeAll: "Xem tất cả",
};
/* eslint-disable max-len */