import { PERMISSIONS } from "react-native-permissions";
import { Device } from "./ui/device.ui";
export const PERMISSION = {
  permissionMedia: Device.isIos
    ? [
        PERMISSIONS.IOS.CAMERA,
        PERMISSIONS.IOS.MICROPHONE,
        PERMISSIONS.IOS.PHOTO_LIBRARY,
      ]
    : [
        PERMISSIONS.ANDROID.CAMERA,
        // PERMISSIONS.ANDROID.WRITE_EXTERNAL_STORAGE,
        // PERMISSIONS.ANDROID.READ_EXTERNAL_STORAGE
      ],
  permissionRecord: Device.isIos
    ? [PERMISSIONS.IOS.MICROPHONE]
    : [
        PERMISSIONS.ANDROID.RECORD_AUDIO,
        PERMISSIONS.ANDROID.WRITE_EXTERNAL_STORAGE,
        PERMISSIONS.ANDROID.READ_EXTERNAL_STORAGE,
      ],
  permissionLibrary: Device.isIos
    ? [PERMISSIONS.IOS.PHOTO_LIBRARY]
    : [
        PERMISSIONS.ANDROID.WRITE_EXTERNAL_STORAGE,
        PERMISSIONS.ANDROID.READ_EXTERNAL_STORAGE,
      ],
  permissionCamera: Device.isIos
    ? [PERMISSIONS.IOS.CAMERA]
    : [PERMISSIONS.ANDROID.CAMERA, PERMISSIONS.ANDROID.WRITE_EXTERNAL_STORAGE],
  permissionCall: Device.isIos
    ? []
    : [PERMISSIONS.ANDROID.POST_NOTIFICATIONS, PERMISSIONS.ANDROID.CALL_PHONE],
};
